#+INCLUDE: theme/style.org
#+TITLE: CPP / C++ Review
#+DESCRIPTION: cpp c++ code examples, demonstrations, design pattern and integration.
#+STARTUP: content 

 - [[wiki:index][Index]]

* Bookmarks 
** Online Tools

 + Online Compilers 

   + http://rextester.com/
     + The main selling point of this online tool is that it allows to
       save code snippets and run them again. 
     + Online C++ compiler, provides GCC, CLANG and Visual Studio
       Compiler, also known as MSVC (VC++ - Visual C++).

   + https://wandbox.org/

 + Compiler Explorer 
   + https://godbolt.org/
     * Compiler explorer - allows to explore the assembly generated by a
       wide variety of compilers, including, GNU GCC, Clang, MSVC and so on.
   + https://demangler.com/
     * Symbol demangler for MSVC and GCC.

 + Template expasion visualizer
   + http://metashell.org/index.html

 + MISC
   + [[https://www.google.ca/search?q=float%20point%20online][float point online - Google Search]]
   + [[https://www.h-schmidt.net/FloatConverter/IEEE754.html][IEEE-754 Floating Point Converter]]
   + [[http://weitz.de/ieee/][IEEE 754 Calculator]]

** Code Standards and guidelines 

 + [[https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#main][ISO C++ Core Guidelines]] - "This is a set of core guidelines for
   modern C++, C++17, C++14, and C++11, taking likely future
   enhancements and ISO Technical Specifications (TSs) into
   account. The aim is to help C++ programmers to write simpler, more
   efficient, more maintainable code."

   + [[http://www.modernescpp.com/index.php/c-core-guidelines-constructors-assignments-and-desctructors][C++ Core Guidelines: The Rule of Zero, Five, or Six - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-when-you-can-t-throw-an-exception][C++ Core Guidelines: finally in C++ - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-constructors][C++ Core Guidelines: Constructors - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-more-rules-to-concurrency-and-parallelism][C++ Core Guidelines: More Rules to Concurrency and Parallelism - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-concurrency-and-lock-free-programming][C++ Core Guidelines: Concurrency and lock-free Programming - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-rules-to-error-handling][C++ Core Guidelines: Rules for Error Handling - ModernesCpp.com]]
   + [[http://www.modernescpp.com/index.php/c-core-guidelines-type-erasure][C++ Core Guidelines: Type Erasure - ModernesCpp.com]]

 + [[https://developer.mozilla.org/en-US/docs/Mozilla/Using_CXX_in_Mozilla_code][Using C++ in Mozilla code - Mozilla | MDN]] 

 + [[https://wiki.openstack.org/wiki/CppCodingStandards#Using_Namespaces_Properly][CppCodingStandards - OpenStack]] - "Note that coding standards and
   guidelines will never be perfect and that not everyone will agree
   with every guideline or naming convention. The purpose of the
   guidelines and standards are to maintain consistency in the source
   code." 

 + [[https://google.github.io/styleguide/cppguide.html][Google C++ Style Guide]]

 + [[http://drake.mit.edu/styleguide/cppguide.html][Google C++ Style Guide for Drake]]

 + [[https://developer.lsst.io/cpp/style.html][DM C++ Style Guide — LSST DM Developer Guide Current documentation]]

 + [[https://users.ece.cmu.edu/~eno/coding/CppCodingStandard.html][C++ Coding Standard]]

 + [[https://juce.com/discover/stories/coding-standards][Coding Standards | JUCE]] - Juce code standard and its rationale and
   motivation.  

** Development 

Fail-fast approach: 

 + [[https://www.codeproject.com/Articles/1138445/Introduction-to-the-Fail-Fast-Principle-in-Softwar][Introduction to the 'Fail Fast!' Principle in Software Development - CodeProject]]
 + [[https://enterprisecraftsmanship.com/2015/09/15/fail-fast-principle/][Fail Fast principle - Enterprise Craftsmanship]]
 + [[http://ithare.com/unchecked-exceptions-for-c/][Unchecked Exceptions for C++ - IT Hare on Soft.ware]]
 + [[http://joeduffyblog.com/2016/02/07/the-error-model/][Joe Duffy - The Error Model]]
 + [[http://wiki.c2.com/?FailFast][Fail Fast]]

** Debugger 
*** GDB Front-Ends GUI 

GDB's (GNU Debugger) Front-End GUI for [U]-nix

 + [[https://sourceware.org/gdb/wiki/GDB%20Front%20Ends][GDB Front Ends - GDB Wiki]]

 + http://www.kdbg.org/ - GNU Debugger Front-End with KDE user
   interface.
   + Linux Fedora install: *$ sudo dnf install kdbg.x86_64*
   + Interface Style: KDE/QT
   + Features:
     + Syntax highligh
     + Dissably Line - Just click at a given line to show its assembly code.
     + Watch variables and expressions at any context
     + Can View the current stack of many threads
     + Inspect Stack Variables in a tree-like structure
     + View CPU Register.

 + [[https://wiki.gnome.org/Apps/Nemiver][Neminver]] - Intuitive and easy GNOME User Interface for (GDB) GNU
   Debugger.
   + Linux Fedora install: *$ sudo dnf install neminver.x86_64*
   + Interface Style: GNOME/Gtk 
   + Features:
     + Syntax highligh
     + Set/Clear breakpoints graphically by clicking.
     + Many windows to watch stack variables
     + Watch variables and C++ expressions.
     + View CPU Registers

   + https://gdbgui.com/ - Browser Front-end for GDB Server.
     + Note: requires Python.

 + https://github.com/cyrus-and/gdb-dashboard
   + GUI Style: TUI - Terminal User Interface - Keyboard driver.
   + Modular GDB Interface written in Python.

*** GDB Reference Cards 

 + [[http://visualgdb.com/gdbreference/commands/print][GDB Command Reference - print command]]

 + [[https://darkdust.net/files/GDB%2520Cheat%2520Sheet.pdf][PDF - GDB Cheat Sheet]]

** Mind Map 

Shared Libraries / Software Components 

 - Interoperability

 - Binary Compatibility

 - C-library

   - [[http://www.etalabs.net/compare_libcs.html][Comparison of C/POSIX standard library implementations for Linux]]

 - Linking

   - Static Linking

   - Dynamic Linking

 - [[http://en.wikipedia.org/wiki/Dependency_hell][Dependency Hell]]

 - API - Application Programming Interface

 - ABI - [[https://en.wikipedia.org/wiki/Application_binary_interface][Application Binary Interface]]

   - Calling Conventions

   - [[https://en.wikipedia.org/wiki/System_call][System Call]]

   - Stable and Standard ABI - C Language

   - [[https://en.wikipedia.org/wiki/Loader_(computing)][Loader (computing)]]

   - [[https://en.wikipedia.org/wiki/Dynamic_linker][Dynamic linker]]

   - [[https://en.wikipedia.org/wiki/Binary-code_compatibility][Binary-code compatibility]]

 - FFI - Foreign Function Interface 

 - Excetuable Formats

   - [[https://en.wikipedia.org/wiki/Portable_Executable][PE]] - Portable Executable / Windows (*.exe files and *.dll files)

   - [[https://en.wikipedia.org/wiki/Executable_and_Linkable_Format][ELF]] - Executable and Linkable Format / Unix (Linux, BSD ...)

   - [[https://en.wikipedia.org/wiki/Mach-O][Mach-O]] -  Mach object file format / Mach-OSX and IOS

   - [[https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats][Comparison of executable file formats]]

   - 

** Drawbacks and ABI Issues

*Drawbacks*

 + C++ is unsafe. Bugs like stack overflow, buffer overlow, null
   pointr exceptions may happen.

 + _Operating System Depedent_ - C++ may be portable, but it is not
   cross platform since it is compiled to machine code and for a
   particular operatiing system.

 + Hardware dependent (Processor Architecture) and Operating System
   Depedent. C++ is compied to machine code / binary code for a
   particular operating system and processor architecture with
   different executable formats. The most common processor
   architectures are Intel x86 (32 bits) and AMD64 (64 bits).

   + OS Windows            / Executable Format - PE-32

   + Unix (Linux, BSD ...) / Executable Format - ELF

   + Mac-OSX               / Executable Format - Mac-O

   +

 + _No Standard ABI (Application Binary Interface)_ - C++ shared
   libraries and programs compiled with different compilers or
   different versions of same compiler may be incompatible because
   unlinke C, C++ doesn't have a standard ABI. It makes hard to call
   libraries written in C+++ through an FFI - Foreign Function
   Interface form another programming language such as Python.


*ABI Issues* - Credits: *Defining a Portable C++ ABI* - https://isocpp.org/files/papers/n4028.pdf

_A C++ developer cannot compile C++ code and share the object file with_
_other C++ developers on the same platform and know that the result_
_will compile and link correctly_. Our status quo is that two source
files a.cpp and b.cpp can only be linked together if they are compiled
with both:" -- ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])

 - "the same version of the same compiler, or another compiler with a
   compatibility mode" ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])

 - "compatible switch settings, since most C++ compilers offer
   incompatible switch settings where even compiling two files with
   the same version of the same compiler will not link successfully."
   ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])



Issues:

 - "It makes sharing binary C++ libraries more difficult: _To ship a C++_
   _library in binary form for a given platform requires building it_
   _with possibly dozens of popular combinations of switch settings for_
   the popular compiler(s) on that platform, and then may not cover
   all combinations. Alternatively, one can wrap the library in that
   platform’s stable C ABI, which brings us to…"  ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])



 - "_It is a valid reason to use C: This is (the) one area where C is_
   _superior to C++_. Among programs and programmers who would otherwise
   use C++, _the top reason to use C appears to be the inability to_
   _publish an API with a stable binary ABI_, including that it can be
   linked to from C, C++, and other languages’ foreign function
   interfaces (FFIs) such as Java JNI and .NET PInvoke. In
   particular…"  ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])



 - "_It therefore creates ongoing security problems: The fact that C is_
   _the only de facto ABI-stable lingua franca continues to encourage_
   _type- and memory-unsafe C APIs that traffick in things like error_
   prone pointer/length pairs instead of more strongly typed and still
   highly efficient abstractions, including but not limited to
   std::string or the new string_view"  ([[https://isocpp.org/files/papers/n4028.pdf][Herb Sutter]])


*Solutions to ABI compatibility issues*

 1) _Distribute the library in source format_. Approach adopted by QT
    (former Trolltech Inc, now the QT Company) with open source and
    commercial license.

 2) Distribute the library in binary format and only support a
    specific compiler.

 3) _Compile he C++ shared library with all possible compilers_ and
    distribute the binaries for each compiler, compiler version,
    processor architecture and operating system.

 4) _Write the library in C, instead of C++_. This approach is followed
    by most Unix/Linux libraries and OpenGL and Gtk GUI toolkit.

 5) Use some language that can compile/generate C-code (transpiler).

 6) Use Microsoft COM (Component Object Model)/ DCOM or CORBA, DBUS ... 



Note: C is until now the only language with a standard and public ABI
and most OS exposes its API through a C interface, programming
languages runtimes are generally implement in C.

** Compiler Metadata Generators

 + [[https://pygccxml.readthedocs.io/en/develop/upgrade_issues.html][GCC-XML 0.7 → 0.9 upgrade issues (Legacy) — pygccxml 1.9.1 documentation]]

** C => to C++ Guidelines

+ Malloc - Avoid malloc and manual memory management. Instead of that
  use _new_ and _vector_ instead of realloc.
+ Pointer - Avoid pointers.
+ Arrays - Use C++ STL vector classes instead of arrays.
+ Strings. Don't use array of characters to represent a string,
  instead of that use c++ strings by inclunding '#include <string>'
  header at the top of file.
+ Separate the operating system depedent code from the
  operating system agnostic code.

** C++ Resources

*C++ General Resources*

 - Ian D. Chivers - *An Introduction to C++*
   <http://www.icsd.aegean.gr/lecturers/kavallieratou/Cplusplus_files/notes.pdf>

 - [[https://www.reddit.com/r/Physics/comments/2w4exo/what_are_the_useful_aspects_of_c_in_physics/][What are the useful aspects of C++ in Physics programming? : Physics]]

 - [[https://anteru.net/blog/2016/05/01/3249/][Designing C APIs in 2016 | Anteru’s blog]]

*C++ Numerical Methods and Scientific Computing*

 - Prof. R. Hiptmair, SAM, ETH Zurich. *Numerical Methods for
   Computational Science and Engineering* -
   <http://www.sam.math.ethz.ch/~hiptmair/tmp/NumCSE/NumCSE15.pdf>


 - Norbert Pozar. *Basic C++ for numerical computations: vectors*
   <http://polaris.s.kanazawa-u.ac.jp/~npozar/basic-cpp-for-numerics-vectors.html>


*C++ STL - Standard Template Library*


 - *A modest STL tutorial*
   <http://cs.brown.edu/~jak/proglang/cpp/stltut/tut.html>


 - Carlos Moreno. *C++ Vectors* <https://cal-linux.com/tutorials/vectors.html>


*C++ ABI - Application Binary Interface, Binary Compatibility and FFI*

 - By Agner Fog. *Calling conventions for different C++ compilers and
   operating systems*
   <http://www.agner.org/optimize/calling_conventions.pdf>


 - Armin Ronacher. *Beautiful Native Libraries*
   <http://lucumr.pocoo.org/2013/8/18/beautiful-native-libraries/>


 - Herb Sutter. *Defining a Portable C++ ABI* <https://isocpp.org/files/papers/n4028.pdf>

 - *Some thoughts on binary compatibility*
   <http://blog.qt.io/blog/2009/08/12/some-thoughts-on-binary-compatibility/>

 - *Interoperability of Libraries Created by Different Compiler
   Brands* <http://www.mingw.org/wiki/Interoperability_of_Libraries_Created_by_Different_Compiler_Brands>

 - Thiago Macieira. *Binary compatibility for library developers*
   <https://events.linuxfoundation.org/sites/events/files/slides/Binary_Compatibility_for_library_devs.pdf>

 - *What Language I Use for… Creating Reusable Libraries: Objective-C*
   <http://www.informit.com/articles/article.aspx?p=2144812>

 - *Compilable modern alternatives to C/C++* -
   <https://softwareengineering.stackexchange.com/questions/162614/compilable-modern-alternatives-to-c-c>

 - [[https://stackoverflow.com/questions/3217513/are-llvm-gcc-and-clang-binary-compatible-with-gcc-particularly-mingw-gcc-on-w][linker - Are llvm-gcc and clang binary compatible with gcc? - particularly mingw gcc on Windows - Stack Overflow]]

 - [[http://rlc.vlinder.ca/blog/2009/08/binary-compatibility/][Binary Compatibility | Making Life Easier]]

 - *System V Application Binary Interface AMD64 Architecture Processor
   Supplement* <https://c9x.me/compile/bib/abi-x64.pdf>

 - *Software optimization resources* - <http://www.agner.org/optimize/>

 - [[https://softwareengineering.stackexchange.com/questions/281882/why-does-c-provide-language-bindings-where-c-falls-short][Why does C provide language 'bindings' where C++ falls short? - Software Engineering Stack Exchange]]

 - [[https://news.ycombinator.com/item?id=2379676][I've written in C++ professionally almost 12 years (17 years counting College), ... | Hacker News]]

 - [[https://www.reddit.com/r/swift/comments/67z7dy/what_is_abi_stability_and_why_does_it_matter/][What is ABI stability and why does it matter? : swift]]

 - [[https://www.reddit.com/r/programming/comments/4r6r8e/abi_vs_api/][ABI vs. API : programming]]

 - [[https://www.reddit.com/r/linux_gaming/comments/5nqaux/confused_about_compatibility/dcdxd19/][heartsofwar comments on Confused about Compatibility]]

 - [[https://www.reddit.com/r/askscience/comments/3ei05n/why_is_that_programs_need_to_be_ported_between/][Why is that programs need to be ported between operating systems in order in to function? What goes on at the programming level to require this? : askscience]]

 - [[https://www.reddit.com/r/AskProgramming/comments/5c74i4/some_thoughts_about_abis/][some thoughts about ABIs : AskProgramming]]

 - [[http://damienkatz.net/2013/01/the_unreasonable_effectiveness_of_c.html][Damien Katz: The Unreasonable Effectiveness of C]]

 - [[https://www.reddit.com/r/linux/comments/42vngw/why_is_the_linux_community_ambivalent_about/][Why is the Linux community ambivalent about binary compatibility? : linux]]

 - [[https://www.reddit.com/r/C_Programming/comments/4afu69/implementing_cross_platform_library_in_c_proscons/][Implementing cross platform library in C pros/cons C_Programming]]

 - 

 - 

*C-Interface* 

 - *CppCon 2014: Stefanus DuToit "Hourglass Interfaces for C++ APIs* -
   <https://www.youtube.com/watch?v=PVYdHDm0q6Y>


*FFI - Foreign Function Interface*

 - https://en.wikipedia.org/wiki/Foreign_function_interface

 - [[http://www.mono-project.com/docs/advanced/pinvoke/][Interop with Native Libraries | Mono]]

 - [[https://en.wikipedia.org/wiki/SWIG][SWIG - Wikipedia]] -  Simplified Wrapper and Interface Generator

 - [[https://sourceware.org/libffi/][libffi]] - A Portable Foreign Function Interface Library

 - [[https://en.wikipedia.org/wiki/Libffi][libffi - Wikipedia]]

 - [[https://docs.python.org/3/extending/extending.html][1. Extending Python with C or C++ — Python 3.6.1 documentation]]

 - [[https://msdn.microsoft.com/en-us/library/aa288468(v=vs.71).aspx][Platform Invoke Tutorial (C#)]]

 - [[https://www.reddit.com/r/explainlikeimfive/comments/5c2yfq/eli5_how_can_a_single_software_project_use/][Eli5: How can a single software project use multiple languages? Wouldn't the compiler have difficulty understanding what's what? : explainlikeimfive]]

 - [[https://www.reddit.com/r/learnprogramming/comments/3dzif8/how_do_you_communicate_between_different_computer/][How do you communicate between different computer languages? : learnprogramming]]


*Courses and Online Books*

 - [[https://en.wikibooks.org/wiki/C%2B%2B_Programming][C++ Programming - Wikibooks, open books for an open world]]


 - Francois Fleuret. *C++ lecture notes*
   <https://www.idiap.ch/~fleuret/files/Francois_Fleuret_-_C++_Lecture_Notes.pdf>


 - Course:  https://www3.ntu.edu.sg/home/ehchua/programming/

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp0_Introduction.html][An Introduction to C++ Programming for First-time Programmers - C++ Programming Tutorial]] - https://archive.is/MRDZI

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp9_STL.html][C++ Libraries, String and Standard Template Library]] - https://archive.is/lrIDk

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp2_MoreBasics.html][C++ More Basics]] - https://archive.is/pr7pn

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp3_OOP.html][Object-oriented Programming (OOP) in C++]] - https://archive.is/lpXae

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp4_PointerReference.html][C++ Pointers and References]] - https://archive.is/Ja1xJ

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp5_OOPExamples.html][Examples on Classes and Objects]] - https://archive.is/eZJPl

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp8_Template.html][Object-oriented Programming (OOP) in C++ - Template and Generic Programming]] - https://archive.is/eG0KZ

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp9_String.html][C++ Libraries, String and Standard Template Library]]

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp9_String.html][C++ Libraries, String and Standard Template Library]]

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp10_IO.html][C++ IO Streams and File Input/Output]]

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp11_TipsTraps.html][Examples on Classes and Objects]]

   - [[https://www3.ntu.edu.sg/home/ehchua/programming/cpp/DataStructureAlgorithm.html][Data Structure and Algorithm]]

*Unix - API / LibC*

 - *User space and the libc interface* - <https://www.win.tue.nl/~aeb/linux/lk/lk-3.html>


*Embedded Systems*

 - [[http://bitbashing.io/embedded-cpp.html][C++ On Embedded Systems]]

 - [[http://git.eti.pg.gda.pl/intel-grant/pliki/esp/ESP_Toolchain_ENG.pdf][Embedded Systems Programming OS Linux - Toolchain]]

 - 

*Alternatives to C++*

The C++ language is suitable for system programming, writing native
applications and writing high performance software components or
libraries. However the lack of standard ABI - Application Binary
interface makes calling C++ calling a C++ library through FFI -
Foreign Function Interface in another language harder.

Due to the C++ ABI issues, many portable libraries that are easier to
invoked through a FFI are written in C, for instance, GTK GUI toolkit,
... 

Selection Requirements: 

 - Compile to native code.

 - Have an stable and standard ABI - Application Binary Interface like C.

 - Be able to build shared libraries *.so or *.dll and easily invoked
   through FFI - Foreign Function Intefaces of high level languages
   such as Python, Ruby, Java, C# and so on.

 - Be memory safe in order to avoid buffer overflow. 


_D language_


   - [[http://bitbashing.io/2015/01/26/d-is-like-native-python.html][D is like native Python]]

   - [[http://code.dlang.org/packages/pyd][Package pyd version 0.9.9 - DUB - The D package registry]]

   - [[http://dlang.org/spec/abi.html][Application Binary Interface - D Programming Language]] 

   - [[https://dlang.org/dll-linux.html][Writing Shared Libraries With D On Linux - D Programming Language]]

   - [[http://blog.tenstral.net/2016/05/adventures-in-d-programming.html][Adventures in D programming | Ximions Blog]]

_Gambit Scheme_ 

A Scheme implementation that is interactive with a REPL and that can
generate C-code and invoke C-libraries. It can be compiled to
shared libraries *.so or *.dlls and be called from scheme REPL.

_Rust_

* Selected Conference Videos 
** Misc 
*** Bjarne Stroustrup - The Essence of C++

- [[https://www.youtube.com/watch?v=86xWVb4XIyE][Bjarne Stroustrup - The Essence of C++]]
  - "Bjarne Stroustrup, creator and developer of C++, delivers his
    talk entitled, The Essence of C++. Stroustrup has held
    distinguished posts at Texas A&M University and spent significant
    time in the Computer Science Departments of Cambridge, Columbia
    and Princeton. C++ is the one of the world's most widely used
    technology languages and it has influenced newer languages such
    as C# and Java as well as older languages."
    + Applications on System Programming Domains:
      - Device drivers
      - Network drivers
      - Embedded Systems
      - Suitable for hard and soft real time systems.
    + C++ Origin: C + Simula (First Object Oriented language)
    + Main Ideas:
      - Direct map to hardware
      - Zero-overhead abstraction
      - Much of inspiration comes from operating systems.
      - Backward compatibility: Avoid breaking old code.
    + Key strengths:
      + A language for building lightweight abstractions.
      + Software infrastructure.
      + Resource-constrained application. (May be embedded systems)
      + Resource Management
*** CppCon 2017: Michael Spencer "My Little Object File: How Linkers Implement C++"

 - [[https://www.youtube.com/watch?v=a5L66zguFe4][CppCon 2017: Michael Spencer “My Little Object File: How Linkers Implement C++” - YouTube]]
   - "Ever wonder how the linker turns your compiled C++ code into an
     executable file? Why the One Definition Rule exists? Or why your
     debug builds are so large? In this talk we'll take a deep dive
     and follow the story of our three adventurers, ELF, MachO, and
     COFF as they make their way out of Objectville carrying C++
     translation units on their backs as they venture to become
     executables. We'll see as they make their way through the tangled
     forests of name mangling, climb the cliffs of thread local
     storage, and wade through the bogs of debug info. We'll see how
     they mostly follow the same path, but each approach the journey
     in their own way.  We'll also see that becoming an executable is
     not quite the end of their journey, as the dynamic linker awaits
     to bring them to yet a higher plane of existence as complete C++
     programs running on a machine."
*** CppCon 2017: Mathieu Ropert "API & ABI Versioning"

- [[https://www.youtube.com/watch?v=Ia3IDPjA-d0][CppCon 2017: Mathieu Ropert “API & ABI Versioning...” - YouTube]]
  - "Software keeps changing, but not always as fast as its
    clients. A key to maintaining a library in the long run is to
    ensure a proper versioning of the API and ABI. Not only does this
    gives a clear picture of both source and binary compatibility
    between the versions, but it also helps design by making breaking
    changes explicit to the developer.  In this talk I will define
    API and ABI in terms of impacts on compatibility, explain the
    difference between breaking and non-breaking changes and present
    a few techniques to handle them.  We will quickly explain what
    APIs are, with an emphasis on the notion of contracts. Then the
    usually lesser known notion of ABI will be explained, going over
    the concepts of call syntax, mangling and most importantly sizes,
    alignment and offsets in data structures. We will see how to use
    semantic versioning (semver) in C++ by considering not only
    changes to the API but also to the ABI and offer some advice on
    how to change API and ABI over time and how to minimize the
    impacts."
*** C++Now 2018: Louis Dionne "Runtime Polymorphism: Back to the Basics"

- [[https://www.youtube.com/watch?v=OtU51Ytfe04][C++Now 2018: Louis Dionne “Runtime Polymorphism: Back to the Basics” - YouTube]]
  + Description: "C++ solves the problem of runtime polymorphism in a very
    specific way. It does so through inheritance, by having all
    classes that will be used polymorphically inherit from the same
    base class, and then using a table of function pointers (the
    virtual table) to perform dynamic dispatch when a method is
    called. Polymorphic objects are then accessed through pointers to
    their base class, which encourages storing objects on the heap
    and accessing them via pointers. This is both inconvenient and
    inefficient when compared to traditional value semantics. As Sean
    Parent said: Inheritance is the base class of evil. It turns out
    that this is only one of many possible designs, each of which has
    different tradeoffs and characteristics. This talk will explore
    the design space for runtime polymorphism in C++, and in
    particular will introduce a policy-based approach to solving the
    problem. We will see how this approach enables runtime
    polymorphism with stack-allocated storage, heap-allocated
    storage, shared storage, no storage at all (reference semantics),
    and more. We will also see how we can get fine-grained control
    over the dispatch mechanism to beat the performance of classic
    virtual tables in some cases. The examples will be based on a
    real implementation in the Dyno library [1], but the principles
    are independent from the library."

    + Problem: C++ sub-typing polymorphism inevitably requires
      pointers to objects allocated on the heap. However by using
      pointers, the advantages of value semantics, which C++ is built
      on top, are lost. For instance, pointers doesn't play well with
      C++ algorithms and functions expecting value or reference
      parameters. Another issue is that pointers to objects allocated
      on the heap raises questions about memory ownership such as who
      should delete the pointer.

      + Ideas => some possible approaches:
        + Use static polymorphism: _template functions._
        + Use a _proxy object allocated on the stack._ The object
          inherits the base class and takes a pointer to base class
          as argument. Then the proxy object can forward any method
          call or message to the wrapped heap object.
        + Deal with it and accept as it is for performance reasons.
** Functional Programming 
*** CPPCON-2017: Klaus Iglberger - Free Your Functions

+ [[https://www.youtube.com/watch?v=WLDT1lDOsb4][CppCon 2017: Klaus Iglberger "Free Your Functions!"]]
  * Description: "You are devoted to minimize coupling and
    duplication? You are taking care to maximize cohesion,
    flexibility, extensibility, encapsulation, testability, and even
    performance in order to achieve the high goals of
    (object-oriented) programming? Awesome!  But wait: You still
    favor member functions? Seriously? You have been deceived! You
    have been praying at the altar of false promises! Shed the
    shackles of Java philosophy! Free your functions!. In this talk I
    will demonstrate why in C++ free functions should generally be
    preferred to member functions, and why free functions — not
    member functions! — provide you with all the aforementioned
    advantages you expect from object-oriented programming. Note,
    though, that this talk might fundamentally change your perception
    of C++ and object-oriented programming in general!"

  * _Summary and notes_:
    * _Free functions_ (ordinary functions or non-virtual functions)
      abides to object oriented principles such as OCP (Open-Close
      Principle) as they can extend a class without requiring
      modification or recompilation of the class source code.
    * _Static polymorphism_ which is a combination of free functions
      and _template metaprogramming_ can make the code more loosely
      coupled and more perfomant.
      * Becomes more loosely coupled because it doesn't require that
        arguments have any common base class or class hierarchy.
      * Becomes more performant as template generates overloaded code
        for each different type parameters combination what
        eliminates virtual function calls and dynamic
        polymorphism. The disadvantage of templates are the higher
        complexity and larger code size.
    * Benefits of Free Functions:
      - Encapsulation
      - Cohesion (SRP - Single Responsibility Principle)
      - Reuse (DRY - DO NOT REPEAT YOURSELF)
      - Overloading (Polymorphism )
      - Generic Programming (Aka template metaprogramming)
      - Abstraction
      - Testability
      - _Performance_ (Raison d'être of C++).

    * Free Functions on standard library:
      - std::begin, std::cbegin ...

    * Use free functions in order to:
      * ... wrap virtual function calls
      * ... get an homogeneous interface.
      * ... get more performant code.
      * ... more flexible and loosely-coupled code.

    * Free functions aren't are multi-paradigm, they can work with
      any paradigm. It is not necessarly functional programming. 

    * Potential Problems
      * C++ doens't have a convenient syntax for function application
        as ML-based languages like Haskell and OCaml. So, multiple
        function applications would be written as f1(f2(f3(f5 ... fn(x))))

      * _Discoverability_: according to the presentation, IDE's may not
        help to find them easily as they help to find methods (aka
        member functions). However it can mitigated with careful
        selection of namespaces which would improve code complexion
        and discoverability.
** Tools 
*** LVM Euro Conference 2013 - The Clang AST - a Tutorial

+ [[https://www.youtube.com/watch?v=VqCkCDFLSsc][The Clang AST - a Tutorial - YouTube]]
  + "If you always wanted to know more about about Clang's AST [1],
    for example because you want to implement an awesome tool [2, 3]
    based on Clang, or simply because you want to start contributing,
    this talk is for you."
  + Note: Clang + LLVM suite provides many services that can be used
    to build code automation tools for C++ such as code generators
    and reflection metadata code generator.
*** CppCon 2018: "Latest and Greatest in the Visual Studio Family for C++ Developers 2018" :tooling:

  + [[https://www.youtube.com/watch?v=6NAAuxWNhk4&feature=youtu.be][CppCon 2018: “Latest and Greatest in the Visual Studio Family for C++ Developers 2018” - YouTube]]
    + "This talk will be modeled on our previously successful talks at
      CppCon. We'll give the community an update on how we are doing
      in terms of conformance where we'll be announcing the final
      conformance state for MSVC for the final 2017 update. We'll be
      showing many many demos of new features (not in previous
      versions of this talk) that target cross platform developers in
      C++. This will include making it easier to bring your code to
      Visual Studio, significant improvements to ease of use for
      developers using CMake, improvements to unit testing
      experiences, a lot of new Linux targeting improvements, an
      update on our performance work, and new debugger features for
      C++ developers. Developers will learn new tricks they can apply
      immediately on leaving the session as well as get a sense of
      what is coming in future updates. The main message is that
      Visual Studio and Visual Studio Code will make every C++
      developer (not just Windows developers) more productive." 

  + Features:

    + Fredom to target any platform from a single ID:
      + ARM/mBed, Android, Cyngwin, iOS, Linux, UWP, Windows

    + CMake compatibility

    + The VC++ Compiler has full support for C++11/14/15 language features.

      + Process Snapshot - allows to introspect process memory.

      + Macro expansion - The editor, now can expand macros when the
        mouse is hoovered over some macro.

      + Completion for templates.

      + Live Sharing => Collaboration session. 

      + Multiple cursor editing, aka multi caret editing: hold CTRL +
        ALT and click at the points where the cursor will be placed
        and then type.

      + Peek definition.

      + Compiler flags:
        + /std:c++14 (default)
        + /std:c++17
        + /std:c++latest
        + /experimental:external  - Switch to isolate code from
          external headers.

      + C++ Core Check - https:/aka.ms/CppCoreCheck

    + Integratio with other building systems: Make, Ninja, NMake, ... 

    + Code editing experience:
      + IntelliSense => Smart Code Completion 
      + Refactoring
      + Debugging
      + Reverse Debugging
      + Debug Visualization

    + Integration with other compilers and tools:
      + Clang/LLVM, GCC, Clang-format, Google-test, Boost.Test

    + Recommended Package Manger: *Vcpakge* - cross platform package
      manager which works on Linux, MacOSX and Windows. There are over
      900 libraries available in that.

      + $ vcpackage install boost sdl zlib gtest
      + https://aka.ms/vcpkg 

    + Can compile and run code in remote machines and also perform
      remote debugging. 

    + One of the most valued and loved of feature of Visual Studio is
      the *debugger*.
      + The debugger can attach to process in current or remote
        machine through SSH.

    + *CMake target view* provides a CMake-centric experience showing
      all targets, files and configuration.

    + *Open folder experience:*
      + Optmized for non-MSBuild projects => any project using CMake,
        make or other C++ building system. Target Windows, MinGW,
        Cyngwin, Linux or mBed.
      + Easy to get started
        + devenv.exe <folder>
        + File => Open => Folder ... (Ctrl + Alt +Shift + O)

    + Linux Targeting:
      + Visual Studio can connect to any linux distribution with
        GDB or GdbServer. Remove VMs, Containers, IoT (RasberryPI, Beaglebone),
        Local Windows Subsystem for Linux distros and Cross-Compile.
*** Rapid Prototyping in C++ - Dmitri Nesteruk - Meeting C++ 2015

 - [[https://www.youtube.com/watch?v=Ncy4Y-k-vLA][Rapid Prototyping in C++ - Dmitri Nesteruk - Meeting C++ 2015 - YouTube]]
   * Description: Show several techniques for fast prototyping in C++.
   * Summary:
     + CERN's ROOT Framework or CLING C++ interpreter. Allows to play
       and evaluate C++ code in the same fashion Python interpreter does.
     + Wrap the C++ library with SWIG wrapper generator to generate a Python binding and
       then prototype in the Python REPL.
     + Use a more suitable tool with fast feedback for prototyping
       such as spreadsheet, R language, Python, Matlab, Octave and so
       on.
     + Runtime compiled C++.
*** CppCon 2018: Steven Simpson "Source Instrumentation for Monitoring C++ in Production" :tooling:instrumentation:

 + [[https://www.youtube.com/watch?v=0WgC5jnrRx8&feature=youtu.be][CppCon 2018: Steven Simpson “Source Instrumentation for Monitoring C++ in Production” - YouTube]]
   + "It is essential to discuss how modern C++ code can be
     effectively instrumented, in order to effectively monitor it
     after deployment. *This talk will focus on portable source*
     *instrumentation techniques such as logging, tracing and*
     *metrics*. Straightforward, but well designed code additions can
     drastically ease the troubleshooting of functional issues, and
     identification of performance bottlenecks, in production.  Of
     course when dealing with C++ performance is often critical, and
     so minimizing the cost of any instrumentation is also
     critical. Key to this is understanding the trade-off between the
     detail of information collected, and the overheads of exposing
     that information. It is also important to understand how best to
     benefit from advances in contemporary monitoring infrastructure,
     popularised by "cloud" environments.  This talk will open with a
     brief summary of monitoring goals, infrastructure, benefits, and
     existing practise. It will then detail practicalities of building
     a set of C++ source instrumentation primitives, based on proven
     principles employed in demanding production software."

 
   + Summary + Notes + Brainstorm:
     * Use a logging library with the following features.
       + Format string (or ostream)
       + Serverity levels, [INFO], [WARNING], [FAILURE], [CRITICAL], [TRACE] ...
       + Enable/disable at runtime
       + Logs files + rotation
       + Timestamp 
       + Remote Logging
       + OS Integration => Syslog on U*nix, or OutputDebugString on Windows.

     * Error messages and exception should have context about the
       problem such as the file where it happened, code line, what
       caused the exception and so on. 

     * Log Service infrastructure:
       + Should support search, indexing, sorting and filtering.
       + Structured Logging Format: json, csv, to avoid parsing and
         writing complicated regular expressions.
       + Logging Alert
       + Logging can be stored in cloud services. 

     * Logging X Tracing

       + A more detailed logging, showing the internals of some
         operation for debugging purposes. 

       + Example about tracing: Unix utility strace which log system
         calls perfomed by a program. $ strace -ttT cat hello.txt    

     * Downsides of logging:
       * Logging may, specially writing to IO, may cause performance
         overhead on performance critical code. This is why tracing
         logging in this type of code is often disabled on deployment
         builds.
       * Tracing can be implemented with C-preprocessor macros in
         order to allow disabling it on debug builds. Using
         preprocessor has also the advatange that, when the tracing is
         disabled, it will not inccur on any rutime overhead or
         performance cost, as string concatenation will not happen and
         the code will be discarded. 
  
     * Domains where logging is essential:
       * _Network Servers and Web Servers_. => Servers are long running
         programs which runs in background as daemons without any
         graphical user interface. So logging, is the only available
         information about what is going on with the sefver.
       * _Databases_ 
       * _Embedded Systems_ => Usually doesn't have keyboard, monitor
         and etc.
       * _Industrial Instrumentation_ => Temperature, pressure, speed, ... 

     * Closing:
       * By building observable software, the software can become its
         own debugger. 

     * *Techniques for Program Instrumentation* => My Ideas.
       * Logging with some logging library
       * Debug Build 
         * Debugging Symbols 
         * Assertions => Allows to check assumptions during the
           development. 
         * Tracing
       * Use a proper debugger such as GDB, WindBG, LLDB for
         instrospecting the process. 
       * Proper error messages with enough context information. 
       * Unit Tests or some automated testing.
       * System call logger such as strace.
       * Memory Leak Detector such as Valgrind.
       * Profiler => Mesure performance.
       * Compiler with non cryptic error messages like Clang++.
       * Enforce as much correctness as possible at compile-time in
         order to catch bugs earlier before runtime and deployment.
** High Performance Computing for Math 
*** CPPCON 2016: Klaus Iglberger "The Blaze High Performance Math Library"

 - [[https://www.youtube.com/watch?v=w-Y22KrMgFE][CppCon 2016: Klaus Iglberger “The Blaze High Performance Math Library" - YouTube]]
   - "In this presentation we introduce the Blaze C++ math library, a
     hot contender for the linear algebra performance throne. Blaze
     is an open-source, high-performance library for dense and sparse
     arithmetic. It combines elegance and ease of use with HPC-grade
     performance, making it one of the most intuitive and at the same
     time fastest C++ math libraries available. We demonstrate its
     basic linear algebra functionality by means of several BLAS
     level 1 to 3 operations and explain why Blaze outperforms even
     well established linear algebra libraries. Additionally, we
     present some advanced features that enable users to adapt Blaze
     to special circumstances: custom data structures, custom
     operations, and the customizable error reporting mechanism."

     - Note: Blaze library uses _Express Template_ technique for
       compile-time generation of high-performance linear algebra
       code. 
*** Statistical scientific programming OO patterns: accumulators - Olivia Quinet - Lightning Talks :math:science:
 
 + [[https://www.youtube.com/watch?v=IwvA7oExmSo][Statistical scientific programming OO patterns: accumulators - Olivia Quinet - Lightning Talks - YouTube]]
   + "Statistical scientific programming OO patterns: accumulators -
     Olivia Quinet - Lightning Talks Meeting C++ 2017"
     + Summary: Accumulators like Boost.Accumulators allows to compute
       several statistical properties of a set of values such as a
       time series avoiding errors such as _float pointing_
       _castastrophic cancellation_ and loss of precision. The Welford
       statistical formula is shown as a way to implement accumulators
       and how it can be used to compute standard deviation and other
       statistical properties. 
*** Algorithms and Iterators for Multidimensional Arrays - Cem Bassoy - Lightning Talks Meeting C++ 2017 :math:science:

  + [[https://www.youtube.com/watch?v=8P-sDH9XJAc][Algorithms and Iterators for Multidimensional Arrays - Cem Bassoy - Lightning Talks Meeting C++ 2017 - YouTube]]

Paper at:  [[https://arxiv.org/abs/1711.10912][1711.10912 - TLib: A Flexible C++ Tensor Framework for Numerical Tensor Calculus]]

Abstract:

#+BEGIN_QUOTE
Numerical tensor calculus comprise basic tensor operations such as the
entrywise addition and contraction of higher-order tensors. We
present, TLib, flexible tensor framework with generic tensor functions
and tensor classes that assists users to implement generic and
flexible tensor algorithms in C++. The number of dimensions, the
extents of the dimensions of the tensors and the contraction modes of
the tensor operations can be runtime variable. Our framework provides
tensor classes that simplify the management of multidimensional data
and utilization of tensor operations using object-oriented and generic
programming techniques. Additional stream classes help the user to
verify and compare of numerical results with MATLAB. Tensor operations
are implemented with generic tensor functions and in terms of
multidimensional iterator types only, decoupling data storage
representation and computation. The user can combine tensor functions
with different tensor types and extend the framework without further
modification of the classes or functions. We discuss the design and
implementation of the framework and demonstrate its usage with
examples that have been discussed in the literature.

#+END_QUOTE    
** C++ Binary Components + ABI + Reflection 
*** CPPCON 2016 - C++14 Reflections Without Macros, Markup nor External Tooling :reflection:metaprogramming:templates:

 + [[https://www.youtube.com/watch?v=abdeAew3gmQ][CppCon 2016: "C++14 Reflections Without Macros, Markup nor External Tooling.." - YouTube]]
   + "C++ was lacking the reflections feature for a long time. But a
     new metaprogramming trick was discovered recently: we can get
     some information about POD structure by probing it's braced
     initializes. Combining that trick with variadic templates,
     constexpr functions, implicit conversion operators, SFINAE,
     decltype and integral constants we can count structure's fields
     and even deduce type of each field.  Now the best part:
     everything works without any additional markup nor macros
     typically needed to implement reflections in C++.  In this talk
     I'll explain most of the tricks in detail, starting from a very
     basic implementation that is only capable of detecting fields
     count and ending up with a fully functional prototype capable of
     dealing with nested PODs, const/volatile qualified pointers,
     pointers-to-pointers and enum members. Highly useful use-cases
     will be shown a the end of the talk. You may start experimenting
     right now using the implementation at".
*** NDC Conference - Introduction to C++ Template Metaprogramming - Sasha Goldshtein :tmp:templates:

 + [[https://www.youtube.com/watch?v=lrziylOWBT4][Introduction to C++ Template Metaprogramming - Sasha Goldshtein]]
   + "technique in modern C++. First, TMP can be used as a precursor
     to C++17 Concepts, in order to check constraints and produce
     clear error messages when a template parameter doesn't adhere to
     its specified constraints. Second, TMP can be used to pick an
     algorithm implementation based on the template type provided --
     thus enabling optimizations for specific types. Finally, TMP can
     be used to introspect C++ types at compile-time and generate
     compile-time constructs that save time or enable
     fully-compile-time computation. In this talk, we will review a
     collection of techniques and examples for using TMP in your
     libraries and application code. You are expected to understand
     basic template syntax and template specialisation, and we will
     build the rest as we go along." 
*** CppCon 2018: Victor Ciura "These Aren't the COM Objects You're Looking For"

 + [[https://www.youtube.com/watch?v=T_1zutIBHs0][CppCon 2018: Victor Ciura “These Aren't the COM Objects You're Looking For” - YouTube]]
   + Description: "Windows COM is 25 years old. Yet it is relevant
     today more than ever, because Microsoft has bet its entire
     modern WinRT API on it (starting with Windows 8/10). But, if
     you’re familiar with the “old” COM with its idioms and SDK
     helper classes, you’re in for a treat. With the advent of modern
     C++ 17, using COM objects and new Windows APIs in your
     applications feels like a completely new experience. In this
     session, we’ll explore how using modern C++ features can
     radically transform the shape of your COM code. By eliminating a
     lot of boilerplate, your code will be much more readable and
     maintainable. Classic COM idioms around activation and
     QueryInterface() can feel totally different with modern C++
     helpers. A beautiful example of modern COM usage is C++/WinRT
     (now part of Windows SDK). This is a standard C++ language
     projection for the new Windows Runtime API.  COM memory
     management, data marshalling, string handling can all feel quite
     mechanical in nature and very error prone, so a little help from
     modern C++ facilities would be more than welcomed. Error
     handling and debugging can be cumbersome for COM like APIs;
     we’ll explore some tricks to improve this experience, as well."
*** BoostCon: John Bandela - Easy Binary Compatible C++ Interfaces Across Compilers
 
 + [[https://www.youtube.com/watch?v=BbbqBJ94-_E][John Bandela: Easy Binary Compatible C++ Interfaces Across Compilers - YouTube]]
   + Description: C++ is often perceived as hard to use and not as
     productive as other languages. One of the reasons for this is
     the lack of interoperability of binary components. When using a
     library, the user then either has to build from source (further
     complicated by the fact that there are multiple build systems)
     or the creator has to distribute multiple binaries. For example
     on Windows, one may have to distribute binaries for GCC Mingw,
     Visual C++ 2010 (release and debug, static and dynamic CRT),
     Visual C++ 2012, etc. There have been attempts to get around
     this problem. Options range from "extern C" functions, COM or
     XPCOM, or language extensions such as C++/CX. The above options
     either require compiler extensions or feel foreign and low-level
     to someone who is used to Modern C++. With C++11 being more
     consistently implemented across more compilers, one can take
     advantage of features such as lambdas and variadic templates to
     create easy to define, use, and implement binary interfaces that
     will work across compilers.
     + This presentation will discuss the design and implementation of
       a library that has the following benefits:
     + No external tools to run
       * Define an interface once and use the definition for both implementation and usage
       * Interfaces are easy to implement and use once defined
       * Use std::string, std::vector, and std::pair in the interface
       * Use real return types (not error codes)
       * Use exceptions both in implementation and usage
       * Binary compatible with COM
       * Supports interface inheritance
       * Supports implementation inheritance
       * Implementation tested on Windows with Visual C++ executable and GCC .dll
       * Implementation tested on Linux with GCC executable and Clang .so
*** BoostCon: John Bandela - CppComponents- A Modern Portable C++11 Component System

 + [[https://www.youtube.com/watch?v=a4iFJuNBx7U][CppComponents- A Modern Portable C++11 Component System - YouTube]]

