#+INCLUDE: theme/style.org 
#+TITLE: CPP / C++ - Debuggers 
#+DESCRIPTION: C++ Debuggers reverse engineering introspection 
#+STARTUP: content 

 - [[wiki:index][Index]]

* GDB - GNU Debugger - Command Line 
** Overview 

 *What is a debugger?*

 + A program which allows to inspect the execution of a program
   compiled with or without debugging symbols. Essentialy a debugger
   is an "execution monitor". 

 *Common Debuggers*

 + GDB - GNU Debugger 

 + LLDB - CLang Debugger

 + WinDBG, Visual Studio Debugger (Windows-only) - Both are front-ends
   to the Windows Debugger which is just a DLL - Dynamic Linked
   Library.

 + [[http://www.ollydbg.de/][OllyDBG]] (Windows-only) - Debugger designed for reverse engineering
   with better capabilities to operate without debugging symbols. 

 + [[https://www.hex-rays.com/products/ida/debugger/index.shtml][IDA]] - Interactive Disassemble and debugger designed for reverse
   engineering. In addition Linux, Windows and OSX binaries, IDA can
   also disassemble firmwares.

 + [[http://www.valgrind.org/][Valgrind]] Memory leaking debugger (Unix-like operating systems) - No
   exactly a debugger, however it is useful for detecting memory
   leaks, profiling and so on.

 *Capabilities:*

 + Inspect any running programs or process allowing to observer
   variables and manipulating memory.

 + Attach to running process in local machine.

 + Core Dump Analysis, aka crash dump analysis - post mortem analysis
   of a program. 

 + Attach to running process in remote machine (GDB - Server)
   + It allows remote debugging of a program running in a remote
     machine over the network; Android device or program/firmware
     running in a embedded system.

 + Automation with user scripts, just a file containing GDB commands.

 + Automation with Python scripts.

 *Use case:*

 + Development tools as it helps to understand the inner working of
   some program, find bugs, trace function-calls, system-calls and get
   process state.
 + Reverse Engineering => Inspect and manipulate any process at runtime.
 + Vunerability research and exploit development.

 *Some platforms and operating systems supported by GDB:*

 + Linux
 + Embedded Linux 
 + MacOSX 
 + Android
 + iOS
 + [[https://en.wikipedia.org/wiki/Raspberry_Pi][Raspberry PI board]] (Well-known single-board computer powered by ARM
   processor which supports many operating systems, namely, GNU/Linux
   compiled for ARM, Embedded Linux, Windows-CE, BSD, Android and so
   on.)
 + [[https://en.wikipedia.org/wiki/BeagleBoard][Beaglebone black]]  - Single-board computer powered by ARM-based
   processors. It is similar to Raspberry PI, however it has more
   peripherals and the hardware is open source.
 + Atmega AVR microcontrollers 

 *Languages supported by GDB:*

 + *C*
 + *C++*
 + Ada
 + *Fortran*
 + *Objective-C*
 + D (D-Language)
 + Go
 + OpenCL
 + Rust
 + Modula-2
 + Pascal 

 *Other useful tools for debugging / instrospection and reverse engineering:*

 + strace => Trace system calls.
 + ltrace => Trace system calls.

 + lsof => View process' file descriptors, sockets, file mappings and
   so on.

 + lslk => View process' locks.

 + ls -l ~/proc/<pid-of-process/>/fd~
   + Show file descriptors opened by process.

 + _Wireshark and TCPDump_ => Debug and reverse engineer network
   protocols.

 + _netcat_ - Can create socket clients or socket servers on the fly. It
   is useful for testing network servers or clients.

 *Front-ends for GDB (Graphical User Interfaces):*

Graphical user interfaces makes easier to set breakpoints, watch
variables and modify at runtime the execution control flow. However,
not all GDB commands are accessible from the GDB graphical user
interfaces, thus, the command line and terminal interface $ gdb is
more powerful.

 + [[https://github.com/cs01/gdbgui/][GdbGUI]] - Brower GUI user interface - it opens a webpage at
   localhost containing a front-end for GDB.
   + Supports commands: YES
   + Video: [[https://www.youtube.com/watch?v=Cd0BOOdGjrw][gdbgui demonstration - browser based gdb frontend]]

 + [[https://wiki.gnome.org/Apps/Nemiver/Features][Nemiver]]
   + [[https://people.gnome.org/~dodji/vids/variable-tooltip.ogg][Screencast]]
   + Supports commands: NO. 
 + [[https://www.gnu.org/software/ddd/][DDD - Data Display Debugger]]
   + Supports commands: YES.
   + [[https://www.gnu.org/software/ddd/manual/html_mono/ddd.html#Summary][Manual]]
   + Video: [[https://www.youtube.com/watch?v=cKQ1qdo79As][GDNU DDD - Software Debugging]]

 + Eclipse CDT IDE
   + Video: [[https://www.youtube.com/watch?v=KbN1UyybsV4][GDB Remote Debugging using LUbuntu Linux and Eclipse CDT Neon 3]]
   + Video: [[https://www.youtube.com/watch?v=T9yFyWsyyGk][Debian C/C++ Cross-Compilation for Embedded Linux using Eclipse (Luna), CDT, RSE & Remote Debug]]

 + [[https://www.youtube.com/watch?v=wUZyoAnPdCY][JetBrain CLion IDE]]  

 + [[https://www.youtube.com/watch?v=-3toI8L3Oug][Microsft Visual Studio]] - (Visual Stdio Debugger can connect from
   Windows to a GDB server remotely over the network)

 + Emacs
   + Supports commands: YES.
   + Video: [[https://youtu.be/Vn1kDWVxq4s?t=344][AoD_1: Debugging with GDB in Emacs]] 

 + More info, see: [[https://sourceware.org/gdb/wiki/GDB%20Front%20Ends][GDB Front Ends - GDB Wiki]] 

Side notes:
 + Supports commands: Means commands such as ($ b main), ($ i locals)...
 + ?? -> Not known. 

** Command Summary 

Commands: 

| Command                   | Description                                               |   |
|---------------------------+-----------------------------------------------------------+---|
| help or h                 | Show help                                                 |   |
| info                      | Show help about all (i) or info commands                  |   |
|                           |                                                           |   |
| *Debug Program or Process*  |                                                           |   |
| file [path/to/program]    | Load  some program/executable file (ELF format on U*nix). |   |
| start                     | Start debugging a loaded program                          |   |
| attach [PID]              | Attach debugger to a running process.                     |   |
| detach                    | Detach debugger from process.                             |   |
| r or run                  | Run the loaded program                                    |   |
| r [ARG0] [ARG1]  ...      | Run program with arguments ARG0, ARG1 ...                 |   |
| r > logging.fil           | Run program redirecting output to file.                   |   |
| tty /dev/pts/4            | Redirect program input and ouput to another terminal      |   |
| q or quit                 | Quit GNU debugger.                                        |   |
| kill                      | Kill the process being debugged                           |   |
|                           |                                                           |   |
| *Break Points*              |                                                           |   |
| i b or i breakpoints      | Show brakpoints                                           |   |
| break main                | Set break point at main function                          |   |
| break [FUNCTION]          | Set break point at some function                          |   |
| break [OBJECT.method]     | Set break point at some class method.                     |   |
| break [LINE ]             | Set break point at some line.                             |   |
| break [FILE]:[LINE]       | Set break point at some line of a given file.             |   |
| watch n == 10             | Set watchpoint, that pauses program when n == 10 is true. |   |
| sycall catch fork         | Stop execution whenever this syscall, fork, is invoked.   |   |
| syscall catch read        | Set break point at read system call.                      |   |
|                           |                                                           |   |
| *Setepping through*         |                                                           |   |
| s or step                 | Execute next line, stepping over any function calls.      |   |
| n or next                 | Execute next line, stepping into function calls.          |   |
| c, cont or continue       | Resume execution until next break point                   |   |
| pop [RETURN VALUE]        | Pop current stack frame, returning from current function. |   |
| finish                    | Run until the current function returns                    |   |
| jump [LINE]  or *address  | Resume execution at different address                     |   |
| lines                     | Show lines of srouce around current line                  |   |
| where                     | Show current location                                     |   |
| bt or backtrace           | Show backtrace                                            |   |
|                           |                                                           |   |
| *Variables*                 |                                                           |   |
| i locals                  | Show local variables                                      |   |
| i args                    | Show arguments of current function                        |   |
| p [VAR] or print [VAR]    | Print some variable                                       |   |
| display [VAR]             | Add variable to display list                              |   |
| watch [VAR]               | Watch variable                                            |   |
| set [VAR] = [VALUE]       | Set variable with some value                              |   |
| i registers               | Show CPU registers                                        |   |
| p $pc                     | Show program counter CPU Register                         |   |
| p $sp                     | Show stack pointer                                        |   |
| p $fp                     | Show frame pointer                                        |   |
|                           |                                                           |   |
| *Process Information*       |                                                           |   |
| i proc                    | Display basic information about current process.          |   |
| i proc status             | Show process status                                       |   |
| i proc all                | Show all information about current process                |   |
| i inferior                | Show path to executable and PID of debugged process.      |   |
|                           |                                                           |   |
| pwd                       | Current process working directory                         |   |
| cd [DIRECTORY]            | Change process working directory.                         |   |
| show args                 | Show arguments used to invoke the program being debugged. |   |
| show environment          | Show environment variables of the process being debugged. |   |
| show paths                | Show PATH variable or serach paths.                       |   |
|                           |                                                           |   |
| *Misc*                      |                                                           |   |
| i threads                 | Show threads information                                  |   |
| i functions               | Show all functions and symbols in the program             |   |
| set print pretty on       | Turn on pretty print                                      |   |
| call Function()           | Call some function and print returned value.              |   |
| layout asm                | Show a window within current terminal with assembly code. |   |
| laytout src               | Show a window within current terminal with source code.   |   |
|                           |                                                           |   |
| *Backtrace*                 | Debug exceptions and signals such as segmentation fault.  |   |
| backtrace or bt           | Show backtrace.                                           |   |
| backtrace full or bt full | Show full backtrace                                       |   |
|                           |                                                           |   |

Key Bindings for Terminal:

| Key Bindign  | Description                                                                        |
|--------------+------------------------------------------------------------------------------------|
| Crtl + z     | Suspend GDB process, type fg to resume                                             |
| Crtl + c     | Terminate debugged process                                                         |
| Ctrl + l     | Clear screen                                                                       |
| Ctrl + x + a | Open a window in the terminal which shows the source code around the current line. |
|              |                                                                                    |
| *Line Editor*  | Note: The liner editor is based on Emacs and Lib. GNUReadline                      |
| Ctrl + a     | Move cursor to beggining of line                                                   |
| Ctrl + e     | Move cursor to end of line                                                         |
| Ctrl + d     | Send EOF (End of File char) 0x4 - means end of input                               |
| Ctrl + p     | Previous command from history                                                      |
| Ctrl + n     | Next command from history                                                          |
| Ctrl + k     | Delete characters from current cursor location to end of line.                     |
| Ctrl + u     | Delete characters from current cursor location to beggining of line.               |
| Ctrl + x + 2 | Switch to other window.                                                            |
|              |                                                                                    |
|              |                                                                                    |


Note: To run the process input/output in another terminal use:

 + Step 1: Open another terminal for displaying debugged program's
   output and get its name with command $ tty.

#+BEGIN_SRC sh 
  $ tty
  /dev/pts/3
#+END_SRC

 + Step 2: Open GDB use the following command to redirect the
   program's stdout, stderr and stdin output to the terminal
   /dev/pts/3 

#+BEGIN_SRC sh 
  >>> file program.bin 
  >>> tty /dev/pts/3
  >>> start 
  >>> b main 
  >>> b 198
  >>> c # Continue until next break point. 
  >>> c  
#+END_SRC

** Example and work flow 

Compile program with Debug Symbols:

Note: To use the debugger, it is necessary to compile the program with
appropriate compiler option to build with _debug symbols_. In GCC and
Clang, this flag is (-g).

#+BEGIN_SRC sh 
 $ clang++ line-editor.cpp -o line-editor.bin -g -std=c++1z -Wall -Wextra 
#+END_SRC

 *Open GDB:*

Run GDB shell. 

#+BEGIN_SRC sh 
  $ gdb 
#+END_SRC

Run GDB attached it to an executable: 

#+BEGIN_SRC sh 
 $ gdb PROGRAM.BIN 
#+END_SRC

Run GDB attaching it to a running process: 

#+BEGIN_SRC sh 
 # 7081 is the process ID (PID) of the program to be debugged.
 $ gdp -pid 7081
#+END_SRC


 *Show help*

 + >>> help
 + >>> h 

#+BEGIN_SRC sh 
  >>> h
  List of classes of commands:

  aliases -- Aliases of other commands
  breakpoints -- Making program stop at certain points
  data -- Examining data
  files -- Specifying and examining files
  internals -- Maintenance commands
  obscure -- Obscure features
  running -- Running the program
  stack -- Examining the stack
  status -- Status inquiries
  support -- Support facilities
  tracepoints -- Tracing of program execution without stopping the program
  user-defined -- User-defined commands

  Type "help" followed by a class name for a list of commands in that class.
  Type "help all" for the list of all commands.
  Type "help" followed by command name for full documentation.
  Type "apropos word" to search for commands related to "word".
  Command name abbreviations are allowed if unambiguous.
  >>> 
#+END_SRC

 *Load an executable inside GDB shell*

#+BEGIN_SRC sh 
 >>> file program.bin 
#+END_SRC

 *Attach to running process*

Attach GDB to a running process (inside GDB shell): 

 + attach <PID>

#+BEGIN_SRC sh 
  >>> attach 18071
#+END_SRC
 
 *Detach GDB from current process* 

#+BEGIN_SRC sh 
  >>> detach 
#+END_SRC

 *Show path to executable and PID of debugged process*

#+BEGIN_SRC sh 
  >>> i inferior
    Num  Description       Executable        
  * 1    process 7343      /home/archbox/root-scripts/line-editor.bin 
#+END_SRC

 *Show current location*
 
Command _where_ - show the current location: 

#+BEGIN_SRC sh 
  >>> where
  #0  0x00007f701345de21 in read () from /lib64/libc.so.6
  #1  0x00007f70133ef6e0 in __GI__IO_file_underflow () from /lib64/libc.so.6
  #2  0x00007f70133f07e2 in __GI__IO_default_uflow () from /lib64/libc.so.6
  #3  0x00007f7013dceb11 in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::uflow() () from /lib64/libstdc++.so.6
  #4  0x00007f7013ddd61e in std::istream::get() () from /lib64/libstdc++.so.6
  #5  0x000000000040257d in main () at line-editor.cpp:182
  >>> 
#+END_SRC

 *Set break points:*

 + break <LINE>
 + break <FILE>:<LINE> 

#+BEGIN_SRC sh 
  >>> break 200 

  >>> break line-editor.cpp:183
  Breakpoint 3 at 0x402593: file line-editor.cpp, line 183.

  >>> break line-editor.cpp:249
  Breakpoint 1 at 0x402b92: file line-editor.cpp, line 249.
  >>> 
#+END_SRC

 *Show breakpoints:*

#+BEGIN_SRC sh 
  >>> info breakpoints
  No breakpoints or watchpoints.

  >>> info breakpoints
  Num     Type           Disp Enb Address            What
  1       breakpoint     keep y   0x0000000000402b92 in main() at line-editor.cpp:249
  2       breakpoint     keep y   0x0000000000402b92 in main() at line-editor.cpp:249
  >>> 
#+END_SRC

Continue until the program execution until the next breakpoint: 

  + cont
  + continue 

#+BEGIN_SRC sh 
 >>> continue 
 >>> cont 
#+END_SRC

 *Inspect Stack Variables*

At some breakpoint, it is possible to inspect local variables with the
command print:

#+BEGIN_SRC sh 
  >>> print key
  $5 = 104 'h'

  >>> print line_buffer
  $6 = ""

  >>> print linePos
  $7 = 0
  >>> 

  >>> p line_buffer.size()
  $7 = 12
  >>> 
#+END_SRC

Print variable in binary format: 

#+BEGIN_SRC sh 
  >>> print /t linePos
  $1 = 1000

  >>> print /t line_buffer
  $2 = "adsadsad"
  >>> 
#+END_SRC

 *Print Variable Types* 

#+BEGIN_SRC sh 
  >>> ptype line_buffer
  type = std::string

  >>> ptype linePos
  type = unsigned long
  >>> 
#+END_SRC

 *Add variable to display list*

 + Once variables are added to display list, they will be
   automatically printed on every new break point.

#+BEGIN_SRC sh 
  >>> display linePos
  1: linePos = 9
  >>> display line_buffer
  2: line_buffer = "safdsfdsf"
  >>> 

  # Continue execution until next break point 
  # the following variables are automatically displayed.
  >> cont 
  Breakpoint 2, main () at line-editor.cpp:232
  232				if(logging)
  1: linePos = 3
  2: line_buffer = "asd"
  >>> 
#+END_SRC

 *Watch variables* 

 + The debugger will stop the program execution whenever the watched
   variable is changed. Then the user has to type _continue_ to run the
   debugged program until the next change happens. 

#+BEGIN_SRC sh 
  >>> watch linePos 

  >>> continue 
 
  Hardware watchpoint 2: linePos

  Old value = 7
  New value = 8
  main () at line-editor.cpp:196
  196				line_buffer.push_back(key);
  >>> 

  >>> continue 

  Hardware watchpoint 2: linePos

  Old value = 11
  New value = 12
  main () at line-editor.cpp:196
  196				line_buffer.push_back(key);
  >>> 
#+END_SRC

 *Print individual CPU registers*

#+BEGIN_SRC sh 
  >>> print $eax
  $1 = -512

  >>> print $rcx
  $2 = 139647707258401

  >>> print $rax
  $3 = -512
#+END_SRC

 *Print registers:*

 + $ info rgisters 

#+BEGIN_SRC sh 
     >>> info registers
     rax            0xfffffffffffffe00	-512
     rbx            0x7f0244290a00	139647710202368
     rcx            0x7f0243fc1e21	139647707258401
     rdx            0x400	1024
     rsi            0xb035a0	11548064
     rdi            0x0	0
     rbp            0xd68	0xd68
     rsp            0x7ffdb09942d8	0x7ffdb09942d8
     .... .... .... ... ... ... ... 
#+END_SRC

 *Show backtrace* 

 + backtrace 

#+BEGIN_SRC sh 
  >>> bt
  #0  0x00007fc0d7d4beab in raise () from /lib64/libc.so.6
  #1  0x00007fc0d7d365b9 in abort () from /lib64/libc.so.6
  #2  0x00007fc0d870ca9b in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /lib64/libstdc++.so.6
  #3  0x00007fc0d8712efc in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
  #4  0x00007fc0d8712f57 in std::terminate() () from /lib64/libstdc++.so.6
  #5  0x00007fc0d87131b8 in __cxa_throw () from /lib64/libstdc++.so.6
  #6  0x0000000000403061 in main () at line-editor.cpp:253
  >>> 
#+END_SRC

 *Show current working directory of debugged program* 

#+BEGIN_SRC sh 
  >>> pwd
  Working directory /home/archbox/root-scripts.

 # Change current directory: 
  >>> cd /
  Working directory /.

  >>> pwd
  Working directory /.
  >>> 
#+END_SRC

 *Show arguments used to invoke the program* 

#+BEGIN_SRC sh 
  >>> show args
  Argument list to give program being debugged when it is started is "".
#+END_SRC

 *Show environment variables of the debugged program* 

#+BEGIN_SRC sh 
  >>> show environment
  LC_ALL=en_US.UTF-8
  LD_LIBRARY_PATH=:/home/archbox/opt/root/lib:/home/archbox/opt/cling_2018-09-16_fedora27/lib/:/home/archbox/opt/root/lib:/home/archbox/opt/cling_2018-09-16_fedora27/lib/
  XDG_CONFIG_HOME=/home/archbox/.config
  TERMINATOR_UUID=urn:uuid:16c59236-2dde-4517-9fec-c472df54476d
  XDG_MENU_PREFIX=lxqt-
  LXQT_SESSION_CONFIG=session
  MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
  LANG=en_CA.UTF-8
  ... ... ... ..
#+END_SRC


 *Show search paths / path variable for current process*

#+BEGIN_SRC sh 
  >>> show paths
  Executable and object file path: /usr/share/Modules/bin:...
#+END_SRC

 *Current Stack frame* 

Show current function. 

 + $ frame or $ f
   

#+BEGIN_SRC sh 
   >>> f
   #0  main () at line-editor.cpp:232
   232				if(logging)
   >>> 
#+END_SRC

Show arguments of current function:
 
 + $ info args
 + $ i args 

#+BEGIN_SRC sh 
  >>> i args
  No arguments.
  >>> 
#+END_SRC
 
Show local variables: 

 + $ info locals 
 + $ i locals

#+BEGIN_SRC sh 
  >>> i locals
  term = {
    m_tty_back = {
      c_iflag = 17664, 
      c_oflag = 5, 
      c_cflag = 191, 
      c_lflag = 35387, 
      c_line = 0 '\000', 
      c_cc = "\003\034\177\025\004\000\001\000\021\023\032\000\022\017\027\026", '\000' <repeats 15 times>, 
      c_ispeed = 15, 
      c_ospeed = 15
    }, 
    m_fd = 1
  }
  key = 10 '\n'
  lineSize = 0
  linePos = 8
  logging = true
  fd = <incomplete type>
  line_buffer = "adsadsad"
  >>> 

#+END_SRC

 *Call a function in the program*

#+BEGIN_SRC sh 
  >>> call nextChar()
  $1 = 115 's'

  >>> call printHello()
  $2 = 100
  >>> 
#+END_SRC

 *Disassembly some function*

#+BEGIN_SRC sh 
  >>> disas printHello
  Dump of assembler code for function printHello():
     0x0000000000402800 <+0>:	push   %rbp
     0x0000000000402801 <+1>:	mov    %rsp,%rbp
     0x0000000000402804 <+4>:	sub    $0x10,%rsp
     0x0000000000402808 <+8>:	movabs $0x6071a0,%rdi
     0x0000000000402812 <+18>:	movabs $0x405300,%rsi
     0x000000000040281c <+28>:	callq  0x4024c0 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
     0x0000000000402821 <+33>:	movabs $0x402420,%rsi
     0x000000000040282b <+43>:	mov    %rax,%rdi
     0x000000000040282e <+46>:	callq  0x4024f0 <_ZNSolsEPFRSoS_E@plt>
     0x0000000000402833 <+51>:	mov    $0x64,%ecx
     0x0000000000402838 <+56>:	mov    %rax,-0x8(%rbp)
     0x000000000040283c <+60>:	mov    %ecx,%eax
     0x000000000040283e <+62>:	add    $0x10,%rsp
     0x0000000000402842 <+66>:	pop    %rbp
     0x0000000000402843 <+67>:	retq   
  End of assembler dump.
  >>> 

#+END_SRC

 *Show all functions in the program*

#+BEGIN_SRC sh 
  >>> info functions 

  0x00007f173c67bd80  memcpy
  0x00007f173c67bd80  memmove
  0x00007f173c67bf60  memset
  0x00007f173c67c040  __GI___setitimer
  0x00007f173c67c040  __GI_setitimer
  0x00007f173c67c040  __setitimer
  0x00007f173c67c040  setitimer
  0x00007f173c67c060  _etext
  0x00007ffc86bbf9f0  __vdso_clock_gettime
  0x00007ffc86bbf9f0  clock_gettime
  0x00007ffc86bbfd20  __vdso_gettimeofday
  0x00007ffc86bbfd20  gettimeofday
  0x00007ffc86bbfed0  __vdso_time
  0x00007ffc86bbfed0  time
  0x00007ffc86bbfee0  __vdso_getcpu
  0x00007ffc86bbfee0  getcpu
  ... ... ... ... ... ... ... ... 
#+END_SRC

 *Show basic information about the process*

#+BEGIN_SRC cpp 
  >>> i proc
  process 18214
  cmdline = './line-editor.bin'
  cwd = '/home/archbox/root-scripts'
  exe = '/home/archbox/root-scripts/line-editor.bin'
  >>> 
#+END_SRC

 *Show process status*

#+BEGIN_SRC sh 
  >>> i proc status

  process 18214
  Name:	line-editor.bin
  Umask:	0002
  State:	t (tracing stop)
  Tgid:	18214
  Ngid:	0
  Pid:	18214
  PPid:	9944
  TracerPid:	13314
  Uid:	1000	1000	1000	1000
  Gid:	1000	1000	1000	1000
  FDSize:	256
  Groups:	10 971 1000 
  NStgid:	18214
  NSpid:	18214
  NSpgid:	18214
  NSsid:	9944
  VmPeak:	   13856 kB
  VmSize:	   13820 kB
  VmLck:	       0 kB
  VmPin:	       0 kB
  VmHWM:	    1844 kB
  VmRSS:	    1844 kB
  RssAnon:	     148 kB
  RssFile:	    1696 kB
  RssShmem:	       0 kB
  VmData:	     224 kB
  VmStk:	     136 kB
  VmExe:	      28 kB
  VmLib:	    5160 kB
  VmPTE:	      72 kB
  VmSwap:	       0 kB
  HugetlbPages:	       0 kB
  CoreDumping:	0
  Threads:	1
  SigQ:	0/62735
  SigPnd:	0000000000000000
  ShdPnd:	0000000000000000
  SigBlk:	0000000000000000
  SigIgn:	0000000000000000
  SigCgt:	0000000000000000
  CapInh:	0000000000000000
  CapPrm:	0000000000000000
  CapEff:	0000000000000000
  CapBnd:	0000003fffffffff
  CapAmb:	0000000000000000
  NoNewPrivs:	0
  Seccomp:	0
  Speculation_Store_Bypass:	thread vulnerable
  Cpus_allowed:	f
  Cpus_allowed_list:	0-3
  Mems_allowed:	00000000,00000000,00000000,00000000,00000000,... ... 
  Mems_allowed_list:	0
  voluntary_ctxt_switches:	2
  nonvoluntary_ctxt_switches:	0
  >>> 

#+END_SRC

 *Show all information about process*

#+BEGIN_SRC cpp 
   xe = '/home/archbox/root-scripts/line-editor.bin'
   >>> i proc all
   process 18214
   cmdline = './line-editor.bin'
   cwd = '/home/archbox/root-scripts'
   exe = '/home/archbox/root-scripts/line-editor.bin'
   Mapped address spaces:

             Start Addr           End Addr       Size     Offset objfile
               0x400000           0x407000     0x7000        0x0 /home/archbox/root-scripts/line-editor.bin
               0x606000           0x607000     0x1000     0x6000 /home/archbox/root-scripts/line-editor.bin
               0x607000           0x608000     0x1000     0x7000 /home/archbox/root-scripts/line-editor.bin
              0x1aff000          0x1b20000    0x21000        0x0 [heap]
              .. ... . ... ... ... ... ... 
         0x7f02752b3000     0x7f02752b4000     0x1000    0x27000 /usr/lib64/ld-2.27.so
         0x7f02752b4000     0x7f02752b5000     0x1000        0x0 
         0x7fffcf5fd000     0x7fffcf61f000    0x22000        0x0 [stack]
         0x7fffcf652000     0x7fffcf655000     0x3000        0x0 [vvar]
         0x7fffcf655000     0x7fffcf657000     0x2000        0x0 [vdso]
     0xffffffffff600000 0xffffffffff601000     0x1000        0x0 [vsyscall]

   Name:	line-editor.bin
   Umask:	0002
   State:	t (tracing stop)
   Tgid:	18214
   Ngid:	0
   Pid:	18214
   PPid:	9944
   TracerPid:	13314
   Uid:	1000	1000	1000	1000
   Gid:	1000	1000	1000	1000
   .. .... ... ... 
   CoreDumping:	0
   Threads:	1
   SigQ:	1/62735
   SigPnd:	0000000000000000
   ShdPnd:	0000000008000000
   SigBlk:	0000000000000000

    ... ... ... ... 

   Process: 18214
   Exec file: line-editor.bin
   State: t
   Parent process: 9944
   Process group: 18214
   Session id: 9944
   TTY: 34819
   TTY owner process group: 18214
   Flags: 0x40404000
   Minor faults (no memory page): 142
   Minor faults, children: 0

    .. ... ... 

   Start of text: 0x400000
   End of text: 0x4065e4
   Start of stack: 0x7fffcf61cb60

#+END_SRC

 *Show memory map of current process* 

#+BEGIN_SRC sh 
   >> info file
   Symbols from "/home/archbox/root-scripts/line-editor.bin".
   Native process:
           Using the running image of attached process 7343.
           While running this, GDB does not access memory from...
   Local exec file:
           `/home/archbox/root-scripts/line-editor.bin', file type elf64-x86-64.
           Entry point: 0x4026e0
           0x0000000000400238 - 0x0000000000400254 is .interp
           0x0000000000400254 - 0x0000000000400274 is .note.ABI-tag
           0x0000000000400274 - 0x0000000000400298 is .note.gnu.build-id
           0x0000000000400298 - 0x0000000000400444 is .gnu.hash
           0x0000000000400448 - 0x0000000000400d18 is .dynsym
           0x0000000000400d18 - 0x0000000000401d37 is .dynstr
           ... ... ... ... .... ... .. 
#+END_SRC

 *Show memory mappings* 

#+BEGIN_SRC sh 
   >>> i proc m
   process 1446
   Mapped address spaces:

             Start Addr           End Addr       Size     Offset objfile
               0x400000           0x407000     0x7000        0x0 /home/archbox/root-scripts/line-editor.bin
               0x606000           0x607000     0x1000     0x6000 /home/archbox/root-scripts/line-editor.bin
               0x607000           0x608000     0x1000     0x7000 /home/archbox/root-scripts/line-editor.bin
              0x1ce7000          0x1d08000    0x21000        0x0 [heap]
         0x7f84ad30f000     0x7f84ad4c4000   0x1b5000        0x0 /usr/lib64/libc-2.27.so
         0x7f84ad4c4000     0x7f84ad6c4000   0x200000   0x1b5000 /usr/lib64/libc-2.27.so
         0x7f84ad6c4000     0x7f84ad6c8000     0x4000   0x1b5000 /usr/lib64/libc-2.27.so
         0x7f84ad6c8000     0x7f84ad6ca000     0x2000   0x1b9000 /usr/lib64/libc-2.27.so
         0x7f84ad6ca000     0x7f84ad6ce000     0x4000        0x0 
         0x7f84ad6ce000     0x7f84ad6e5000    0x17000        0x0 /usr/lib64/libgcc_s-8-20181105.so.1
         0x7f84ad6e5000     0x7f84ad8e4000   0x1ff000    0x17000 /usr/lib64/libgcc_s-8-20181105.so.1
         0x7f84ad8e4000     0x7f84ad8e5000     0x1000    0x16000 /usr/lib64/libgcc_s-8-20181105.so.1
         0x7f84ad8e5000     0x7f84ad8e6000     0x1000    0x17000 /usr/lib64/libgcc_s-8-20181105.so.1
         0x7f84ad8e6000     0x7f84ada78000   0x192000        0x0 /usr/lib64/libm-2.27.so
    ... .... ... ... ... 
#+END_SRC


 *Detach or exit from debugger:*

#+BEGIN_SRC sh 
  >>> quit
  A debugging session is active.

          Inferior 1 [process 22370] will be detached.
#+END_SRC

** Extensions and scripts 

 + [[http://man7.org/linux/man-pages/man5/gdbinit.5.html][gdbinit]] - GDB Initialization script.

 + https://github.com/gdbinit/gdbinit
   + Gdbinit for OS X, iOS and others - x86, x86_64 and ARM https://reverse.put.as

 + https://github.com/dholm/dotgdb
   + GDB scripts to add support for low level debugging and reverse
     engineering.

 + https://github.com/cyrus-and/gdb-dashboard
   + Modular visual interface for GDB in Python.
   + Desc: "This comes as a standalone single-file .gdbinit which,
     among the other things, enables a configurable dashboard showing
     the most relevant information during the program execution. Its
     main goal is to reduce the number of GDB commands issued to
     inspect the current program status allowing the programmer to
     focus on the control flow instead."

 + https://github.com/eteran/edb-debugger
   + "edb is a cross platform AArch32/x86/x86-64 debugger. It was
     inspired by Ollydbg, but aims to function on AArch32, x86, and
     x86-64 as well as multiple OS's. Linux is the only officially
     supported platform at the moment, but FreeBSD, OpenBSD, OSX and
     Windows ports are underway with varying degrees of
     functionality." 

** References, Bookmarks and Further Reading 
*** Selected GDB Documentation

 + [[https://sourceware.org/gdb/onlinedocs/gdb/Core-File-Generation.html#Core-File-Generation][Debugging with GDB: Core File Generation]]

 + [[https://sourceware.org/gdb/onlinedocs/gdb/Dump_002fRestore-Files.html][Debugging with GDB: Dump/Restore Files]]

 +

 +
*** Bookmarks and further reading

 + [[https://www.recurse.com/blog/5-learning-c-with-gdb][Learning C with gdb - Blog - Recurse Center]]

 + [[http://faculty.kutztown.edu/spiegel/Debugging/DebugPrimer.htm][Simple Use of GDB]] (GDB usage from Emacs)

 + [[http://peeterjoot.com/category/cc-development-and-debugging/][Peeter Joot's Blog » C/C++ development and debugging.]]

 + GDB Manual: https://users.encs.concordia.ca/~adnna_dz/files/gdb.pdf

 + [[https://hgad.net/posts/object-inspection-in-gdb/][Object Inspection in GDB]]

 + [[http://heather.cs.ucdavis.edu/~matloff/UnixAndC/CLanguage/Debug.html][Guide to Faster, Less Frustrating Debugging]]

 + [[https://www.linux.com/blog/tracing-user-space-and-operating-system-interactions][Tracing the User Space and Operating System Interactions | Linux.com | The source for Linux information]]

 + [[https://stackoverflow.com/questions/12773101/gdb-assembly-instruction-calculation][c - GDB: Assembly instruction calculation - Stack Overflow]]

 + [[http://visualgdb.com/gdbreference/commands/x][GDB Command Reference - x command]]

 + [[https://suchakra.wordpress.com/2016/06/29/fast-tracing-with-gdb/][Fast Tracing with GDB – Tuxology]]
*** Videos

 + [[https://www.youtube.com/watch?v=-3toI8L3Oug][Visual Studio GDB Debugger]]

 + [[https://www.youtube.com/watch?v=xQ0ONbt-qPs][Quick Intro to gdb]]

 + [[https://www.youtube.com/watch?v=713ay4bZUrw&feature=youtu.be]['Become a GDB Power User' - Greg Law  ACCU 2016]]
   + "If you’re writing C++ for anything other than Windows, chances
     are that you occasionally break out GDB. This session presents
     some of the lesser known features of GDB that can change the way
     you debug. GDB has come a long way in the last few years and does
     so much more than break, print, step and continue. Reversible
     debugging; Non-Stop Mode; Multi-process Debugging; and Dynamic
     Printf are but some of its best features, and its built-in Python
     scripting is particularly powerful. Join Undo Software co-founder
     and CEO, Greg Law, as he takes you through a series of demos to
     show some amazing tricks with GDB, and powerful new (and
     not-so-new) features that you may not have heard of."

 + [[https://www.youtube.com/watch?v=-n9Fkq1e6sg][CppCon 2016: Greg Law “GDB - A Lot More Than You Knew"]]
   + "If you’re writing C++ for anything other than Windows, chances
     are that you occasionally break out GDB. This session presents
     some of the lesser known features of GDB that can change the way
     you debug. GDB has come a long way in the last few years and now
     does so much more than break, print, step and
     continue. Reversible debugging; Non-Stop Mode; Multi-process
     Debugging; and Dynamic Printf are but some of its best features,
     and its built-in Python scripting is particularly powerful. Join
     Undo co-founder and CEO, Greg Law, as he takes you through a
     series of demos to show some amazing tricks with GDB and some of
     its powerful new (and not-so-new) features that you may not have
     heard of."

 + [[https://www.youtube.com/watch?v=PorfLSr3DDI][CppCon 2015: Greg Law "Give me 15 minutes & I'll change your view of GDB"]]
*** Reverse Engineering

 + [[https://reverseengineering.stackexchange.com/questions/1392/decent-gui-for-gdb][debuggers - Decent GUI for GDB - Reverse Engineering Stack Exchange]]

 + [[http://liveoverflow.com/binary_hacking/reverse_engineering.html][Reverse Engineering - LiveOverflow]]

 + [[https://stackoverflow.com/questions/6473908/can-gdb-change-the-assembly-code-of-a-running-program][linux - Can GDB change the assembly code of a running program? - Stack Overflow]]

 + [[https://bob.cs.sonoma.edu/IntroCompOrg-x64/bookap3.html][C Using the gdb Debugger for Assembly Language]]

*** References

 + https://betterexplained.com/articles/debugging-with-gdb/

 + [[http://www.yolinux.com/TUTORIALS/GDB-Commands.html][Linux Tutorial - GNU GDB Debugger Command Cheat Sheet]] 

 + [[http://cseweb.ucsd.edu/classes/fa09/cse141/tutorial_gcc_gdb.html#gcc_flags][Tutorial of gcc and gdb]]

 + [[http://web.eecs.utk.edu/~bvz/cs140/Notes/Recursion/debug.html][CS140 Lecture notes -- Recursion Debugging Example]]

 + [[https://drive.google.com/viewerng/viewer?url=https://www.cs.tau.ac.il/telux/lecture-notes/GDB_Linux_telux.pptx][Debugging with GDB]]

 + [[https://www.cs.dartmouth.edu/~campbell/cs50/gdb.html][gdb – Debugging buggy code with the GNU debugger]]

 + [[http://www.haifux.org/lectures/211/gdb_-_customize_it.html][gdb - customize it the way <b>you</b> want]]

 + [[https://reverseengineering.stackexchange.com/questions/19598/find-base-address-and-memory-size-of-program-debugged-in-gdb][debugging - Find base address and memory size of program debugged in gdb - Reverse Engineering Stack Exchange]]

 + [[http://www.cse.psu.edu/~deh25/cmpsc311/Lectures/GDB.html][CMPSC 311 - GDB]]

 + http://csapp.cs.cmu.edu/public/docs/gdbnotes-ia32.pdf

 + [[https://cs.baylor.edu/~donahoo/tools/gdb/gdb.html][Debugging with GDB]]

* WindBG - Windows Debugger 
** Overview 

Microsft provides many Windows debuggers other than Visual Studio
Debugger. Despite their difference their engine is the same, is the
_DbgEng_ which is a COM component.

Windows Debuggers: 
 
 + NTSD - Microsft NT Symbolic Debugger
 + CDB  - Microsft Console Debugger 
 + WinDbg - Graphical interface for Windows debug engine DbgEng.
 + KD - Kernel Debugger.

The Windows Debugger - Windbg is an invaluable tool for a wide
variety of tasks such as: 
 
 + Debugging and troubleshooting - processes, applications.
 + Discover Windows Internals
 + Analysis of a process crash dumps or post mortem analysis of a
   processes
 + Reverse engineering
 + Security auditing
 + Development of exploits
 + Check runtime dependencies of a process or dlls used by a process. 

Capabilities:

 + Usermode debugging
 + Kernel mode debugging
 + Remote debugging
 + Post-mortem or debugging of program crash dump, aka core dump.
 + Debugging of 32 bits or 64 bits applications.
 + Attach-to-process deubugging - allows to spy on a process and
   gather information, reverse engineer, check what it is doing ...
 + Scriptable and extensible with many programming languages including
   Python. 

Drawbacks: 

 + Steep learning curve. 
 + Not very documented and sparse documentation.
 + Cryptic commands. 

** Command Summary 

 + http://dblohm7.ca/pmo/windbgcheatsheet.html

 + [[http://kipirvine.com/asm/4th/debug/windbg/index.htm][Using Microsoft Windows Debugger]]

 + [[https://bugslasher.net/2011/01/15/memory-exhaustion-even-if-a-large-enough-free-memory-segment-is-available/][Memory management under Windows : what your mother didn’t tell you | BugSlasher]]

 
| Command                      | Action                                                                           |
|------------------------------+----------------------------------------------------------------------------------|
| version                      | Show debugger version                                                            |
| ?                            | Show basic help                                                                  |
| .cls                         | Clear Screen                                                                     |
| bl                           | Show braking points                                                              |
| bc                           | Clear breaking points                                                            |
| bp kernel32!CreateNamedPipeW | Set break point on a symbol (function CreateNamedpipeW) from kernel32.dll        |
| bp client!main               | Set a break point on main function - note: client.exe is the app being debugged. |
| t                            | Step Into                                                                        |
| p                            | Step Over                                                                        |
| g                            | Continue to the next break point                                                 |
| q                            | Detach debugger and kill process being debugged                                  |
| qd                           | Detach debugger without killing process being debugged                           |
|                              |                                                                                  |
| .tlist                       | Show all processes in the current machine                                        |
| .attach <process-id>         | Attach debugger to some process                                                  |
| .create ~E:\progs\app.exe~     | Create a process                                                                 |
|                              |                                                                                  |
| dv                           | Display Local Variables - Equivalent to window local variables                   |
| ~dt *!*~                        | Display all data structures from all modules (dlls)                              |
| dt ntdll!*                    | Show all data structures available in the module ntdll (ntdll.dll)               |
| ~!peb~                         | Show process' PEB - Process Environment Block                                    |
| lm                           | Show loaded modules (dlls) - shared libraries used by the application.           |
| lmf                          | Show loaded modules with paths (dlls.)                                           |
|                              |                                                                                  |
|                              |                                                                                  |

** Basic Debugger Commands 
*** Show hlep 

 - Command: !help 

#+BEGIN_SRC text 
0:000> !help
address [address]          - Displays the address space layout
        [-UsageType]       - Displays the address space regions of the given type
analyze [-v]               - Analyzes current exception or bugcheck
cpuid [processor]          - Displays CPU version info for all CPUs
elog_str <message>         - Logs simple message to host event log
cppexr <exraddress>        - Displays a C++ EXCEPTION_RECORD
error [errorcode]          - Displays Win32 & NTSTATUS error string
exchain                    - Displays exception chain for current thread
for_each_frame <cmd>       - Executes command for each frame in current
                             thread
for_each_local <cmd> $$<n> - Executes command for each local variable in
                             current frame, substituting fixed-name alias
                             $u<n> for each occurrence of $$<n>
gle [-all]                 - Displays last error & status for current thread
imggp <imagebase>          - Displays GP directory entry for 64-bit image
imgreloc <imagebase>       - Relocates modules for an image
list [-? | parameters]     - Displays lists
obja <address>             - Displays OBJECT_ATTRIBUTES[32|64]
owner [symbol!module]      - Detects owner for current exception or
                             bugcheck from triage.ini
rtlavl <address>           - Displays RTL_AVL_TABLE
std_map <address>          - Displays a std::map<>
str <address>              - Displays ANSI_STRING or OEM_STRING
ustr <address>             - Displays UNICODE_STRING


#+END_SRC

*** Clear screen 

 - Command: _.cls_

#+BEGIN_SRC text 
0:000> .cls
#+END_SRC
*** Display version 
 
 - Command: version 

#+BEGIN_SRC sh 
0:000> version

Windows 10 Version 17134 UP Free x64
Product: WinNt, suite: SingleUserTS
17134.1.amd64fre.rs4_release.180410-1804
Machine Name:
Debug session time: Sun Aug 26 16:54:20.077 2018 (UTC - 7:00)
System Uptime: 10 days 4:18:43.003
Process Uptime: 0 days 1:21:04.373
  Kernel time: 0 days 0:00:00.000
  User time: 0 days 0:00:00.046
Live user mode: <Local>

Microsoft (R) Windows Debugger Version 10.0.17134.12 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

 ...  ...  ...  ...  ...  ...  ...  ...  ...  ... 
#+END_SRC

*** Display source search path 

 - Command: .srcpath 

#+BEGIN_SRC text 
  0:000> .srcpath
  Source search path is: C:\Users\archbox\Desktop\wincpp\com-ole\comtest

  ************* Path validation summary **************
  Response                         Time (ms)     Location
  OK                                             C:\Users\archbox\Desktop\wincpp\com-ole\comtest

#+END_SRC

*** Display loaded modules

 - Command: _lm_

Note: The modules are dlls loaded in the process' addresss space, such
as ntdll.dll, service.dll and etc.

#+BEGIN_SRC text 
>> lm
  start             end                 module name
  00007ff6`69b50000 00007ff6`69c59000   client     (deferred)             
  00007ff8`3dfc0000 00007ff8`3e005000   service    (deferred)             
  00007ff8`4ec10000 00007ff8`4eca8000   uxtheme    (deferred)             
  00007ff8`50740000 00007ff8`50751000   kernel_appcore   (deferred)             
  00007ff8`507d0000 00007ff8`50a43000   KERNELBASE   (deferred)             
  00007ff8`512c0000 00007ff8`51452000   gdi32full   (deferred)             
  00007ff8`51460000 00007ff8`514da000   bcryptPrimitives   (deferred)             
  00007ff8`514e0000 00007ff8`5157f000   msvcp_win   (deferred)             
  00007ff8`51580000 00007ff8`515a0000   win32u     (deferred)             
  00007ff8`51790000 00007ff8`5188a000   ucrtbase   (deferred)             
  00007ff8`518f0000 00007ff8`51918000   GDI32      (deferred)             
  00007ff8`51920000 00007ff8`51a71000   ole32      (deferred)             
  00007ff8`51e80000 00007ff8`51fa4000   RPCRT4     (deferred)             
  00007ff8`51fb0000 00007ff8`52140000   USER32     (deferred)             
  00007ff8`52140000 00007ff8`5219b000   sechost    (deferred)             
  00007ff8`521a0000 00007ff8`5223e000   msvcrt     (deferred)             
  00007ff8`52240000 00007ff8`52563000   combase    (private pdb symbols)  C:\ProgramData\dbg\sym\combase.pdb\8BD819B4B577CBB5053ADA5ED7AA29E91\combase.pdb
  00007ff8`53a80000 00007ff8`53aad000   IMM32      (deferred)             
  00007ff8`54080000 00007ff8`54120000   clbcatq    (deferred)             
  00007ff8`54120000 00007ff8`541d2000   KERNEL32   (deferred)             
  00007ff8`54400000 00007ff8`545e1000   ntdll      (pdb symbols)          C:\ProgramData\dbg\sym\ntdll.pdb\EA3C05F9EA540B02C1971816AF7CC8D21\ntdll.pdb

#+END_SRC
*** Display loaded modules with file name 

 - Command: _lmf_

#+BEGIN_SRC text 
   0:000> lmf

   start             end                 module name
   00007ff6`69b50000 00007ff6`69c59000   client   client.exe  
   00007ff8`3dfc0000 00007ff8`3e005000   service  C:\Users\archbox\Desktop\wincpp\com-ole\comtest\service.dll
   00007ff8`4ec10000 00007ff8`4eca8000   uxtheme  C:\WINDOWS\system32\uxtheme.dll
   00007ff8`50740000 00007ff8`50751000   kernel_appcore C:\WINDOWS\System32\kernel.appcore.dll
   00007ff8`507d0000 00007ff8`50a43000   KERNELBASE C:\WINDOWS\System32\KERNELBASE.dll
   00007ff8`512c0000 00007ff8`51452000   gdi32full C:\WINDOWS\System32\gdi32full.dll
   00007ff8`51460000 00007ff8`514da000   bcryptPrimitives C:\WINDOWS\System32\bcryptPrimitives.dll
   00007ff8`514e0000 00007ff8`5157f000   msvcp_win C:\WINDOWS\System32\msvcp_win.dll
   00007ff8`51580000 00007ff8`515a0000   win32u   C:\WINDOWS\System32\win32u.dll
   00007ff8`51790000 00007ff8`5188a000   ucrtbase C:\WINDOWS\System32\ucrtbase.dll
   00007ff8`518f0000 00007ff8`51918000   GDI32    C:\WINDOWS\System32\GDI32.dll
   00007ff8`51920000 00007ff8`51a71000   ole32    C:\WINDOWS\System32\ole32.dll
   00007ff8`51e80000 00007ff8`51fa4000   RPCRT4   C:\WINDOWS\System32\RPCRT4.dll
   00007ff8`51fb0000 00007ff8`52140000   USER32   C:\WINDOWS\System32\USER32.dll
   00007ff8`52140000 00007ff8`5219b000   sechost  C:\WINDOWS\System32\sechost.dll
   00007ff8`521a0000 00007ff8`5223e000   msvcrt   C:\WINDOWS\System32\msvcrt.dll
   00007ff8`52240000 00007ff8`52563000   combase  C:\WINDOWS\System32\combase.dll
   00007ff8`53a80000 00007ff8`53aad000   IMM32    C:\WINDOWS\System32\IMM32.DLL
   00007ff8`54080000 00007ff8`54120000   clbcatq  C:\WINDOWS\System32\clbcatq.dll
   00007ff8`54120000 00007ff8`541d2000   KERNEL32 C:\WINDOWS\System32\KERNEL32.DLL
   00007ff8`54400000 00007ff8`545e1000   ntdll    ntdll.dll   

#+END_SRC
*** Show verbose information about module 

 - It shows verbose information about a given module including image,
   symbol, path to file and etc. 

 - Command: _lm vm <module>_

Examples:
 + lm vm kernel32  (Information about kernel32.dll)
 + lm vm service   (Information about service.dll)

Show information about module ntdll.dll 

#+BEGIN_SRC text 
  0:000> lm vm ntdll

  Browse full module list
  start             end                 module name
  00007ff8`54400000 00007ff8`545e1000   ntdll      (pdb symbols)          C:\ProgramData\dbg\sym\ntdll.pdb\EA3C05F9EA540B02C1971816AF7CC8D21\ntdll.pdb
      Loaded symbol image file: C:\WINDOWS\SYSTEM32\ntdll.dll
      Image path: ntdll.dll
      Image name: ntdll.dll
      Browse all global symbols  functions  data
      Image was built with /Brepro flag.
      Timestamp:        6D15B6D7 (This is a reproducible build file hash, not a timestamp)
      CheckSum:         001EA411
      ImageSize:        001E1000
      File version:     10.0.17134.228
      Product version:  10.0.17134.228
      File flags:       0 (Mask 3F)
      File OS:          40004 NT Win32
      File type:        2.0 Dll
      File date:        00000000.00000000
      Translations:     0409.04b0
      Information from resource tables:
          CompanyName:      Microsoft Corporation
          ProductName:      Microsoft® Windows® Operating System
          InternalName:     ntdll.dll
          OriginalFilename: ntdll.dll
          ProductVersion:   10.0.17134.228
          FileVersion:      10.0.17134.228 (WinBuild.160101.0800)
          FileDescription:  NT Layer DLL
          LegalCopyright:   © Microsoft Corporation. All rights reserved.
#+END_SRC

 Show information about module service.dll 

#+BEGIN_SRC text 
  0:000> lm vm service
  Browse full module list
  start             end                 module name
  00007ff8`3dfc0000 00007ff8`3e005000   service    (deferred)             
      Image path: C:\Users\archbox\Desktop\wincpp\com-ole\comtest\service.dll
      Image name: service.dll
      Browse all global symbols  functions  data
      Timestamp:        Thu Aug 23 10:44:03 2018 (5B7EF263)
      CheckSum:         00000000
      ImageSize:        00045000
      Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
      Information from resource tables:

#+END_SRC
*** Show module headers 

Show module headers 

 - Command: !dh <module> -f 

#+BEGIN_SRC text 
  :000> !dh out2 -f

  File Type: EXECUTABLE IMAGE
  FILE HEADER VALUES
      8664 machine (X64)
         7 number of sections
  5B89DE49 time date stamp Fri Aug 31 17:33:13 2018

         0 file pointer to symbol table
         0 number of symbols
        F0 size of optional header
        22 characteristics
              Executable
              App can handle >2gb addresses

  OPTIONAL HEADER VALUES
       20B magic #
     14.12 linker version
     CAE00 size of code
     42E00 size of initialized data
         0 size of uninitialized data
      28C4 address of entry point
      1000 base of code
           ----- new -----
  00007ff6c7f40000 image base
      1000 section alignment
       200 file alignment
         3 subsystem (Windows CUI)
      6.00 operating system version
      0.00 image version
      6.00 subsystem version
    112000 size of image
       400 size of headers
         0 checksum
  0000000000100000 size of stack reserve
  0000000000001000 size of stack commit
  0000000000100000 size of heap reserve
  0000000000001000 size of heap commit
      8160  DLL characteristics
              High entropy VA supported
              Dynamic base
              NX compatible
              Terminal server aware
         0 [       0] address [size] of Export Directory
    10D3E8 [      28] address [size] of Import Directory
         0 [       0] address [size] of Resource Directory
    103000 [    8748] address [size] of Exception Directory
         0 [       0] address [size] of Security Directory
    110000 [    11BC] address [size] of Base Relocation Directory
     E6060 [      38] address [size] of Debug Directory
         0 [       0] address [size] of Description Directory
         0 [       0] address [size] of Special Directory
         0 [       0] address [size] of Thread Storage Directory
     E60A0 [     100] address [size] of Load Configuration Directory
         0 [       0] address [size] of Bound Import Directory
    10D000 [     3E8] address [size] of Import Address Table Directory
         0 [       0] address [size] of Delay Import Directory
         0 [       0] address [size] of COR20 Header Directory
         0 [       0] address [size] of Reserved Directory

#+END_SRC

*** Show memory of module 

List modules: 

#+BEGIN_SRC text  
  0:000> lm
  start             end                 module name
  00007ff6`69b50000 00007ff6`69c59000   client   C (private pdb symbols)  C:\ProgramData\dbg\sym\client.pdb\8051143355D841DDB7EE7257B7AE231814\client.pdb
   ... ... ... ... 
  00007ff8`54120000 00007ff8`541d2000   KERNEL32   (pdb symbols)          C:\ProgramData\dbg\sym\kernel32.pdb\63816243EC704DC091BC31470BAC48A31\kernel32.pdb
  00007ff8`54400000 00007ff8`545e1000   ntdll      (pdb symbols)          C:\ProgramData\dbg\sym\ntdll.pdb\EA3C05F9EA540B02C1971816AF7CC8D21\ntdll.pdb

#+END_SRC

Select module ntdll 

 - 00007ff8`54400000
   + Show where in the virtual address space the module is loaded.
 - 00007ff8`545e1000

#+BEGIN_SRC text 
  00007ff8`54400000 00007ff8`545e1000   ntdll      (pdb symbols)          C:\ProgramData\dbg\sym\ntdll.pdb\EA3C05F9EA540B02C1971816AF7CC8D21\ntdll.pdb
#+END_SRC

Diplay bytes of the region: 00007ff8`54400000
 
 - db: d(display) b(bytes)

#+BEGIN_SRC text 
   0:000> db 00007ff8`54400000
   00007ff8`54400000  4d 5a 90 00 03 00 00 00-04 00 00 00 ff ff 00 00  MZ..............
   00007ff8`54400010  b8 00 00 00 00 00 00 00-40 00 00 00 00 00 00 00  ........@.......
   00007ff8`54400020  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
   00007ff8`54400030  00 00 00 00 00 00 00 00-00 00 00 00 e8 00 00 00  ................
   00007ff8`54400040  0e 1f ba 0e 00 b4 09 cd-21 b8 01 4c cd 21 54 68  ......	.!..L.!Th
   00007ff8`54400050  69 73 20 70 72 6f 67 72-61 6d 20 63 61 6e 6e 6f  is program canno
   00007ff8`54400060  74 20 62 65 20 72 75 6e-20 69 6e 20 44 4f 53 20  t be run in DOS 
   00007ff8`54400070  6d 6f 64 65 2e 0d 0d 0a-24 00 00 00 00 00 00 00  mode....$.......
#+END_SRC

Display region as dwords (32 bits values)

#+BEGIN_SRC text 
   0:000> dc 00007ff8`54400000
   00007ff8`54400000  00905a4d 00000003 00000004 0000ffff  MZ..............
   00007ff8`54400010  000000b8 00000000 00000040 00000000  ........@.......
   00007ff8`54400020  00000000 00000000 00000000 00000000  ................
   00007ff8`54400030  00000000 00000000 00000000 000000e8  ................
   00007ff8`54400040  0eba1f0e cd09b400 4c01b821 685421cd  ......	.!..L.!Th
   00007ff8`54400050  70207369 72676f72 63206d61 6f6e6e61  is program canno
   00007ff8`54400060  65622074 6e757220 206e6920 20534f44  t be run in DOS 
   00007ff8`54400070  65646f6d 0a0d0d2e 00000024 00000000  mode....$.......
#+END_SRC

*** Show formatted output about the Process Environment Block (PEB)

Show PEB - Process Environment Block memory location (aka address)

#+BEGIN_SRC text 
   0:000> .process
   Implicit process is now 00000096`d8a7d000
#+END_SRC

Show PEB - Process Environment Block 

 - Command: _!peb_

#+BEGIN_SRC text 
  0:000> !peb
  PEB at 000000a87accf000
      InheritedAddressSpace:    No
      ReadImageFileExecOptions: No
      BeingDebugged:            Yes
      ImageBaseAddress:         00007ff669b50000
      Ldr                       00007ff85455c360
      Ldr.Initialized:          Yes
      Ldr.InInitializationOrderModuleList: 000002986df32e80 . 000002986df523b0
      Ldr.InLoadOrderModuleList:           000002986df33030 . 000002986df52390
      Ldr.InMemoryOrderModuleList:         000002986df33040 . 000002986df523a0
                      Base TimeStamp                     Module
              7ff669b50000 5b7ef429 Aug 23 10:51:37 2018 C:\Users\archbox\Desktop\wincpp\com-ole\comtest\client.exe
              7ff854400000 6d15b6d7 Dec 29 20:06:47 2027 C:\WINDOWS\SYSTEM32\ntdll.dll
              7ff854120000 5f488a51 Aug 27 21:38:41 2020 C:\WINDOWS\System32\KERNEL32.DLL
              7ff8507d0000 b0bb231d Dec 16 10:10:37 2063 C:\WINDOWS\System32\KERNELBASE.dll
              7ff851920000 f6d21073 Mar 22 12:11:47 2101 C:\WINDOWS\System32\ole32.dll
              7ff852240000 fad18dc5 May 07 20:15:17 2103 C:\WINDOWS\System32\combase.dll
              7ff851790000 5db729cd Oct 28 10:47:57 2019 C:\WINDOWS\System32\ucrtbase.dll
              7ff851e80000 a1f1190d Feb 04 15:26:05 2056 C:\WINDOWS\System32\RPCRT4.dll
              7ff851460000 df1abf1c Aug 11 07:13:48 2088 C:\WINDOWS\System32\bcryptPrimitives.dll
              7ff8518f0000 2ad7837c Oct 10 18:29:32 1992 C:\WINDOWS\System32\GDI32.dll
              7ff8512c0000 460017f0 Mar 20 10:20:48 2007 C:\WINDOWS\System32\gdi32full.dll
              7ff8514e0000 b8c3e718 Mar 24 13:27:04 2068 C:\WINDOWS\System32\msvcp_win.dll
              7ff851fb0000 fd9a9c22 Oct 29 17:02:42 2104 C:\WINDOWS\System32\USER32.dll
              7ff851580000 b8eb0e32 Apr 23 06:12:18 2068 C:\WINDOWS\System32\win32u.dll
              7ff852140000 aa4b708f Jul 14 15:45:35 2060 C:\WINDOWS\System32\sechost.dll
              7ff853a80000 7a45968f Jan 02 12:01:19 2035 C:\WINDOWS\System32\IMM32.DLL
              7ff850740000 f0a997a7 Dec 11 16:24:07 2097 C:\WINDOWS\System32\kernel.appcore.dll
              7ff8521a0000 5cbba6fd Apr 20 16:10:53 2019 C:\WINDOWS\System32\msvcrt.dll
              7ff84ec10000 66e92861 Sep 16 23:57:37 2024 C:\WINDOWS\system32\uxtheme.dll
              7ff854080000 9fbc25bf Dec 03 02:49:35 2054 C:\WINDOWS\System32\clbcatq.dll
              7ff83dfc0000 5b7ef263 Aug 23 10:44:03 2018 C:\Users\archbox\Desktop\wincpp\com-ole\comtest\service.dll
      SubSystemData:     0000000000000000
      ProcessHeap:       000002986df30000
      ProcessParameters: 000002986df32520
      CurrentDirectory:  'C:\Program Files (x86)\Windows Kits\10\Debuggers\'
      WindowTitle:  'C:\Users\archbox\Desktop\wincpp\com-ole\comtest\client.exe'
      ImageFile:    'C:\Users\archbox\Desktop\wincpp\com-ole\comtest\client.exe'
      CommandLine:  'C:\Users\archbox\Desktop\wincpp\com-ole\comtest\client.exe'
      DllPath:      '< Name not readable >'
      Environment:  000002986df31100
          =::=::\
          ALLUSERSPROFILE=C:\ProgramData
          APPDATA=C:\Users\archbox\AppData\Roaming
          ChocolateyInstall=C:\ProgramData\chocolatey
          ChocolateyLastPathUpdate=Wed Aug  1 00:29:26 2018
          ChocolateyToolsLocation=C:\tools
          CLASSPATH=.;
          CommonProgramFiles=C:\Program Files\Common Files
          CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
          CommonProgramW6432=C:\Program Files\Common Files
          COMPUTERNAME=DESKTOP-2TJVI2H
          ComSpec=C:\WINDOWS\system32\cmd.exe
          DriverData=C:\Windows\System32\Drivers\DriverData
          FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
          FPS_BROWSER_USER_PROFILE_STRING=Default
          FSHARPINSTALLDIR=C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
          HOME=C:\Users\archbox
          HOMEDRIVE=C:
          HOMEPATH=\Users\archbox
          JAVA_HOME=C:\Program Files\Java\jdk1.8.0_162
          LOCALAPPDATA=C:\Users\archbox\AppData\Local
          LOGONSERVER=\\DESKTOP-2TJVI2H
          NUMBER_OF_PROCESSORS=1
          OneDrive=C:\Users\archbox\OneDrive
          OS=Windows_NT
          Path=C:\Program Files (x86)\Windows Kits\10\Debuggers\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Program Files (x86)\scala\bin;C:\Program Files\Git\cmd;C:\Program Files\LLVM\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\archbox\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Program Files (x86)\scala\bin;C:\Users\archbox\AppData\Local\Microsoft\WindowsApps;;C:\Users\archbox\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder;C:\tools\mingw64\bin;
          PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
          PROCESSOR_ARCHITECTURE=AMD64
          PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
          PROCESSOR_LEVEL=6
          PROCESSOR_REVISION=4e03
          ProgramData=C:\ProgramData
          ProgramFiles=C:\Program Files
          ProgramFiles(x86)=C:\Program Files (x86)
          ProgramW6432=C:\Program Files
          PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
          PUBLIC=C:\Users\Public
          SESSIONNAME=Console
          SRCSRV_SHOW_TF_PROMPT=1
          SRCSRV_TIMEOUT_SECONDS=300
          SystemDrive=C:
          SystemRoot=C:\WINDOWS
          TEMP=C:\Users\archbox\AppData\Local\Temp
          TMP=C:\Users\archbox\AppData\Local\Temp
          USERDOMAIN=DESKTOP-2TJVI2H
          USERDOMAIN_ROAMINGPROFILE=DESKTOP-2TJVI2H
          USERNAME=archbox
          USERPROFILE=C:\Users\archbox
          VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
          WINDBG_DIR=C:\Program Files (x86)\Windows Kits\10\Debuggers\x64
          windir=C:\WINDOWS

#+END_SRC

*** Show variables 

Print local variables. It is equivalent to the window which displays
local variable. 

 - Command: dv

#+BEGIN_SRC text 
   0:000> dv
   00000096`d895f6b0               dwBytesRead = 0x2c8
   00000096`d895f6a8 NtQueryInformationProcess = 0x00007ff8`2dcfa1c0
   00000096`d895f6f0                       peb = struct _PEB
   00000096`d895f690                     hProc = 0xffffffff`ffffffff
   00000096`d895f6b8                       pbi = struct _PROCESS_BASIC_INFORMATION
   00000096`d895f698                   retsize = 0x30
   00000096`d895f6a0                    hNtDLL = 0x00007ff8`2dc60000
   00000096`d895f684                parent_pid = 0x1c84
   00000096`d895f688                    status = 0n0

#+END_SRC

Print all local variables of current stack-frame. 
 
 - Command: dv /t

#+BEGIN_SRC text 
   0:000> dv /t

   00000096`d895f6b0 unsigned int64 dwBytesRead = 0x2c8
   00000096`d895f6a8 <function> * NtQueryInformationProcess = 0x00007ff8`2dcfa1c0
   00000096`d895f6f0 struct _PEB peb = struct _PEB
   00000096`d895f690 void * hProc = 0xffffffff`ffffffff
   00000096`d895f6b8 struct _PROCESS_BASIC_INFORMATION pbi = struct _PROCESS_BASIC_INFORMATION
   00000096`d895f698 unsigned long retsize = 0x30
   00000096`d895f6a0 struct HINSTANCE__ * hNtDLL = 0x00007ff8`2dc60000
   00000096`d895f684 unsigned long parent_pid = 0x1c84
   00000096`d895f688 long status = 0n0
#+END_SRC

*** Show HANDLEs or Kernel objects used by process 

Show all handles used by the process being debugged. 

#+BEGIN_SRC text 
   0:000> !handle
   Handle 4
     Type         	Key
   Handle 8
     Type         	Event
   Handle c
     Type         	WaitCompletionPacket
   Handle 10
     Type         	IoCompletion
   Handle 14
     Type         	TpWorkerFactory
   Handle 18
     Type         	IRTimer
   Handle 1c
     Type         	WaitCompletionPacket
   Handle 20
     Type         	IRTimer
   Handle 24
     ... ... ... ... 
   Type           	Count
   None           	4
   Event          	3
   Section        	5
   File           	6
   Directory      	1
   Key            	2
   Thread         	2
   IoCompletion   	2
   TpWorkerFactory	2
   ALPC Port      	1
   WaitCompletionPacket	5

#+END_SRC

Show detailed information about a given handle. 

#+BEGIN_SRC text 
   0:000> !handle 40 f
   Handle 40
     Type         	File
     Attributes   	0
     GrantedAccess	0x100020:
            Synch
            Execute/Traverse
     HandleCount  	2
     PointerCount 	65536
     No Object Specific Information available

   0:000> !handle 34 f
   Handle 34
     Type         	Directory
     Attributes   	0x10
     GrantedAccess	0x3:
            None
            Query,Traverse
     HandleCount  	117
     PointerCount 	3826979
     Name         	\KnownDlls
     No Object Specific Information available

#+END_SRC

*** Show CPU Registers 

 - Command: _r_

#+BEGIN_SRC text 
   0:000> r

   rax=0000000080004005 rbx=0000000080004005 rcx=0000000000000000
   rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
   rip=00007ff8522faf5a rsp=000000a87ab1e320 rbp=000000a87ab1e420
    r8=000000a87ab1f650  r9=0000000000000000 r10=0000000000000000
   r11=000002986df519bc r12=000000a87ab1f650 r13=0000000000000000
   r14=0000000000000000 r15=0000000000000000
   iopl=0         nv up ei pl nz na po nc
   cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010204
   combase!CServerContextActivator::CreateInstance+0x23a:
   00007ff8`522faf5a 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????
#+END_SRC

*** Show threads 

This commands shows the natives threads in the current process: 

 - Command: (~) tilde. For every thread it is assigned an unique
   Id. (Threads 0, 1, 2, 3 ...)

#+BEGIN_SRC text 
  0:000> ~

  .  0  Id: 2144.f68 Suspend: 1 Teb: 000000a8`7acd0000 Unfrozen
     1  Id: 2144.14c4 Suspend: 1 Teb: 000000a8`7acd4000 Unfrozen
     2  Id: 2144.2310 Suspend: 1 Teb: 000000a8`7acd2000 Unfrozen
#+END_SRC

*** Show stack 

Show stack of current thread (in this case thread of id = 0)
 
 - Command: k 

#+BEGIN_SRC text 
  0:000> k
   # Child-SP          RetAddr           Call Site
  00 0000002f`12f3e090 00007ff8`522c5abf combase!CServerContextActivator::CreateInstance+0x23a [onecore\com\combase\objact\actvator.cxx @ 910] 
  01 0000002f`12f3e210 00007ff8`522d63d1 combase!ActivationPropertiesIn::DelegateCreateInstance+0xef [onecore\com\combase\actprops\actprops.cxx @ 1905] 
  02 0000002f`12f3e2a0 00007ff8`522d5b62 combase!CApartmentActivator::CreateInstance+0xc1 [onecore\com\combase\objact\actvator.cxx @ 2169] 
  03 0000002f`12f3e350 00007ff8`522d5e30 combase!CProcessActivator::CCICallback+0x72 [onecore\com\combase\objact\actvator.cxx @ 1637] 
  04 0000002f`12f3e390 00007ff8`522d5c7e combase!CProcessActivator::AttemptActivation+0x40 [onecore\com\combase\objact\actvator.cxx @ 1524] 
  05 0000002f`12f3e3e0 00007ff8`522d608b combase!CProcessActivator::ActivateByContext+0xae [onecore\com\combase\objact\actvator.cxx @ 1368] 
  06 0000002f`12f3e470 00007ff8`522c5a7d combase!CProcessActivator::CreateInstance+0x8b [onecore\com\combase\objact\actvator.cxx @ 1268] 
  07 0000002f`12f3e4c0 00007ff8`522c334a combase!ActivationPropertiesIn::DelegateCreateInstance+0xad [onecore\com\combase\actprops\actprops.cxx @ 1905] 
  08 0000002f`12f3e550 00007ff8`522c5a87 combase!CClientContextActivator::CreateInstance+0x14a [onecore\com\combase\objact\actvator.cxx @ 567] 
  09 0000002f`12f3e800 00007ff8`52273138 combase!ActivationPropertiesIn::DelegateCreateInstance+0xb7 [onecore\com\combase\actprops\actprops.cxx @ 1957] 
  0a 0000002f`12f3e890 00007ff8`52272589 combase!ICoCreateInstanceEx+0xa38 [onecore\com\combase\objact\objact.cxx @ 1959] 
  0b 0000002f`12f3f710 00007ff8`52272393 combase!CComActivator::DoCreateInstance+0x169 [onecore\com\combase\objact\immact.hxx @ 385] 
  0c (Inline Function) --------`-------- combase!CoCreateInstanceEx+0x88 [onecore\com\combase\objact\actapi.cxx @ 177] 
  0d 0000002f`12f3f830 00007ff6`69b5e220 combase!CoCreateInstance+0xc3 [onecore\com\combase\objact\actapi.cxx @ 121] 
  0e 0000002f`12f3f8d0 00007ff6`69ba0f40 client!main+0x1a0 [c:\users\archbox\desktop\wincpp\com-ole\comtest\client.cpp @ 34] 
  0f (Inline Function) --------`-------- client!invoke_main+0x22 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
  10 0000002f`12f3f980 00007ff8`54133034 client!__scrt_common_main_seh+0x110 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
  11 0000002f`12f3f9c0 00007ff8`54471431 KERNEL32!BaseThreadInitThunk+0x14
  12 0000002f`12f3f9f0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
#+END_SRC

Show stack of thread 0 (id = 0)
 
 - Command: k0 

#+BEGIN_SRC text 
   0:000> k0
    # Child-SP          RetAddr           Call Site
   00 0000002f`12f3e090 00007ff8`522c5abf combase!CServerContextActivator::CreateInstance+0x23a [onecore\com\combase\objact\actvator.cxx @ 910] 
   01 0000002f`12f3e210 00007ff8`522d63d1 combase!ActivationPropertiesIn::DelegateCreateInstance+0xef [onecore\com\combase\actprops\actprops.cxx @ 1905] 
   02 0000002f`12f3e2a0 00007ff8`522d5b62 combase!CApartmentActivator::CreateInstance+0xc1 [onecore\com\combase\objact\actvator.cxx @ 2169] 
   03 0000002f`12f3e350 00007ff8`522d5e30 combase!CProcessActivator::CCICallback+0x72 [onecore\com\combase\objact\actvator.cxx @ 1637] 
   04 0000002f`12f3e390 00007ff8`522d5c7e combase!CProcessActivator::AttemptActivation+0x40 [onecore\com\combase\objact\actvator.cxx @ 1524] 
   05 0000002f`12f3e3e0 00007ff8`522d608b combase!CProcessActivator::ActivateByContext+0xae [onecore\com\combase\objact\actvator.cxx @ 1368] 
   06 0000002f`12f3e470 00007ff8`522c5a7d combase!CProcessActivator::CreateInstance+0x8b [onecore\com\combase\objact\actvator.cxx @ 1268] 
   07 0000002f`12f3e4c0 00007ff8`522c334a combase!ActivationPropertiesIn::DelegateCreateInstance+0xad [onecore\com\combase\actprops\actprops.cxx @ 1905] 
   08 0000002f`12f3e550 00007ff8`522c5a87 combase!CClientContextActivator::CreateInstance+0x14a [onecore\com\combase\objact\actvator.cxx @ 567] 
   09 0000002f`12f3e800 00007ff8`52273138 combase!ActivationPropertiesIn::DelegateCreateInstance+0xb7 [onecore\com\combase\actprops\actprops.cxx @ 1957] 
   0a 0000002f`12f3e890 00007ff8`52272589 combase!ICoCreateInstanceEx+0xa38 [onecore\com\combase\objact\objact.cxx @ 1959] 
   0b 0000002f`12f3f710 00007ff8`52272393 combase!CComActivator::DoCreateInstance+0x169 [onecore\com\combase\objact\immact.hxx @ 385] 
   0c (Inline Function) --------`-------- combase!CoCreateInstanceEx+0x88 [onecore\com\combase\objact\actapi.cxx @ 177] 
   0d 0000002f`12f3f830 00007ff6`69b5e220 combase!CoCreateInstance+0xc3 [onecore\com\combase\objact\actapi.cxx @ 121] 
   0e 0000002f`12f3f8d0 00007ff6`69ba0f40 client!main+0x1a0 [c:\users\archbox\desktop\wincpp\com-ole\comtest\client.cpp @ 34] 
   0f (Inline Function) --------`-------- client!invoke_main+0x22 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
   10 0000002f`12f3f980 00007ff8`54133034 client!__scrt_common_main_seh+0x110 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283] 
   11 0000002f`12f3f9c0 00007ff8`54471431 KERNEL32!BaseThreadInitThunk+0x14
   12 0000002f`12f3f9f0 00000000`00000000 ntdll!RtlUserThreadStart+0x21

#+END_SRC

Show stack of thread 1 (id = 1)

 - Command: k1 

#+BEGIN_SRC text 
  0:000> k1
   # Child-SP          RetAddr           Call Site
  00 0000002f`12f3e090 00007ff8`522c5abf combase!CServerContextActivator::CreateInstance+0x23a [onecore\com\combase\objact\actvator.cxx @ 910] 

#+END_SRC

Show stack of thread N  where N = 0, 1, 2... (id = N)
 
 - Command: k<N>

*** List Processes 

List all processes in the current machine. 

 - Command: .tlist 

#+BEGIN_SRC text 
   :000> .tlist

       0n0 System Process
       0n4 System
      0n68 Registry
     0n336 smss.exe
     0n420 csrss.exe
     0n492 wininit.exe
     0n504 csrss.exe
     0n568 winlogon.exe
      ...  ...  ...  ...  ...  ...  ... 
    0n6504 SearchProtocolHost.exe
    0n3584 SearchFilterHost.exe
#+END_SRC

*** Show all symbols exported by a module 

 - Command: x<module>!*

Examples: 
 - xclient!*
 - xntdll!* 

Show all symbols exported by the module client (client.exe) or application
being debugged. 

#+BEGIN_SRC text 
   >>> xclient!*
   00007ff6`69c22130 client!__newclmap = unsigned char [] "???"
   00007ff6`69c22130 client!__newclmap = unsigned char [384] "???"
   00007ff6`69c23828 client!__exp_bias_m1 = 0x3fe
   00007ff6`69c1f3d8 client!std::money_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t> > >::`vftable' = <function> *[6]
   00007ff6`69c25af8 client!__acrt_signal_action_table_size = 0xc0
   00007ff6`69c237d0 client!__pos_zero = 0
   00007ff6`69c47a38 client!std::_Ptr_wcout = 0x00000000`00000000
   00007ff6`69c450b0 client!_fltused = 0n39029
   00007ff6`69c2d130 client!_LInf_C = union _float_const
   00007ff6`69c2d310 client!__mask_mant = 0x000fffff`ffffffff
   00007ff6`69c4a000 client!enable_percent_n = 0
    , ... ... ... ... ... ... ... 

   00007ff6`69c0b27e client!_abstract_sw =  (inline caller) client!_statusfp+a
   00007ff6`69c0b318 client!_abstract_cw =  (inline caller) client!common_control87+28
   00007ff6`69c0b3f7 client!_hw_cw =  (inline caller) client!common_control87+107
   00007ff6`69c0b4f5 client!_abstract_cw =  (inline caller) client!common_control87+205
#+END_SRC

Show all symbols exported by the module ntdll 

#+BEGIN_SRC text 
   0:000> xntdll!*

   00007ff8`5445c658 ntdll!RtlpHpVaMgrRangeCreate (void)
   00007ff8`5444a7b0 ntdll!RtlFindLastBackwardRunClear (void)
   00007ff8`54443f30 ntdll!EtwDeliverDataBlock (void)
   00007ff8`54481790 ntdll!RtlpInitializeStaticCriticalSection (void)
   00007ff8`5443f260 ntdll!RtlpTpWorkCallback (void)
   00007ff8`544a2608 ntdll!RtlUnicodeStringToOemString$fin$0 (void)
   00007ff8`54402a88 ntdll!TppETWTimerCancelled (void)
   00007ff8`5445e5e0 ntdll!RtlpQueryExtendedInformationHeap (void)
     ... ... .. ... ... .. ... ... .. ... ... .. ... ... 
#+END_SRC

*** Evaluate C++ Expressions 

Reference: 

 + [[https://blogs.msdn.microsoft.com/debuggingtoolbox/2008/03/04/special-command-using-c-and-poi-with-cc-expressions/][Special Command: Using ??, @@c++() and poi() with C/C++ Expressions – Debugging Toolbox]]
 + [[http://apprize.info/programming/reverse/5.html][Debugging and Automation - Practical Reverse Engineering: x86, x64, ARM, Windows Kernel, Reversing Tools, and Obfuscation (2014)]]

Commands: 
 + Set the current expression evaluator to C++
   + >> .expr /s c++
 + Set the current expression evaluator to MASM (Microft Macro Assembler)
   + >> .expr /s masm 

Show available expression evaluators: 

#+BEGIN_SRC text 
0:000> .expr /q

Available expression evaluators:
MASM - Microsoft Assembler expressions
C++ - C++ source expressions

Current expression evaluator: MASM - Microsoft Assembler expressions
Available expression evaluators:
MASM - Microsoft Assembler expressions
C++ - C++ source expressions

Current expression evaluator: MASM - Microsoft Assembler expressions

#+END_SRC

Set C++ as defaul expression evaulator: 

#+BEGIN_SRC text 
0:000> .expr /s c++
Current expression evaluator: C++ - C++ source expressions
Current expression evaluator: C++ - C++ source expressions
#+END_SRC

Evaluate basic C++ expressions: 

#+BEGIN_SRC text 
   0:000> ?? @@c++(sizeof(int))
   unsigned int64 4

   0:000> ?? @@c++(sizeof(double))
   unsigned int64 8

   0:000> ?? @@c++(sizeof(long))
   unsigned int64 4

   0:000> ?? @@c++(sizeof(LPVOID))
   unsigned int64 8

   0:000> ?? @@c++(sizeof(LPSTR))
   unsigned int64 8

#+END_SRC

Explorer process environment block data structure PEB. Note: The PEB
can be seen with the command >> !peb 

#+BEGIN_SRC text 
   0:000> ? @@c++(sizeof(@$peb))
   Evaluate expression: 8 = 00000000`00000008

   0:000> ? @@c++(@$peb->ImageBaseAddress)
   Evaluate expression: 140696312152064 = 00007ff6`69b50000

   0:000> ? @@c++(@$peb->Ldr)
   Evaluate expression: 140704543523680 = 00007ff8`5455c360

   0:000> ? @@c++(@$peb->Ldr->Initialized)
   Evaluate expression: 1 = 00000000`00000001
#+END_SRC

*** Exceptions 

Last event: 

#+BEGIN_SRC text 
   0:000> .lastevent
   Last event: 1bac.1294: Access violation - code c0000005 (!!! second chance !!!)
     debugger time: Sun Aug 26 17:12:56.363 2018 (UTC - 7:00)

#+END_SRC

Display most recent exception:

 - Command: .exr -1 

#+BEGIN_SRC text 
   0:000> .exr -1

   ExceptionAddress: 00007ff8522faf5a (combase!CServerContextActivator::CreateInstance+0x000000000000023a)
      ExceptionCode: c0000005 (Access violation)
     ExceptionFlags: 00000000
   NumberParameters: 2
      Parameter[0]: 0000000000000000
      Parameter[1]: 0000000000000000
   Attempt to read from address 0000000000000000
#+END_SRC

Show detailed information about current exception: 

 - Command: !analyse -v 

#+BEGIN_SRC text 
   0:000> !analyze -v

   *******************************************************************************
   *                                                                             *
   *                        Exception Analysis                                   *
   *                                                                             *
   *******************************************************************************

    ... ... ... ... ... ... ...  ... ... ... ... ... ... ...  ... ... ... ... ...


   PROCESS_NAME:  client.exe

   FOLLOWUP_IP: 
   client!main+1a0 [c:\users\archbox\desktop\wincpp\com-ole\comtest\client.cpp @ 34]
   00007ff6`69b5e220 89442460        mov     dword ptr [rsp+60h],eax

   READ_ADDRESS:  0000000000000000 

   ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

    ... .... ... ... ... ...  ... .... ... ... ... ...  ... .... ... ... ... ... 

   STACK_TEXT:  
   0000002f`12f3e090 00007ff8`522c5abf : 00000000`00000000 0000002f`12f3f3c0 00000000`00000002 00000212`cb651d00 : combase!CServerContextActivator::CreateInstance+0x23a
   0000002f`12f3e210 00007ff8`522d63d1 : 00000212`cb630000 0030002d`40000062 0000002f`12f3f110 00000000`00000000 : combase!ActivationPropertiesIn::DelegateCreateInstance+0xef
   0000002f`12f3e2a0 00007ff8`522d5b62 : 00000000`00000000 00000000`00000000 0000002f`12f3e8e0 00000000`00000000 : combase!CApartmentActivator::CreateInstance+0xc1
   0000002f`12f3e350 00007ff8`522d5e30 : 00007ff8`525144c0 00000000`00000000 0000002f`12f3f3c0 00007ff8`522c4850 : combase!CProcessActivator::CCICallback+0x72
   0000002f`12f3e390 00007ff8`522d5c7e : 0000002f`12f3efe8 00000000`00000000 00000000`00000000 00007ff8`52278cb7 : combase!CProcessActivator::AttemptActivation+0x40
   0000002f`12f3e3e0 00007ff8`522d608b : 00007ff8`525144b0 00000000`524a32c0 00000000`00000000 00000000`00000017 : combase!CProcessActivator::ActivateByContext+0xae

    ... .... ... ... ... ...  ... .... ... ... ... ...  ... .... ... ... ... ...  ... .... ... ... ... ... 


   FAULTING_SOURCE_CODE:  
       30: 
       31:  IService* pComponent = nullptr;
       32: 
       33:  std::cerr << "Creating COM Instance" << std::endl;
   >   34:  hr = CoCreateInstance(
       35:          // REFCLSID or GUID rclsid
       36:          clsid, //IID_IUnknown,
       37:          // LPUNKNOWN pUnkOuter 
       38:          NULL,
       39:          // DWORD dwClsContext


   ... ... 

   FAILURE_ID_HASH_STRING:  um:null_pointer_read_c0000005_client.exe!main

   FAILURE_ID_HASH:  {38138cf1-8f6c-6157-2e18-446b4fc12b02}

   Followup:     MachineOwner
   ---------


#+END_SRC

*** Inspect data structures 

Show PEB - Process Environment Block 
 
 - Command: !peb 

#+BEGIN_SRC text 
   0:000> !peb

   PEB at 000000dc0a234000
       InheritedAddressSpace:    No
       ReadImageFileExecOptions: No
       BeingDebugged:            Yes
       ImageBaseAddress:         00007ff691ee0000
       Ldr                       00007ff82ddbc360
       Ldr.Initialized:          Yes
       Ldr.InInitializationOrderModuleList: 0000026976932eb0 . 00000269769335d0
       Ldr.InLoadOrderModuleList:           0000026976933060 . 0000026976933c60
       Ldr.InMemoryOrderModuleList:         0000026976933070 . 0000026976933c70
                       Base TimeStamp                     Module
               7ff691ee0000 5b89d00b Aug 31 16:32:27 2018 C:\Users\archbox\Desktop\wincpp\out.exe
               7ff82dc60000 6d15b6d7 Dec 29 20:06:47 2027 C:\WINDOWS\SYSTEM32\ntdll.dll
               7ff82b0f0000 5f488a51 Aug 27 21:38:41 2020 C:\WINDOWS\System32\KERNEL32.DLL
               7ff82aae0000 b0bb231d Dec 16 10:10:37 2063 C:\WINDOWS\System32\KERNELBASE.dll
       SubSystemData:     0000000000000000
       ProcessHeap:       0000026976930000
    ... ... ... ....  ... ... ... ....  ... ... ... ....  ... ... ... ....  ... ... ... .... 
#+END_SRC

Show TEB - Thread Environment Block 
 
 - Command: !teb 

#+BEGIN_SRC text 
   0:000> !teb
   TEB at 000000dc0a235000
       ExceptionList:        0000000000000000
       StackBase:            000000dc0a180000
       StackLimit:           000000dc0a17d000
       SubSystemTib:         0000000000000000
       FiberData:            0000000000001e00
       ArbitraryUserPointer: 0000000000000000
       Self:                 000000dc0a235000
       EnvironmentPointer:   0000000000000000
       ClientId:             0000000000001940 . 0000000000000b24
       RpcHandle:            0000000000000000
       Tls Storage:          000000dc0a235058
       PEB Address:          000000dc0a234000
       LastErrorValue:       0
       LastStatusValue:      c00000bb
       Count Owned Locks:    0
       HardErrorMode:        0
   TEB at 000000dc0a235000
       ExceptionList:        0000000000000000
       StackBase:            000000dc0a180000
       StackLimit:           000000dc0a17d000
       SubSystemTib:         0000000000000000
       FiberData:            0000000000001e00
       ArbitraryUserPointer: 0000000000000000
       Self:                 000000dc0a235000
       EnvironmentPointer:   0000000000000000
       ClientId:             0000000000001940 . 0000000000000b24
       RpcHandle:            0000000000000000
       Tls Storage:          000000dc0a235058
       PEB Address:          000000dc0a234000
       LastErrorValue:       0
       LastStatusValue:      c00000bb
       Count Owned Locks:    0
       HardErrorMode:        0
#+END_SRC

Show all data structures exported by ntdll 

 - Command: dt ntdll!*

#+BEGIN_SRC text 
   0:000> dt ntdll!*

             ntdll!LIST_ENTRY64
             ntdll!LIST_ENTRY32
             ntdll!SE_WS_APPX_SIGNATURE_ORIGIN
             ntdll!_PS_MITIGATION_OPTION
             ntdll!_PS_MITIGATION_OPTIONS_MAP
             ntdll!_PS_MITIGATION_AUDIT_OPTIONS_MAP
             ntdll!_KSYSTEM_TIME
             ntdll!_NT_PRODUCT_TYPE
             ntdll!_ALTERNATIVE_ARCHITECTURE_TYPE
             ntdll!_KUSER_SHARED_DATA
             ntdll!<unnamed-tag>
             ntdll!_ULARGE_INTEGER
             ntdll!_TP_POOL
             ntdll!_TP_CLEANUP_GROUP
             ntdll!_ACTIVATION_CONTEXT
             ... ... ... ... ... 
#+END_SRC

Show layout of data structure ~_peb~ - process neviromnet block.

 - Command: ~dt ntdll!_peb~

#+BEGIN_SRC text 
   :000> dt ntdll!_peb

      +0x000 InheritedAddressSpace : UChar
      +0x001 ReadImageFileExecOptions : UChar
      +0x002 BeingDebugged    : UChar
      +0x003 BitField         : UChar
       ... ... ... ... ... 
#+END_SRC

Show content of data structure PEB. 

#+BEGIN_SRC text 
   0:000> dt ntdll!_PEB @$peb

      +0x000 InheritedAddressSpace : 0 ''
      +0x001 ReadImageFileExecOptions : 0 ''
      +0x002 BeingDebugged    : 0x1 ''
      +0x003 BitField         : 0x4 ''
      +0x003 ImageUsesLargePages : 0y0
      +0x003 IsProtectedProcess : 0y0
      +0x003 IsImageDynamicallyRelocated : 0y1
      +0x003 SkipPatchingUser32Forwarders : 0y0
      +0x003 IsPackagedProcess : 0y0
      +0x003 IsAppContainer   : 0y0
      +0x003 IsProtectedProcessLight : 0y0
      +0x003 IsLongPathAwareProcess : 0y0
      +0x004 Padding0         : [4]  ""
      +0x008 Mutant           : 0xffffffff`ffffffff Void
      +0x010 ImageBaseAddress : 0x00007ff6`c7f40000 Void
      +0x018 Ldr              : 0x00007ff8`2ddbc360 _PEB_LDR_DATA
      +0x020 ProcessParameters : 0x000001d7`cc5825c0 _RTL_USER_PROCESS_PARAMETERS
      +0x028 SubSystemData    : (null) 
      +0x030 ProcessHeap      : 0x000001d7`cc580000 Void
      +0x038 FastPebLock      : 0x00007ff8`2ddbbe80 _RTL_CRITICAL_SECTION
      +0x040 AtlThunkSListPtr : (null) 
      +0x048 IFEOKey          : (null) 
      +0x050 CrossProcessFlags : 1
      +0x050 ProcessInJob     : 0y1
      +0x050 ProcessInitializing : 0y0
    .. ... ... .. ... ... .. ... ... .. ... ... 
#+END_SRC


Get process base address. 

#+BEGIN_SRC text 
  start             end                 module name
  start             end                 module name
  00007ff6`91ee0000 00007ff6`91fec000   00007ff6`91ee0000 00007ff6`91fec000   outout      out.exe     
  00007ff8`2aae0000 00007ff8`2ad53000         out.exe     
  00007ff8`2aae0000 00007ff8`2ad53000   KERNELBASEKERNELBASE C:\WINDOWS\System32\KERNELBASE.dll
  00007ff8`2b0f0000 00007ff8`2b1a2000    C:\WINDOWS\System32\KERNELBASE.dll
  00007ff8`2b0f0000 00007ff8`2b1a2000   KERNEL32KERNEL32 C:\WINDOWS\System32\KERNEL32.DLL
  00007ff8`2dc60000 00007ff8`2de41000    C:\WINDOWS\System32\KERNEL32.DLL
  00007ff8`2dc60000 00007ff8`2de41000   ntdllntdll    ntdll.dll   
      ntdll.dll   

#+END_SRC

** References 

 + [[https://www.codeproject.com/Articles/6084/Windows-Debuggers-Part-1-A-WinDbg-Tutorial][Windows Debuggers: Part 1: A WinDbg Tutorial - CodeProject]] 

 + [[https://www.codeproject.com/Articles/22245/Quick-start-to-using-WinDbg][Quick start to using WinDbg - CodeProject]]

 + [[https://www.codeproject.com/Articles/707488/Part-1-Windows-Debugging-Techniques-Debugging-Ap-2][Part 1: Windows Debugging Techniques - Debugging Application Crash (Windbg) - CodeProject]]

 + [[https://briolidz.wordpress.com/2013/11/17/windbg-some-debugging-commands/][WinDbg: Some debugging commands | Kamel Messaoudi]]

 + Robert Kuster. *WinDbg From A to Z* -
   <http://windbg.info/download/doc/pdf/WinDbg_A_to_Z_bw2.pdf> 

 + Arno Hutter. *Windows Debugging with WinDbg* -
   <https://www.slideshare.net/ArnoHuetter/windows-debugging-with-windbg>

 + Revealing Stealth Malware UMD CMSC389M -
   <https://drive.google.com/viewerng/viewer?url=https://www.cs.umd.edu/class/winter2013/cmsc389m/Syllabus_files/StealthMalware_1-10-2013_1.pptx>

 + [[http://kiewic.com/2014-07-26/win32-mutex-handles-and-windbg-handle-extension][Win32 Mutex, HANDLEs and WinDbg !handle extension. - kiewic (formerly Monkey Weekend)]]

 + [[https://blogs.msdn.microsoft.com/debuggingtoolbox/2008/03/04/special-command-using-c-and-poi-with-cc-expressions/][Special Command: Using ??, @@c++() and poi() with C/C++ Expressions – Debugging Toolbox]]

 + [[https://mtaulty.com/2004/08/03/m_4656/][A word for WinDbg – Mike Taulty]]

 + *Chapter 8 - Advanced Native Ciode Techniques with WinDBG* -
   <https://drive.google.com/viewerng/viewer?url=http://ecs.syr.edu/faculty/fawcett/Handouts/TestingSeminar/Chapter8.ppt> 

 + [[https://blogs.msdn.microsoft.com/doronh/2006/03/28/debugger-commands-dps-dpp-that-make-my-life-easier-part-5/][Debugger commands (dps, dpp) that make my life easier (part 5) – A Hole In My Head]]

