#+INCLUDE: theme/style.org
#+TITLE: Shared Libraries - Binary Components
#+DESCRIPTION: cpp c++ code examples, demonstrations, design pattern and integration.
#+STARTUP: content 

 - [[wiki:index][Index]]

* Shared Libraries - Binary Components
** Overview 

Shared libraries are compiled object-code exporting functions, data
structures and classes which can be used by many different
programs. They provide many benefits such as: faster compilation time;
less disk space usage since each program using the library do not
need a copy of the library source code or its compiled-code; ability
to update the library and provide security fixes to client
applications without recompilation, just by replacing the library
file. 

On Windows, shared libraries are called DLLs which stands for Dynamic
Linked Libraries, on Unix-like operating systems such as Linux, BSD
and MacOSX, they are called SO - shared objects or DSO - dynamic
shared objects. 

#+CAPTION: Comparison of shared libraries across different operating systems 
| Operating | Long Name               | Short name | File          | Binary Format                         |
| System    |                         |            | Extension     |                                       |
|-----------+-------------------------+------------+---------------+---------------------------------------|
| Windows   | Dynamic Linked Library  | DLL        | .dll          | PE32/PE64 - Portable Executable       |
| Linux     | (Dynamic) Shared Object | DSO or SO  | .so           | ELF or ELF64 (for 64 bits processors) |
| BSD       | (Dynamic) Shared Object | DSO or SO  | .so           | ELF or ELF64                          |
| MacOSX    | -                       | dylib      | .dylib or .so | MachO                                 |
|-----------+-------------------------+------------+---------------+---------------------------------------|

 + Shared libraries are similar to executables, however they do not
   have the main() function entry point.

In addition to C and C++, shared libraries, containing functions with
C-linkage, can also be used as binary components (libraries) and be
consumed from higher level programming languages such as Python, Ruby,
Java or C# through some foreign-function interface. In Python
C-functions can be imported from shared libraries using the [[https://docs.python.org/3/library/ctypes.html][cytpes]]
library; in C# C-functions can be consumed using the P-invoke API and
in Java it is possible to use C-functions from shared libraries using
the JNI (Java Native Interface) or JNA, which is easier to use.

Note: 
 + Shared libraries are specific to a particular operating system and
   are not part of C++ standard.

** Example 1 - Shared Library libtest.dll - DLLs on Windows
*** Overview 

 *Source:*

Shared library Source Code

 + File: [[file:src/dlls/example-windows1/testlib.cpp][file:src/dlls/example-windows1/testlib.cpp]]
 + File: [[file:src/dlls/example-windows1/testlib.hpp][file:src/dlls/example-windows1/testlib.hpp]]

Sample Client C++ Program:

 + File: [[file:src/dlls/example-windows1/client1.cpp][file:src/dlls/example-windows1/client1.cpp]]  

GIST - Better for online view: 

 + [[https://gist.github.com/caiorss/2bba4c50866d9467aaa8c7792b337f71][Gisthub]]

 *Compile the DLL libtest.dll and client program with MSVC* 

Shared Library 

#+BEGIN_SRC cpp 
 $ cl.exe testlib.cpp /EHsc /LD /nologo user32.lib
#+END_SRC

C++ Client program (client code)

#+BEGIN_SRC cpp 
 $ cl.exe /EHsc client.cpp /Fe:out.exe testlib.lib && out.exe
#+END_SRC

 *Compile the DLL libtest.dll and client program with Mingw/GCC* 

Shared Library 

#+BEGIN_SRC cpp 
 $ g++ testlib.cpp -o testlib.dll -g -shared -std=c++14 -Wall
#+END_SRC

C++ Client program 

#+BEGIN_SRC cpp 
 $ g++ client.cpp -o client.exe -g -std=c++14 testlib.dll -Wall
#+END_SRC

*** Header macros 

Sources:
 + File: [[file:src/dlls/example-windows1/testlib.cpp][file:src/dlls/example-windows1/testlib.cpp]]
 + File: [[file:src/dlls/example-windows1/testlib.hpp][file:src/dlls/example-windows1/testlib.hpp]]

 *teslib.hpp / Heade File - Macros*

The header files uses the following macros to reduce the boilerplate
necessary to export the library functions and classes. 

 + file: libstes.hpp => Macros for exporting functions and classes. 

#+BEGIN_SRC cpp
  #ifndef _WIN32
    // If not compiled for Windows, remove declspec directive.
    #define __declspec(param)  
  #endif 

  #define EXPORT_CPP 	__declspec(dllexport)
 
  #ifdef __cplusplus
    // Indicat that a given symbol/function has C-linkage and
    // does not have name mangling. 
    #define EXPORT_C extern "C" __declspec(dllexport)
  #else
    // If a C-compiler uses this header, remove 'extern "C"'
    #define EXPORT_C  __declspec(dllexport)
  #endif 
#+END_SRC

*** Namespace Linalg 

 *Functions of Namespace Linalg* 

Namespace containing sample linear algebra functions, the function norm
computes an Euclidean norm of a N-dimension vector, the function
linTransform computes a linear transformation performing the
computation v[i] * a + b for each vector element. 

On Windows, all DLL symbols, such as functions, variables and clases,
are private by default, they are not exported by default as happens in
Unix-like OSes shared libraries. Therefore, in order to a function be
exported in a Windows shared library, it is necessary to use the MSVC or visual C++
compiler extension ~__declspec(dllexport)~ before the function declaration.
 
 + Interface => File: *testlib.hpp*

#+BEGIN_SRC cpp 
  /** The macro __cplusplus is used for allowing this 
   ,* header to be used from 'C'. If a C compiler is used
   ,* all definitions inside this #ifdef are discarded.
   ,*/
  #ifdef __cplusplus
  namespace Linalg {
          EXPORT_CPP double norm(const std::vector<double>& xs);

          EXPORT_CPP std::vector<double> linTransform(
                  double a,
                  double b,
                  std::vector<double>& xs
                  );

          EXPORT_CPP
          std::ostream&
          printVector(std::ostream& os, std::vector<double>& xs);	
  }
  #endif 
#+END_SRC

The macro ~EXPORT_CPP~ expands to: 

#+BEGIN_SRC cpp
  EXPORT_CPP double norm(const std::vector<double>& xs);
  // Macro EXPORT_CPP expansion 
  __declspec(dllexport) double norm(const std::vector<double>& xs);
#+END_SRC

The compiler directives *#ifdef __cplusplus ... #endif* are used for
disabling this code block when the header is used by a C-compiler as
the C-language does not support classes, namespaces and many other C++
features. 

 + Implementation => file: *testlib.cpp*

#+BEGIN_SRC cpp 
   // Linear algebra tools 
   namespace Linalg{
        __declspec(dllexport)
        double norm(const std::vector<double>& xs){
           double sum = 0.0;
           for(const auto& x : xs) sum += x * x;
               return std::sqrt(sum);
        }

         __declspec(dllexport)
        std::vector<double>
        linTransform(double a, double b, std::vector<double>& xs){
            std::vector<double> out(xs.size());
            ... ... .... 
        }

       ... ... 
   }
#+END_SRC

*** C-interface of Namespace Linalg 

 *C-interface of Namespace Linalg* 

A C-interface is necessary for ensuring that the DLL can be called
from a C-program or a foreign function interface of a higher level
language. 

 + File: *testlib.hpp* => Function declaration. 

#+BEGIN_SRC cpp 
  // ======= C-interface for Linalg namespace =========//
  /* ----- C-Wrappers for Linalg namespace ---- */

  /** Handle or opaque pointer for std::vector<double> */
  typedef void* hVectorD;

  extern "C"  __declspec(dllexport)
  double testlib_vectorD_Linalg_norm(hVectorD hv);

  extern "C"  __declspec(dllexport)
  void testlib_vectorD_Linalg_printVector(const char* name, hVectorD hv);
#+END_SRC

The *extern "C"* statements are necessary to compile the functions with
_C-linkage_, it means without _name mangling_ (aka name decoration). In
every C program, the function symbols are generally the same as their
names. However, as C++ supports templates and function overloading,
many functions can have the same, with different type signatures,
C++ compiler mangles or decorates function names with a different
schema to make the symbol unique. 

Functions with C-linkage, can only use C-compatible types or PODs
types (Plain Old Data). Therefore, they cannot use STL container,
std::vector, std::string and so on. 

The statement ~__declspec(dllexport)~ is necessary to make annotated
functions' symbols visible. On Unix-like systems and Linux, it is not
necessary as it is MSVC (cl.exe) compiler extension. 


 + File: *testlib.cpp* => C-interface function implementations. 

The type synonym hVectorD is handle or a opaque poiter for the type
std::vector<double>. It is a workaround, to pass std::vector<double>
accross a DLL functions with C-linkage and use std::vector<double>
from C programs or foreign function interfaces. 

#+BEGIN_SRC cpp 
  // Handler for double vector 
  using hVectorD = void*;
  using pVectorD = std::vector<double>*;

  /** C-wrapper for vector<double> constructor */
  extern "C" __declspec(dllexport)
  hVectorD
  testlib_vectorD_make0(size_t n, double x){
     return new std::vector<double>(n, x);
  }
    ... ... ...     ... ... ...     ... ... ... 

  /** C-wrapper for vector<double> destructor */
  extern "C" __declspec(dllexport)
  void
  testlib_vectorD_delete(hVectorD hv){
    delete reinterpret_cast<pVectorD>(hv);
  }

  /** C-wrapepr for Linalg::norm function */
  extern "C" __declspec(dllexport)
  double
  testlib_vectorD_Linalg_norm(hVectorD hv){
     return Linalg::norm(*reinterpret_cast<pVectorD>(hv));
  }
    ... ... ...     ... ... ...     ... ... ... 

#+END_SRC





*** Non-polymorphic Class - SampleClass 

  + File: *testlib.hpp* => Class declaration. 

In order to a class be exported in a Windows' shared library, it
requires the annotation ~__declspec(dllexport)~.

Note: It will not be possible to compiled client program using this
class with a compiler different from the used to build the shared
library libtest.dll. It happens because, the C++ ABI - Application
Binary Interface is not the same accross different compilers. If the
DLL is compiled with MSVC, the only way to use this class from a
program compiled using MingW or even a different version of MSVC is
by using a C-interface (functions with C-linkage) and opaque
pointers (void* pointers). 

#+BEGIN_SRC cpp 
  // ======= Non-polymorphic class exported by DLL =========//
  #ifdef __cplusplus
  // Non-polymorphic class 
  class __declspec(dllexport) SampleClass{
  public:
          SampleClass();
          SampleClass(const std::string& name);	
          ~SampleClass();
          std::string getName() const;
          int get();
          void set(int n);	
  private:
          std::string m_name;
          int m_counter;	
  };
  #endif 
#+END_SRC

 + File: *testlib.cpp* => Class implementation. 

#+BEGIN_SRC cpp 
  SampleClass::SampleClass(const std::string& name)
     : m_name(name), m_counter(0)
  {
      std::cout << " Instance created with name = " << m_name << std::endl;
  }
  /** Delegated constructor on right-hand-side */
  SampleClass::SampleClass(): SampleClass("unnamed"){}   
	
  SampleClass::~SampleClass(){
      std::string text = std::string("SampleClass => name = ") + m_name +  " deleted";
      DbgTrace(text);
  }

  std::string SampleClass::getName() const {
      return m_name;
  }
  int SampleClass::SampleClass::get(){		
      return m_counter;
  }
  void SampleClass::set(int n){
      std::cout << " Counter set to value = " << n << std::endl;
      m_counter = n;
  }	
#+END_SRC

*** C-interface for SampleClass

 + File: *testlib.hpp* => Functions declarations. 

#+BEGIN_SRC cpp 
  /* ----- C-Wrappers for SampleClass namespace ---- */
  using hSampleClass = void*;

  /** Nullable constructor zero-arg constructor */
  extern "C" __declspec(dllexport)
  hSampleClass
  testlib_SampleClass_make0();

  /** Other constructor */
  EXPORT_C hSampleClass testlib_SampleClass_make1(const char* name);

  /** Destructor */
  EXPORT_C
  void
  testlib_SampleClass_delete(hSampleClass hnd);

  /** Wrapper for get method */
  EXPORT_C
  int
  testlib_SampleClass_get(hSampleClass hnd);

  /** Wrapper for set method */
  EXPORT_C
  void
  testlib_SampleClass_set(hSampleClass hnd, int n);

  EXPORT_C
  const char*
  testlib_SampleClass_getName(hSampleClass hnd);

#+END_SRC

 + File: *testlib.cpp* => Functions implementation. 

#+BEGIN_SRC cpp 
  using hSampleClass = void*;

  /** Nullable constructor zero-arg constructor */
  extern "C" __declspec(dllexport)
  hSampleClass
  testlib_SampleClass_make0(){
     return new SampleClass();
  }

  /** Other constructor */
  extern "C" __declspec(dllexport)
  hSampleClass
  testlib_SampleClass_make1(const char* name){
     return new SampleClass(name);
  }

  /** Destructor */
  extern "C" __declspec(dllexport)
  void
  testlib_SampleClass_delete(hSampleClass hnd){
     delete reinterpret_cast<SampleClass*>(hnd);
  }

  /** Wrapper for get method */
  extern "C" __declspec(dllexport)
  int
  testlib_SampleClass_get(hSampleClass hnd){
     return reinterpret_cast<SampleClass*>(hnd)->get();
  }
#+END_SRC

*** Polymorphic class InterfaceClass 

 + File: *testlib.hpp* => Class declaration. 

As the name implies, this class is an interface class, which is a
class containing only pure virtual functions (abstract methods). As a
result, it is declared only in the header file and cannot be
instatiated directly. 

This class uses only C-types to be binary compatible with different
compilers, if it used STL containers such as string or any other
non-compatible C-type, it would not be possible to compile a C++
program using Mingw/GCC against this DLL built with MSVC.

#+BEGIN_SRC cpp 
  // Polymorphic Interface class binary compatible across different
  // compilers as it does not use any STL container on the interface.
  #ifdef __cplusplus
  struct InterfaceClass{
          /* Returns class unique ID */
          virtual const char* getID()	const = 0;
          /** Set class internal state */
          virtual void setName(const char* name) = 0;
          virtual const char* getName() = 0;

          /** Virtual constructor */
          virtual ~InterfaceClass() = default;
          // virtual ~InterfaceClass();
  };
  #else
    #define InterfaceClass void 
  #endif 
#+END_SRC

 + File: *testlib.cpp* => class ImplementationA of interface InterfaceClass. 

#+BEGIN_SRC cpp 
  class ImplementationA: public InterfaceClass
  {
  private:
      std::string m_name;
  public:
      static constexpr const char* class_id = "ImplementationA";

      ImplementationA(): m_name("Unammed-A"){ }
      ImplementationA(const std::string& name)
         : m_name(name){}	
      ~ImplementationA(){
           std::cout << " [INFO] ImplementationA deleted => name = "
                     << m_name
                     << " ; type = " << class_id
                     << std::endl;
      }
      const char* getID() const {		
          return class_id;
      }
      void setName(const char* name) {
          m_name = name;
      }
      const char* getName() {
          return m_name.c_str();
      }
  };
#+END_SRC

 + File: *testlib.cpp* => class ImplementationB of interface InterfaceClass. 

#+BEGIN_SRC cpp 
  class ImplementationB: public InterfaceClass
  {
  private:
      std::string m_name;
  public:
      static constexpr const char* class_id = "ImplementationB";

      ImplementationB(): m_name("Unammed-B"){ }
      ImplementationB(const std::string& name)
         : m_name(name){}	
      ~ImplementationB(){
          std::cout << " [INFO] ImplementationB deleted => name = "
                    << m_name
                    << " ; type = " << class_id
                    << std::endl;
      }
      const char* getID() const {		
              return class_id;
      }
      void setName(const char* name) {
              m_name = name;
      }
      const char* getName() {
              return m_name.c_str();
      }
  };

#+END_SRC

 + File: *testlib.hpp* => C-interface and factory function to load
   implementations from the DLL.

#+BEGIN_SRC cpp 
  /** Factory function */
  EXPORT_C InterfaceClass* teslib_InterfaceClass_factory(const char* class_id);

  /** C-wrapper for destructor */
  EXPORT_C void testlib_InterfaceClass_delete(InterfaceClass* hinst);

  /** C-wrapper for getID method */
  EXPORT_C const char* testlib_InterfaceClass_getID(InterfaceClass* hinst);

  EXPORT_C void testlib_InterfaceClass_setName(InterfaceClass* hinst, const char* name);

  EXPORT_C const char* testlib_InterfaceClass_getName(InterfaceClass* hinst);
#+END_SRC

 + File: *testlib.cpp* => C-interfaces and factory functions
   definitions.

#+BEGIN_SRC cpp 
  EXPORT_C InterfaceClass*
  teslib_InterfaceClass_factory(const char* class_id)
  {
      auto s = std::string(class_id);
      if(s == "ImplementationA")
              return new ImplementationA();
      if(s == "ImplementationB")
              return new ImplementationB();
      return nullptr;
  }

  EXPORT_C void testlib_InterfaceClass_delete(InterfaceClass* hinst)
  {
      delete hinst;
  }
  EXPORT_C
  const char* testlib_InterfaceClass_getID(InterfaceClass* hinst)
  {
      return hinst->getID();
  }
  EXPORT_C
  void testlib_InterfaceClass_setName(InterfaceClass* hinst, const char* name)
  {
      hinst->setName(name);
  }
  EXPORT_C
  const char* testlib_InterfaceClass_getName(InterfaceClass* hinst){
      return hinst->getName();
  }
#+END_SRC
*** DLL startup function DLLMain 

When a Windows shared library is loaded at compile-time or at runtime
by some process, the function DLLMain is always invoked, it is similar
to the function main() from an executable. 

Note: logging statements with printf, std::cout, std::cerr will not
printed if the DLL is loaded by some non-console program, a program
compiled to the _window subsystem_. Therefore, the easiest way to log is
to use the OutputDebugString function which output can viewed by the
DebugView sysinternal tool. 


 + File: *testlib.cpp* => DLL main function. 

#+BEGIN_SRC cpp 
  /** - DLL Entry point - main function of DLL which is executed when
      the DLL is loaded by some process.
   ,*/
  extern "C" __declspec(dllexport)
  BOOL APIENTRY DllMain (HINSTANCE hInst, DWORD reason, LPVOID lpReserved)
  {
     std::string text =
             std::string("DLL Loaded into the process => PID = ")
             + std::to_string(::GetCurrentProcessId());
     WindbgTrace(text);
     DbgTrace(text);	   	
      switch (reason)
      {
      case DLL_PROCESS_ATTACH:
          WindbgTrace("DLL attached to process");
          DbgTrace("DLL attached to process.");			
        break;
      case DLL_PROCESS_DETACH:
          WindbgTrace("=> DLL detached.");
          DbgTrace("=> DLL attached");
        break;
      case DLL_THREAD_ATTACH:
          WindbgTrace("DLL attached to thread");
          DbgTrace("DLL detached to thread.");
          break;
      case DLL_THREAD_DETACH:
          WindbgTrace("DLL detached from thread");
          DbgTrace("DLL detached from thread.");
        break;
      }

    return TRUE;
  }
#+END_SRC

Another more portable way to peform some way action when the DLL is
loaded by a process or unloaded is to use a static object. The startup
task is executed int the object's constructor and the finalization
task, which happens when the process ends, is executed at object's
destructor. 

 + File: *testlib.cpp* => Static Object for replacing DLLMain 

The class _StaticObject and a static instance of it is defined within
an anonymous namespace to make them private to the compilation unit
testlib.cpp and not allow them to be used from anywhere else. 

#+BEGIN_SRC cpp 
  // Class private to this compilation unit - cannot be accessed from
  // any other file
  namespace {
     class _StaticObject{		
     public:
         using Action = std::function<void ()>;
         Action m_end;

         _StaticObject(Action init, Action end)
                 :  m_end(end)
         {
                 init();
         }
         ~_StaticObject(){ m_end(); }
     };

     // Static object for replacing DLLMain 
     auto initDLL = _StaticObject(
        []{
              std::cout << " [StaticObject] => Initialize DLL"
                         << std::endl;						
        },
        []{	
             std::cout << " [StaticObject] => Shutdown DLL"
                       << std::endl;								
        });
  }
#+END_SRC
*** DLL entry point for run32dll.exe 

This function is a DLL entry point for the Windows program
rundll32.exe which can execute this function with: 

#+BEGIN_SRC cpp 
 $ rundll32.exe testlib.dll,entryPoint1
 $ rundll32.exe testlib.dll,entryPoint1 arg0 arg1 arg2 ... argn 
#+END_SRC

When the DLL testlib.dll is run with run32dll calling the function
entryPoint1, it will display a message box. 

Note: It is an optional function which could be used for installing
the DLL in the system or creating some entry in Windows' registry. 

 + File: *testlib.cpp*

#+BEGIN_SRC cpp 
  extern "C" __declspec(dllexport)
  void entryPoint1(HWND hwn, HINSTANCE hinst, LPSTR cmdLine, int nCmdShow){  
       DbgDisp(cmdLine);
       OutputDebugString("Rudll32 called entryPoint1()");
       MessageBoxA(NULL, "DLL ENTRY POINT", "Entry point 1", 0);
  }
#+END_SRC
*** C++ Client program - client1.cpp 

 + File: [[file:src/dlls/example-windows1/client1.cpp][file:src/dlls/example-windows1/client1.cpp]]  

 *File client1.cpp*

Includes: 

 + Note: (#include "testlib.hpp") a header file between quotes,
   indicates to the compiler that the header is in the same directory
   as the source file client1.cpp.

#+BEGIN_SRC cpp 
  #include <iostream>
  #include <ostream>
  #include <vector>
  #include <string>

  #include "testlib.hpp"
#+END_SRC

Declaration of functions with C-linkages not declarated in the header
testlib.hpp

#+BEGIN_SRC cpp 
  extern "C" hVectorD testlib_vectorD_make0(size_t n, double);
  extern "C" hVectorD testlib_vectorD_make1(size_t n, double array []);
  extern "C" void testlib_vectorD_delete(hVectorD hv);
#+END_SRC

Main function - Experiment 1 and Experiment 2:

#+BEGIN_SRC cpp 
  #ifndef DISABLE
  std::cout << "\n=== EXPERIMENT 1 ===> Import C++ functions from DLL" << std::endl;

  DbgTrace("Main process starts here.");
  std::vector<double> xs{1.0, 2.0, 3.0, 4.0, 5.0};
  std::cout << " => Linalg::norm(xs) " << Linalg::norm(xs) << std::endl;
  std::cout << "=> xs = "; Linalg::printVector(std::cout, xs); std::cout << std::endl;

  std::cout << "=== EXPERIMENT 2 ===> Import class from DLL" << std::endl;
  auto cls = SampleClass("Dummy");
  cls.set(100);
  std::cout << "cls.getName() = " << cls.getName() << std::endl;
  std::cout << "    cls.get() = " << cls.get() << std::endl;
  #endif // -- eof DISABLE flag
#+END_SRC

Main Function - Experiment 3 

#+BEGIN_SRC cpp
  //=========>> Load functions and classes using C-interface ==============//

  std::cout << "\n== EPERIMENT 3 ===> Import C-functions from DLL - C-interface" << std::endl;

  double arr [] = {1, 2, 3, 4, 5};
  hVectorD v1 = testlib_vectorD_make1(5, arr);
  testlib_vectorD_Linalg_printVector("v1", v1);
  std::cout << "norm(v1) = " << testlib_vectorD_Linalg_norm(v1) << std::endl;

  testlib_vectorD_delete(v1);
#+END_SRC

Main Functions - Experiment 4 

#+BEGIN_SRC cpp 
  std::cout << "\n== EPERIMENT 4 ===> Non-polymorphic class with C-interface " << std::endl;

  hSampleClass hcls = testlib_SampleClass_make1("[EXPERIMENT4]ClassHandle-OOP-C-API");
  std::cout << "[EXPERIMENT 4] hcls.getName() = " << testlib_SampleClass_getName(hcls) << std::endl;
  testlib_SampleClass_set(hcls, 100);
  std::cout << "[EXPERIMENT 4] hcls.get()     = " << testlib_SampleClass_get(hcls) << std::endl;
  testlib_SampleClass_set(hcls, 200);
  std::cout << "[EXPERIMENT 4] hcls.get()     = " << testlib_SampleClass_get(hcls) << std::endl;

  testlib_SampleClass_delete(hcls);	
#+END_SRC

Main Functions - Experiment 5 

#+BEGIN_SRC cpp 
  std::cout << "\n== EPERIMENT 5 ===> Load polymorphic classes from DLL " << std::endl;

  InterfaceClass* hinstA = teslib_InterfaceClass_factory("ImplementationA");
  InterfaceClass* hinstB = teslib_InterfaceClass_factory("ImplementationB");

  std::cout << " => hinstA->getID() = " << hinstA->getID() << std::endl;
  std::cout << " => hinstA->getID() = " << hinstB->getID() << std::endl;
  hinstA->setName("ClassA-implA");
  hinstB->setName("ClassB-implB");
  std::cout << " => hinstA->getName() = " << hinstA->getID() << std::endl;
  std::cout << " => hinstB->getName() = " << hinstB->getID() << std::endl;

  // Note: If delete is used directly to delete hinstA and hinstB,
  // a segmentatin fault will happen whenc compiling with Mingw/GCC
  testlib_InterfaceClass_delete(hinstA);
  testlib_InterfaceClass_delete(hinstB);

  std::cout << " [INFO] After deleting instances" << std::endl;

  DbgTrace("Program ended OK.");
#+END_SRC

 *Compile and run client code with MSVC*

Note: Both the DLL and the client code are compiled with MSVC-2017 64
bits target.

#+BEGIN_SRC sh 
  $ cl.exe /EHsc client.cpp /nologo /Fe:client1.exe testlib.lib && client1.exe

  # Output: 
  client.cpp
     Creating library client1.lib and object client1.exp
   [StaticObject] => Initialize DLL
  testlib.cpp:39: <DllMain> DLL Loaded into the process => PID = 1112
  testlib.cpp:45: <DllMain> DLL attached to process.

  === EXPERIMENT 1 ===> Import C++ functions from DLL
  client.cpp:33: <main> Main process starts here.
   => Linalg::norm(xs) 7.4162
  => xs = [5]( 1, 2, 3, 4, 5,  )
  === EXPERIMENT 2 ===> Import class from DLL
   Instance created with name = Dummy
   Counter set to value = 100
  cls.getName() = Dummy
      cls.get() = 100

  == EPERIMENT 3 ===> Import C-functions from DLL - C-interface
  v1 = [5]( 1, 2, 3, 4, 5,  )
  norm(v1) = 7.4162

  == EPERIMENT 4 ===> Non-polymorphic class with C-interface 
   Instance created with name = [EXPERIMENT4]ClassHandle-OOP-C-API
  [EXPERIMENT 4] hcls.getName() = [EXPERIMENT4]ClassHandle-OOP-C-API
   Counter set to value = 100
  [EXPERIMENT 4] hcls.get()     = 100
   Counter set to value = 200
  [EXPERIMENT 4] hcls.get()     = 200
  testlib.cpp:159: <SampleClass::~SampleClass> SampleClass => name = [EXPERIMENT4]ClassHandle-OOP-C-API deleted

  == EPERIMENT 5 ===> Load polymorphic classes from DLL 
   => hinstA->getID() = ImplementationA
   => hinstA->getID() = ImplementationB
   => hinstA->getName() = ImplementationA
   => hinstB->getName() = ImplementationB
   [INFO] ImplementationA deleted => name = ClassA-implA ; type = ImplementationA
   [INFO] ImplementationB deleted => name = ClassB-implB ; type = ImplementationB
   [INFO] After deleting instances
  client.cpp:87: <main> Program ended OK.
  testlib.cpp:159: <SampleClass::~SampleClass> SampleClass => name = Dummy deleted
  testlib.cpp:39: <DllMain> DLL Loaded into the process => PID = 1112
  testlib.cpp:49: <DllMain> => DLL attached
   [StaticObject] => Shutdown DLL

#+END_SRC

 *[FAILURE] ABI - Issue - Compile with Mingw client1.cpp against testlib.dll built with MSVC*

The client code is compiled with Mingw and the library was built with
MSVC-2017 for 64 bits target.

Build and run client [FAILURE]:

#+BEGIN_SRC cpp 
  $ g++ client1.cpp -g -o client1-gcc.exe -std=c++14 testlib.dll  && client1-gcc.exe
  C:\Users\archbox\AppData\Local\Temp\cckNg9eZ.o: In function `main':
  client1.cpp:35: undefined reference to `Linalg::norm(std::vector<double, std::allocator<double> > const&)'
  client1.cpp:36: undefined reference to `Linalg::printVector(std::ostream&, std::vector<double, std::allocator<double> >&)'
  client1.cpp:39: undefined reference to `SampleClass::SampleClass(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
  client1.cpp:40: undefined reference to `SampleClass::set(int)'
  client1.cpp:41: undefined reference to `SampleClass::getName[abi:cxx11]() const'
  client1.cpp:42: undefined reference to `SampleClass::get()'
  client1.cpp:39: undefined reference to `SampleClass::~SampleClass()'
  client1.cpp:39: undefined reference to `SampleClass::~SampleClass()'
  collect2.exe: error: ld returned 1 exit status
  Compilation exited abnormally with code 1 at Sun Dec 16 17:41:47
#+END_SRC

The compilation fails because C++ does not have a standard and stable
ABI - Application Binary Interface, as a result, it is not possible to
use an object-code (here - any type of compiled code) built by a
different compiler than the current one. The ABI comprises the name
mangling schema or name decoration schema which is compiler-dependent,
padding, class memory layout and so on. In addition to ABI issues, the
STL - Standard Template Library implementations may not be compatible
and also not be the same across different compilers. 

The only way to ensure that a DLL can work with all possible compilers
is to use a functions with C-linkage (extern "C") with opaque pointers
(void*) for passing around classes and wrapped STL containers. Classes
can be used by different compilers, only if they are interface classes
(classes with only pure virtual functions) containing only
C-compatible types in the declaration. 


 *Compile with Mingw client1.cpp against testlib.dll built with MSVC*

The compilation works when compiling with the custom flag -DDISABLE.
The directive _#ifndef DISABLE ... #endif_ removes all usages of the
namespace Linalg and the class SampleClass. This flag makes main the
function use only functions with C-linkage and the interface class
InterfaceClass.

#+BEGIN_SRC cpp 
$ g++ client.cpp -g -o client-gcc.exe -std=c++14 testlib.dll -DDISABLE   && client-gcc.exe

   [StaticObject] => Initialize DLL
  testlib.cpp:39: <DllMain> DLL Loaded into the process => PID = 5724
  testlib.cpp:45: <DllMain> DLL attached to process.

  == EPERIMENT 3 ===> Import C-functions from DLL - C-interface
  v1 = [5]( 1, 2, 3, 4, 5,  )
  norm(v1) = 7.4162

  == EPERIMENT 4 ===> Non-polymorphic class with C-interface 
   Instance created with name = [EXPERIMENT4]ClassHandle-OOP-C-API
  [EXPERIMENT 4] hcls.getName() = [EXPERIMENT4]ClassHandle-OOP-C-API
   Counter set to value = 100
  [EXPERIMENT 4] hcls.get()     = 100
   Counter set to value = 200
  [EXPERIMENT 4] hcls.get()     = 200
  testlib.cpp:159: <SampleClass::~SampleClass> SampleClass => name = [EXPERIMENT4]ClassHandle-OOP-C-API deleted

  == EPERIMENT 5 ===> Load polymorphic classes from DLL 
   => hinstA->getID() = ImplementationA
   => hinstA->getID() = ImplementationB
   => hinstA->getName() = ImplementationA
   => hinstB->getName() = ImplementationB
   [INFO] ImplementationA deleted => name = ClassA-implA ; type = ImplementationA
   [INFO] ImplementationB deleted => name = ClassB-implB ; type = ImplementationB
   [INFO] After deleting instances
  client.cpp:87: <main> Program ended OK.
  testlib.cpp:39: <DllMain> DLL Loaded into the process => PID = 5724
  testlib.cpp:49: <DllMain> => DLL attached
   [StaticObject] => Shutdown DLL
#+END_SRC








** TODO Shared Libraries on Linux 
