#+INCLUDE: theme/style.org
#+TITLE: CPP / C++ - Preprocessor and Macros 
#+DESCRIPTION: cpp c++ code examples preprocessor macros define assertion 
#+STARTUP: content 

* Preprocessor and macros 
** General Predefined Macros  

C++ Provides some useful predefined macros for debugging, logging,
compiler identification and detecting the version of C++ standard the
compiler is using. 

| Macro               | Description                                                   | Compiler                                  |
|---------------------+---------------------------------------------------------------+-------------------------------------------|
| ~__LINE__~            | Contains current line number of the program.                  | all                                       |
| ~__FILE__~            | Name of current file.                                         | all                                       |
| ~__DATE__~            | Date in the format month/day/year                             | all                                       |
| ~__TIME__~            | Contains a string in the format hour:minute:second            | all                                       |
|                     |                                                               |                                           |
| ~__cplusplus~         | Contains C++ standard Version string                          |                                           |
|                     |                                                               |                                           |
| =__FUNCTION__=        | Print name of current function or method (member function)    | all                                       |
| =__PRETTY_FUNCTION__= | Print name of current function or method with type signature. | GGC/G++, Mingw(GCC for Windows) and Clang |
| =__FUNCSIG__=         | Print name of current function with type signature.           | MSVC(aka VC++)                            |
|                     |                                                               |                                           |

The macro: ~__cplusplus~ is useful for identifying if the code is being
compiled with C or C++ compiler and also get the version C++ standard
the code is being compiled. 

|----------------------------+---------------------------------------------------|
| Value of Macro ~__cplusplus~ | C++ Version                                       |
|----------------------------+---------------------------------------------------|
| Not defined.               | N/A the code is being compiled with a C-compiler. |
| 199711L                    | C++98/C++03                                       |
| 201103L                    | C++11                                             |
| 201402L                    | C++14                                             |
| 201703L                    | C++17                                             |
| N/A                        | C++20  - Still waiting                            |
| N/A                        | C++ with module system? - Only gosh knows!        |
| N/A                        | C++ with a standardized ABI - "Keep on dreaming!" |
|----------------------------+---------------------------------------------------|

Example: 

#+BEGIN_SRC cpp 
  cout << " time = " << __TIME__
       << " file = " << __FILE__
       << " line = " << __LINE__
       << "  variable  = " << value
       << endl;
#+END_SRC

** Macros for detecting platform or operating system 

The preprocessor macros can be used for cross platform compilation,
creating cross platform libraries and isolating platform-specific 
code. 

*Macros for detecting Operating System and Platform* 

| Operating System               | OS Family | Macro                          | Description                                                    |
|--------------------------------+-----------+--------------------------------+----------------------------------------------------------------|
|                                |           |                                |                                                                |
| Windows 32 and 64-bits         | WinNT     | ~_WIN32~                         | Defined when compiling on Windows with Msvc(Visual C++) or Gcc |
| Windows 64 bits                | WinNT     | ~_WIN64~                         | Windows 64 bits.                                               |
| Windows CE                     | WinCE     | ~_WIN32_WCE~                     | Windows CE Kernel for embedded systems.                        |
| MSDOS                          |           | MSDOS or ~__MSDOS__~             |                                                                |
| OS2                            |           | OS2 or ~_OS2~ or ~__OS2__~         | IBM's old OS2 Operating System.                                |
|                                |           |                                |                                                                |
| Unix-like                      | Unix      | ~__unix__~                       | Check whether OS is unix-like (Linux, BSD-variant), Mac OSX)   |
| Linux                          | Unix      | ~__linux__~                      | Defined when compiling on Linux with Gcc or Clang              |
| Android                        | Unix      | ~__ANDROID__~                    | Android NDK.                                                   |
| MacOSX and IOS (Darwin Kernel) | Unix      | ~__apple__~, ~__APPLE__~, ~__MACH__~ | -                                                              |
| BSD                            | Unix      | ~__bsd__~                        | -                                                              |
| Free BDS                       | Unix      | ~__FreeBSD__~                    |                                                                |
| Net BSD                        | Unix      | ~__NetBSD__~                     |                                                                |
| QNX                            | Unix      | ~__QNX__~                        |                                                                |
| VxWorks                        | -         | ~__VXWORKS__~ or ~__vxworks~       |                                                                |
| Minix                          | Unix      | ~__minix~                        |                                                                |
| NaCL                           |           | ~__native_client__~              |                                                                |
| AsmJS                          |           | ~__asmjs__~                      |                                                                |
|                                |           |                                |                                                                |
|                                |           |                                |                                                                |

Usage example: 

#+BEGIN_SRC cpp 
  void makeDirectory(std::string path){
      #if defined __linux__ || defined __apple__ || defined __bsd__
        mkdir(path.c_str(), 0777);
      #elif _WIN32
        wchar_t* wtext = winUtils::stringToLPWSTR(path);
      CreateDirectoryW(wtext, NULL);
        delete [] wtext;
      #else
        #error "Unknown platform"
      #endif
  }
#+END_SRC

** Macros for detecting compiler 

Compiler detection: 

| Macro                       | Compiler                                                          |
|-----------------------------+-------------------------------------------------------------------|
| *Compiler*                    |                                                                   |
| ~__GNUC__~                    | GNU C/C++ Compiler.                                               |
| ~__MINGW32__~                 | Mingw or GNU C/C++ Compiler ported for Windows NT.                |
| ~__MINGW64__~                 | Mingw or GNU C/C++ Compiler ported for Windows NT - 64 bits only. |
| ~__GFORTRAN__~                | Fortran / GNU Fortran Compiler                                    |
|                             |                                                                   |
| ~__clang__~                   | Clang / LLVM Compiler                                             |
|                             |                                                                   |
| ~_MSC_VER~                    | Microsoft Visual Studio Compiler MSVC                             |
| ~_MANAGED~ or ~__cplusplus_cli~ | Compilation to C++/CLI .NET (CLR) bytecode                        |
|                             |                                                                   |
| ~__INTEL_COMPILER~            | Intel C/C++ Compiler                                              |
| ~__PGI~ or ~__PGIC__~           | Portland Group C/C++ Compiler                                     |
|                             |                                                                   |
| ~__BORLANDC__~                | Borland C++ Compiler [DEPRECATED]                                 |
|                             |                                                                   |
| ~__EMSCRIPTEN__~              | emscripten (asm.js - web assembly)                                |
| ~__asmjs__~                   | asm.js                                                            |
| ~__wasm__~                    | WebAssembly                                                       |
| ~__NVCC__~                    | NVCC                                                              |
|                             |                                                                   |
| ~__CLING__~                   | CERN's ROOT Cling C++ Interactive Shell                           |
|                             |                                                                   |
|                             |                                                                   |
| *C/C++-library*               |                                                                   |
| ~__GLIBCXX__~                 | Libstdc++                                                         |
| ~_LBCPP_VERSION~              | LibC++                                                            |
| ~_MSC_VER~                    | MSVC C++ Library (Runtime)                                        |
| ~__GLIBC__~                   | GNU LibC runtime                                                  |
| ~__BIONIC__~                  | Bionic LibC runtime. (Android's C-library modified from BSD)      |
|                             |                                                                   |
|                             |                                                                   |


See also: 

 + GCC - [[https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html][The C Preprocessor: Common Predefined Macros]]
 + [[https://sourceforge.net/p/predef/wiki/OperatingSystems/][Pre-defined Compiler Macros / Wiki / OperatingSystems]]
 + [[https://abseil.io/docs/cpp/platforms/macros][abseil / Platform Check Macros]]
 + [[https://stackoverflow.com/questions/142508/how-do-i-check-os-with-a-preprocessor-directive][c - How do I check OS with a preprocessor directive? - Stack Overflow]]
 + [[https://msdn.microsoft.com/en-us/library/468x0ea1.aspx][How to: Detect -clr Compilation]]
 + [[https://stackoverflow.com/questions/9976194/find-programmatically-if-under-c-or-c-cli][compilation - Find programmatically if under C++ or C++/CLI - Stack Overflow]]

** Macros for checking whether the compiler is 32 or 64 bits 

The following macros, taken from [[https://stackoverflow.com/questions/1505582/determining-32-vs-64-bit-in-c][(SO 1505582)]], are useful for checking
whether the compiler is 32 bits (Intel x86 based-processor) or 64 bits
(Intel x86-64 based processor). 

Macros:

#+BEGIN_SRC cpp 
  // Check windows
  #if _WIN32 || _WIN64
     #if _WIN64
       #define ENV64BIT
    #else
      #define ENV32BIT
    #endif
  #endif

  // Check GCC
  #if __GNUC__
    #if __x86_64__ || __ppc64__
      #define ENV64BIT
    #else
      #define ENV32BIT
    #endif
  #endif
#+END_SRC

Sample usage: 

#+BEGIN_SRC cpp 
    #if defined(ENV64Bits)
        std::cout << " [TRACE] 64 Bits - x86_64 " << std::endl;
    #else 
        std::cout << " [TRACE] 32 Bits - x86" << std::endl;
    #endif
#+END_SRC

** Useful macros for debugging and tracing 

Usage: Put this block at the top of the file to debug or log or in a
separate header file and compile with the flag ~-DDEBUG_MODE~, for
instance. _$ g++ file1.cpp fil2.cpp -DDEBUG_MODE_ 

#+BEGIN_SRC cpp 
#if defined(DEBUG_MODE)
  #define disp(expr)  std::cerr << __FILE__ << ":" << __LINE__ << ":" \
      << " ; " <<  #expr << " = " << (expr)  <<  std::endl

  #define dbgloc(msg)  std::cerr << __FILE__ << ":" << __LINE__ << ":" << msg 
  #define dbgline __FILE__ << ":" << __LINE__ << ":" <<
  #define dbgtrace(msg) std::cerr << __FILE__ << ":" << __LINE__ << ": TRACING " << msg << "\n";
#else
  #define disp(expr) 
  #define dbgloc(msg)  
  #define dbgline 
  #define dbgtrace(msg) 
#endif 
#+END_SRC


Note: the program's stdout output is clickable in Emacs which allows
to go quickly to the code location that generated the output. To
compile and run a c++ program in Emacs use: 

 $ ~M-x compile g++ program1.cpp program2.cpp -o out.bin -DDEBUG_MODE && ./out.bin~

 *Macro dbgtrace*

The macro dbgtrace creates the message shown in the following code
block displaying the file and the line where the message was
generated:  

Sample usage:

 - dbtrace("invoking copy constructor")

Output example: 

#+BEGIN_SRC sh 
   gslLinalg.cpp:46: TRACING invoking copy constructor
#+END_SRC

 *Macro disp*

The macro disp displays any expression in the way it is written, it is
useful to create C++ code demonstration and creating proof-of-concept
programs. 

Sample usage: 

 - disp(x * x + 10);

Output example: 

#+BEGIN_SRC sh 
   math1.cpp:10: ; x * x + 10 = 19
#+END_SRC
** Custom Assertion Macro 
*** Simple assertion macro 

Example: 

#+BEGIN_SRC cpp 
  #include <iostream>
  #include <cassert>

  #define ASSERTION_ENABLED

  // Requires header: <cassert>
  #ifdef  ASSERTION_ENABLED
    #define ASSERT(condition, text)    \
                { if (!(condition)) {	 \
                                 std::cerr << " [ASSERTION] " <<  __FILE__ << ":" << __LINE__ << ": " \
                               << text << "\n" ;  \
                                 assert(condition);   }}
  #else
    #define ASSERT(condition, text)
  #endif

  int main(){
          int x = 100;
          ASSERT(x > 200, "Assumption: x > 200");

          return 0;
  }
#+END_SRC

When the assertion fails, it prints the message: 

#+BEGIN_SRC sh 
  g++ scractch.cpp -o scractch.bin -g -std=c++1z -Wall -Wextra && ./scractch.bin
   [ASSERTION] scractch.cpp:33: Assumption: x > 200
  scractch.bin: scractch.cpp:33: int main(): Assertion `x > 200' failed.

#+END_SRC
*** Improved assertion macro 

This assertion macro provides more context information than *assert* 
from <cassert> header. When the predicate of an assertion failure
happens, this assertion macro prints the file name, line, function and
assertion predicate where the failure happened and then terminates the
program calling std::terminate. 

#+BEGIN_SRC cpp 
  #include <iostream>

  #define ENABLE_ASSERT

  #ifdef ENABLE_ASSERT
  #define M_ASSERT(expr) \
        { \
           if(!(expr)){ \
              std::cerr << "ASSERTION FAILURE: \n"; \
              std::cerr << " => Condition: " << #expr << "\n"; \
              std::cerr << " =>  Function: " << __FUNCTION__ << "\n"; \
              std::cerr << __FILE__ << ":" << __LINE__ << ":" << "\n"; \
              std::terminate(); \
           } \
        }
  #else
  #define M_ASSERT(expr)
  #endif
#+END_SRC

Usage: 

#+BEGIN_SRC cpp 
    XMLElement* node = elem->FirstChildElement("CubeX");
    M_ASSERT(node != nullptr);
#+END_SRC

Program output when assertion fails:  

#+BEGIN_SRC sh 
  ... ... ... ... 
  ASSERTION FAILURE: 
   => Condition: node != nullptr
   =>  Function: main
  tinyxml2-test.cpp:64:
  terminate called without an active exception
#+END_SRC

*** Type equality assertion macro 

Compile-time static assertions that aborts compilation when types are
not equal. It is useful for checking assumptions about types at
compile-time. 

#+BEGIN_SRC cpp 
  #define ASSERT_TYPE_EQUAL(type, expr) \
     static_assert(std::is_same<type, expr>::value, "Expected type equality")
#+END_SRC

Usage example: 

#+BEGIN_SRC cpp 
  using iter = std::vector<int>::iterator;

  ASSERT_TYPE_EQUAL(std::random_access_iterator_tag,  iter::iterator_category);

  ASSERT_TYPE_EQUAL(int ,      iter::value_type );
#+END_SRC

** Tips and guidelines for writing macros 
*** DO NOT Use macros for defining constants

Unlike in C, in C++ is preferable to use const keyword approach for
defining constants instead of preprocessor define macros.

For instance, use: 

#+BEGIN_SRC cpp 
  // PI Number
  const double PI = 3.141592653589793; 
  // Euler's number 
  const double  E = 2.718281828459045;
  // Buffer size in bytes 
  const size_t BUFFER_SIZE = 1024; 
#+END_SRC

Instead of: 

#+BEGIN_SRC cpp 
  #define PI 3.141592653589793
  #define E  2.718281828459045
  #define BUFFER_SIZE 1024
#+END_SRC

*** Use parenthesis within macros around parameter names

Reference:  [[https://wiki.sei.cmu.edu/confluence/display/c/PRE01-C.+Use+parentheses+within+macros+around+parameter+names][PRE01-C. Use parentheses within macros around parameter names - SEI CERT C Coding Standard - Confluence]]

Example: The following code fails, if the macro argument is an
experession such as 2 + 1.

#+BEGIN_SRC cpp 
  #define CUBE(x) (x * x * x)
#+END_SRC

So, the result of the followign invokation will be: 

#+BEGIN_SRC cpp 
  // Expected value 81 / 3^3 = 81/27 = 3
  int k = 81 / CUBE(2 + 1); 
  // Remember the macro just does text substitution. 
  int k = 81 / ( 2 + 1 * 2 + 1 * 2 + 1 );
  int k = 81 / ( 2 + 2 + 2 + 1 ) = 81/7 = 11;
  // Expected k = 3, but got k = 11 
  int k = 11;
#+END_SRC

The correct way to define this macro is to enclose the references to
the macro's arguments in its body. 

#+BEGIN_SRC cpp 
  #define CUBE(x) ((x) * (x) * (x))
#+END_SRC

Now, it works: 

#+BEGIN_SRC cpp 
  int k = 81 / CUBE(2 + 1); 
  int k = 81 / ((2 + 1) * (2 + 1) * (2 + 1));
  int k = 81 / 27;
  int k = 3;
#+END_SRC

*** Dump all GCC's preprocessor defines 

Reference: 
 + [[https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines][g++ - GCC dump preprocessor defines - Stack Overflow]]
 + [[http://nadeausoftware.com/articles/2011/12/c_c_tip_how_list_compiler_predefined_macros][C/C++ tip: How to list compiler predefined macros | Nadeau Software]]

#+BEGIN_SRC sh 
   $ gcc -dM -E - < /dev/null
   #define __DBL_MIN_EXP__ (-1021)
   #define __FLT32X_MAX_EXP__ 1024
   #define __UINT_LEAST16_MAX__ 0xffff
   #define __ATOMIC_ACQUIRE 2
   #define __FLT128_MAX_10_EXP__ 4932
   #define __FLT_MIN__ 1.17549435082228750796873653722224568e-38F
   #define __GCC_IEC_559_COMPLEX 2
   #define __UINT_LEAST8_TYPE__ unsigned char
   #define __SIZEOF_FLOAT80__ 16
   #define __INTMAX_C(c) c ## L
   #define __CHAR_BIT__ 8
   #define __UINT8_MAX__ 0xff
   ... ... ... ..
   #define __UINT_FAST16_MAX__ 0xffffffffffffffffUL
   #define __GCC_ATOMIC_SHORT_LOCK_FREE 2
   #define __INT_LEAST64_WIDTH__ 64
   #define __UINT_FAST8_TYPE__ unsigned char
   #define __ATOMIC_ACQ_REL 4
   #define __ATOMIC_RELEASE 3
#+END_SRC

*** Dump all preprocessor macros from a given header file 

Reference: [[https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines][g++ - GCC dump preprocessor defines - Stack Overflow]]

 + GCC (C-Compiler) Dump

#+BEGIN_SRC sh 
   $ echo "#include <sys/socket.h>" | gcc -E -dM - | tail -n 10
   #define SOL_LLC 268
   #define __DBL_MIN_EXP__ (-1021)
   #define AF_LLC PF_LLC
   #define __FLT32X_MAX_EXP__ 1024
   #define AF_MAX PF_MAX
   #define __UINT_LEAST16_MAX__ 0xffff
   #define __ATOMIC_ACQUIRE 2
   #define CMSG_NXTHDR(mhdr,cmsg) __cmsg_nxthdr (mhdr, cmsg)
   #define __FLT128_MAX_10_EXP__ 4932
   #define __FLT_MIN__ 1.17549435082228750796873653722224568e-38F

      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... 

   #define __P(args) args
   #define PF_LOCAL 1
   #define __ATOMIC_ACQ_REL 4
   #define __ATOMIC_RELEASE 3
   #define __fsblkcnt_t_defined 
   #define _BITS_UIO_H 1
#+END_SRC

 +  G++ (C++ Compiler) Dump 

#+BEGIN_SRC sh 
   $ echo "#include <cmath>" | gcc -x c++ -std=c++11 -dD -E - | head -n 10
   # 1 "<stdin>"
   # 1 "<built-in>"
   #define __STDC__ 1
   #define __cplusplus 201103L
   #define __STDC_UTF_16__ 1
   #define __STDC_UTF_32__ 1
   #define __STDC_HOSTED__ 1
   #define __GNUC__ 7
   #define __GNUC_MINOR__ 3
   #define __GNUC_PATCHLEVEL__ 1

   .. ... ... .. ... ... .. ... ... 

   $ echo "#include <cmath>" | gcc -x c++ -std=c++11 -dD -E - | tail -n 40
     constexpr float
     tgamma(float __x)
     { return __builtin_tgammaf(__x); }

     constexpr long double
     tgamma(long double __x)
     { return __builtin_tgammal(__x); }



     template<typename _Tp>
       constexpr typename __gnu_cxx::__enable_if<__is_integer<_Tp>::__value,
                                                 double>::__type
       tgamma(_Tp __x)
       { return __builtin_tgamma(__x); }



     constexpr float
     trunc(float __x)
     { return __builtin_truncf(__x); }

     constexpr long double
     trunc(long double __x)
     { return __builtin_truncl(__x); }



     template<typename _Tp>
       constexpr typename __gnu_cxx::__enable_if<__is_integer<_Tp>::__value,
                                                 double>::__type
       trunc(_Tp __x)
       { return __builtin_trunc(__x); }



   }
   # 1917 "/usr/include/c++/7/cmath" 3
   }
   # 1 "<stdin>" 2

#+END_SRC
