#+INCLUDE: theme/style.org
#+TITLE: Sample Modern C++ Programs 
#+DESCRIPTION: cpp/c++ code examples and demonstrations.
#+STARTUP: content 

 - [[wiki:index][Index]]

* Sample Modern C++ Programs 
** Reverse Polish Notation Interpreter for math computation 

This code is a _reverse polish notation_ ([[https://en.wikipedia.org/wiki/Reverse_Polish_notation][RPN]]) interactive interpreter
for math computation based on a subset of the old [[https://en.wikipedia.org/wiki/Forth_(programming_language)][Forth programming language]].

The RPN notation may look award, but it is very practical and
convenient for manual calculations and implementation of parsers,
evaluators and interpreters. As a result, those RPN features have
inspired some programming languages like:

  + [[https://en.wikipedia.org/wiki/Forth_(programming_language)][Forth programming language]] 

  + [[https://en.wikipedia.org/wiki/PostScript][PostScript]] 

  + [[https://en.wikipedia.org/wiki/Factor_(programming_language)][Factor programming language]]

  + [[https://en.wikipedia.org/wiki/RPL_(programming_language)][RPL - HP Calculators - programming language]]

  + HP ( Hewlett-Packard ) Calculators RPN Calculators such as:
    - [[https://en.wikipedia.org/wiki/HP_48_series][HP 48 series]] - family of scientific and engineering
      calculators which uses RPN notation.
    - [[https://en.wikipedia.org/wiki/HP-12C][HP-12C]] - Financial calculator with RPN notation.

 *Program* 

 + Source code: [[file:src/rpn-calculator.cpp][file:src/rpn-calculator.cpp]]

 + This math evaluator can be extended for implementing some embedded
   scripting language. 

 + Modern C++ Features used:
   - Dynamic Polymorphism, aka subtyping polymorphism.
   - Template metaprogramming for the generic stack container.
   - Smart Pointers for resource management.
   - C++11 Lambdas and std::function
   - C++ exceptions for error handling.

Compile: 

#+BEGIN_SRC sh 
  $ clang++ rpn-calculator.cpp -o rpn-calculator.bin  -Wall -Wextra -std=c++1z -g
#+END_SRC

Running: 

#+BEGIN_SRC sh 
$ ./rpn-calculator.bin 
 EXPR+> 10 20 +
 stack:  30
 EXPR+> 50 - 
 stack:  -20

 EXPR+> 10 *
 stack:  -200
 EXPR+> 300 +
 stack:  100

 stack:  100

 EXPR+> M_PI 2 / sin
 stack:  100 1

 EXPR+> M_PI 2 / cos
 stack:  100 1 6.12323e-17

 EXPR+> M_LN10 exp
 stack:  100 1 6.12323e-17 10

 EXPR+> clear
 stack: 

 EXPR+> 30 dup
 stack:  30 30

 EXPR+> 40 dup
 stack:  30 30 40 40

 EXPR+> clear
 stack: 

 EXPR+> 30 dup *
 stack:  900

 EXPR+> 40 dup *
 stack:  900 1600
 EXPR+> +
 stack:  2500

 EXPR+> sqrt
 stack:  50

 EXPR+> 30 dup * 40 dup * + sqrt
 stack:  50 50
 EXPR+> 

 EXPR+> quit
 Exiting REPL OK.  
#+END_SRC
