#+INCLUDE: theme/style.org
#+TITLE: CPP / C++ - Videos and Conferences 
#+DESCRIPTION: cpp c++ code examples, demonstrations, design pattern and integration.
#+STARTUP: content 

 - [[wiki:index][Index]]

* Videos and Conferences 
** Fundamentals 
*** Move Semantics in Deep - Engineering Distinguished Speaker Series: Howard Hinnant

 + [[https://www.youtube.com/watch?v=vLinb2fgkHk&feature=youtu.be][Engineering Distinguished Speaker Series: Howard Hinnant - YouTube]]
   + "Howard Hinnant spoke at Bloomberg presenting everything you need
     to know about move semantics."

Notes: 

"Special member functions are those member functions that the compiler
can be asked to automatically generate code for."

In C++ 98, there were 4 _special member_ functions that the compiler
can generate if not specified, namely: 

| Member Function           | Signature:                |
|---------------------------+---------------------------|
| Default constructor       | X()                       |
| Copy constructor          | X(const X&)               |
| Destructor                | ~X()                      |
| Copy assignment operator. | X& X::operator=(const X&) |
|---------------------------+---------------------------|

In C++11, there 6 are member functions that the compiler can generate:

| Member Function           | Signature:                |
|---------------------------+---------------------------|
| Default constructor       | X()                       |
| Copy constructor          | X(const X&)               |
| Destructor                | ~X()                      |
| Copy assignment operator. | X& X::operator=(const X&) |
| Move Constructor          | X(X&&)                    |
| Move assignment operator  | X& X::operator=(X&&)      |
|                           |                           |
|---------------------------+---------------------------|

A special member function can be: 

 + not declared 

 + implicitly declared (The compiler can be asked to generate the
   function automatically)

   + _delete_ annotation C++11

   + _default_ annotation C++11

C++ => Declaration X Definition (aka implementation)

 + _Declaration_: only method signature, class signature ... without any
   definition. Generally in *.hpp files (header files).

 + _Definition_: a full definition => Function Signature + Body =>
   Generally in *.cpp files. 
 
User-declared: 

#+BEGIN_SRC cpp 
  struct X
  {
    /* Default Constructor: User declared => The definition or implementation 
     ,* is elsewhere, generally in *.cpp file. 
     ,*/
    X() {} 

    X();           // User declared 
    X() = default; // User declared
    X() = delete;  // User declared, any attempt to use a deleted member
                   // functions yields a compile-time error.
  };
#+END_SRC

Default constructor and overload resolution (1): 

 + If the template has zero arguments, the preferred constructor will
   be the CTOR2 since according to C++ standard, the non-templated
   function will be preferred in an overload resolution.
   + TL;DR => Function CTOR2 gets called.

#+BEGIN_SRC cpp 
   struct X
   {
      // ===> CTOR1 (Variadic constructor)
      // Universal reference 
      // (It can be either, L-value reference or R-value reference.)   
      template <typename ... Args> 
       X(Args&& ... args); // Implementation is elsewhere 

      // ====> CTOR2 (If the template has zero args, this function gets called.)
      X() = default; 
   };
#+END_SRC

Default constructor and overload resolution (2): 

  + deleted members pariticipate in overload resolution.
  + members not-declared DO NOT pariticipate in overload resolution.
  + Any attempt to call the default constructor X() (CTOR2) will
    result in a compile-time error.

#+BEGIN_SRC cpp 
   struct X
   {
      // ===> CTOR1 (Variadic constructor)
      // Universal reference 
      // (It can be either, L-value reference or R-value reference.)   
      template <typename ... Args> 
       X(Args&& ... args); // Implementation is elsewhere 

      // ====> CTOR2 (If the template has zero args, this function gets called.)
      X() = delete; 
   };
#+END_SRC

Under what circunstances are special members implicitly provided by
the compiler. 

 + A user-declared destructor will inhibit the implicit declaration of
   the move members.

 + (Row D) - The implicitly defaulted copy members are deprecated. 

 + (Row D) RULE OF THREE: If any of destructor, copy-ctor or copy-assignment
   is declared, all should be declared, even if not necessary,
   specially in classes managing resources or heap-memory (free store).

 + (Row F) A user declared copy-constructor inhibit move members and the
   copy-assignment operator is deprecated. It should defined and
   declared explicitly. (RULE OF THREE)

 + (Row H) If only the move constructor is declared, the compiler sets
   the copy constructor and copy assignment as deleted and the
   constructor is not declared. The underlying class becomes a
   _move-only class_.
   + Example: std::unique_ptr. 


 *Compiler Implicitly Declares for C++11*

 + Note: The defaulted functions are only generated if they are
   used. It means, invoked in some part of the code. 

|---+---------------------+---------------+---------------+---------------+---------------+---------------+---------------|
|   |                     | default       | destructor    | copy          | copy          | move          | move          |
|   |                     | constructor   |               | constructor   | assignment    | constructore  | assignment    |
|---+---------------------+---------------+---------------+---------------+---------------+---------------+---------------|
| A | Nothing             | defaulted     | defaulted     | defaulted     | defaulted     | defaulted     | defaulted     |
| B | Any constructor     | _not declared_  | defaulted     | defaulted     | defaulted     | defaulted     | defaulted     |
| C | Default Constructor | *user declared* | defaulted     | defaulted     | defaulted     | defaulted     | defaulted     |
| D | Destructor          | defaulted     | *user declared* | *defaulted    | *defaulted    | not declared  | not declared  |
| F | Copy constructor    | _not declared_  | defaulted     | *user declared* | *defaulted    | not declared  | not declared  |
| G | Copy assignment     | defaulted     | defaulted     | defaulted     | *user declared* | not declared  | not declared  |
| H | Move constructor    | not declared  | defaulted     | deleted       | deleted       | *user declared* | not declared  |
| I | Move assignment     | defaulted     | defaulted     | deleted       | deleted       | not declared  | *user declared* |
|---+---------------------+---------------+---------------+---------------+---------------+---------------+---------------|

 *Compiler Implicitly Declares for C++98/03*

|---+---------------------+---------------+---------------+---------------|
|   |                     | default       | destructor    | copy          |
|   |                     | constructor   |               | constructor   |
|---+---------------------+---------------+---------------+---------------|
| A | Nothing             | defaulted     | defaulted     | defaulted     |
| B | Any constructor     | _not declared_  | defaulted     | defaulted     |
| C | Default Constructor | *user declared* | defaulted     | defaulted     |
| D | Destructor          | defaulted     | *user declared* | *defaulted    |
| F | Copy constructor    | _not declared_  | defaulted     | *user declared* |
| G | Copy assignment     | defaulted     | defaulted     | defaulted     |
|---+---------------------+---------------+---------------+---------------|

The function std::move, just casts an L-value (X&) to R-value
(generally temporary objects from which it is not possible to take an
address) (X&&). It has to use, to force the invocation of move
constructor or move assignment operator for transfering resource
ownership.

All STL containers have move constructors and move assignment
operator by default which makes efficient to return them by value from
functions. 

 *Can I define one special member function in terms of another?*

  + YES. It turns out that it is possible.
  + However, the lecturer advises to NOT DO SO. Advice: "Give each
    special member function the tender loving care it deserves."
    Specially move semantics which can enhance performance
    significantly.
  + The entire point of move semantics is to boost performance.


 *Copy and Swap Idiom* 

 + Note: This trick is neat, however it has some performance cost. The
   code can be optimized by writing both copy-assignment and
   move-assignment individually.
 + Benefit: _Strong exception safety_ 

#+BEGIN_SRC cpp 
  class X
  {
   std::vector<int> m_v;
   public: 
   // Implements both copy and move assignment operator. 
   X& operator=(X x){
      m_v.swap(x.m_v);
      return *this;
   }
  };
#+END_SRC

 *Rule of Zero* 

 + If the class only uses STL containers as member functions (not
   pointers or unrwapped resources such as socket handlers), most of
   the time, it is not necessary to define the special member
   functions explicitly and the default generated member functions
   already have optimal performance.

#+BEGIN_SRC cpp 
  class X
  {
   std::vector<int> m_v;
   public: 
   // ===> Everything declared explicitly 
   // as explicit is always better than implicit. 
   //----------------------------------

   /* Default ctor */
   X() = default; 
   /* Default dtor */
  ~X() = default; 
   /* Default copy-ctor */
   X(const X&) = default; 
   /* Default move-ctor */
   X(X&&) = default;
   /* Copy assignment operator */
   X& operator=(const X&)  = default;
   /* Move assignment operator */
   X& operator=(const X&&) = default;
  };
#+END_SRC

 *Trick for strong exception sfaety on assignment*

Note: It is an alternative to copy-and-swap diim. 

#+BEGIN_SRC cpp 
  template <class C>
  C& strong_assign(C& dest, C src){
    std::swap(dest, src);
    return dest;
  }
#+END_SRC

Usage: 

#+BEGIN_SRC cpp 
  // Instead of assignment 
  x = y; 

  // Use - strong_assign where 
  // strong exception safety is needed. 
  // Gets the best of both worlds.
  strong_assign(x, y);
#+END_SRC

 *In a hurry?* 

If there is not time think carefully, the copy members should be
deleted. It disables all the special members, except the destructor
which is implicitly declared. Any attempt to use any of disabled
members functions results in a compile-time error. 

#+BEGIN_SRC cpp 
  class X
  {
   public:
      X(const X& X) = delete;
      X& operator=(const X& X) = delete;
  };
#+END_SRC

 *What is the state of a moved-from object?* 

 + The state from a moved-from object is often unspecified. It is not
   the same as undefined behavior, just the object's state is not
   known. 

 *What is a precondition?* 

 + A requirement in the function specification which restricts the
   state of the object prior to the call. For instance,
   + std::vector<T>::pop_back()
   + Requires the PRECONDITION: empty() shall be false before changing
     the state of the vector.

 *Summary* 

 + Known when the compiler is defaulting or deleting special member
   for you, and what defaulted memebrs will do.
 + Always define or delete special members whn the compiler's implicit
   action is not corret.
 + Give tender lovign care to each of 6 special member functions, even
   if the result is to let the compiler handle it. 

*** Series - Dive in C++14 (Game Oriented) - Vittorio Romeo

 *Dive into C++11*

 * [[https://www.youtube.com/watch?v=_4K3tsKa1Uc&index=1&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e][Dive into C++11 - <1> - Arkanoid clone in 160~ lines of code (SFML 2.1)]]

 * [[https://www.youtube.com/watch?v=tPbrWAbzyTE&index=2&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e][Dive into C++11 - <2> - Frametime, FPS, constexpr, uniform initialization]]

 * [[https://www.youtube.com/watch?v=0TGp0o1KnG8&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e&index=3][Dive into C++11 - <3> - Automatic lifetime, pointers, dynamic allocation]]

 * [[https://www.youtube.com/watch?v=zMdD-s5_BIY&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e&index=4][Dive into C++11 - <4> - Smart pointers]]

 * [[https://www.youtube.com/watch?v=QAmtgvwHInM&index=6&t=0s&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e][Dive into C++11 - <5> - Game entity management basics]]
   + Entity component system.

 *Dive into C++14*

 * [[https://www.youtube.com/watch?v=WZYKzCsACiw&index=6&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e][Dive into C++14 - <1> - Introduction to C++14 core language features]]
   + Note 1: Contexpr => Can have loops, for-loops and doesn't need to be
     recursive as before. It is useful for computing look-up tables,
     hash, CRC32 and checksums at compile-time.

   + Note 2: Return type deduction => Return type can be omitted.
     However, it can be make the code harder to read.

   + Note 3: Variable templates. Allows computing numerical constats
     at compile-time such as PI with some precision.

   + Note 4:
     + Lambda functions can have _auto_ argument or argument type
       deduction.
     + Lambda functions can have variadic parameter pack.

 * [[https://www.youtube.com/watch?v=Za92Tz_g0zQ&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e&index=7][Dive into C++14 - <2> - `for_each_argument` explained and expanded]]

 * [[https://www.youtube.com/watch?v=Ehdl6j3Ace4&index=8&list=PLTEcWGdSiQenl4YRPvSqW7UPC6SiGNN7e][Dive into C++14 - <3> - Generic "unique resource" wrapper]]

** Misc 
*** Bjarne Stroustrup - The Essence of C++

- [[https://www.youtube.com/watch?v=86xWVb4XIyE][Bjarne Stroustrup - The Essence of C++]]
  - "Bjarne Stroustrup, creator and developer of C++, delivers his
    talk entitled, The Essence of C++. Stroustrup has held
    distinguished posts at Texas A&M University and spent significant
    time in the Computer Science Departments of Cambridge, Columbia
    and Princeton. C++ is the one of the world's most widely used
    technology languages and it has influenced newer languages such
    as C# and Java as well as older languages."
    + Applications on System Programming Domains:
      - Device drivers
      - Network drivers
      - Embedded Systems
      - Suitable for hard and soft real time systems.
    + C++ Origin: C + Simula (First Object Oriented language)
    + Main Ideas:
      - Direct map to hardware
      - Zero-overhead abstraction
      - Much of inspiration comes from operating systems.
      - Backward compatibility: Avoid breaking old code.
    + Key strengths:
      + A language for building lightweight abstractions.
      + Software infrastructure.
      + Resource-constrained application. (May be embedded systems)
      + Resource Management
*** CppCon 2017: Michael Spencer "My Little Object File: How Linkers Implement C++"

 - [[https://www.youtube.com/watch?v=a5L66zguFe4][CppCon 2017: Michael Spencer “My Little Object File: How Linkers Implement C++” - YouTube]]
   - "Ever wonder how the linker turns your compiled C++ code into an
     executable file? Why the One Definition Rule exists? Or why your
     debug builds are so large? In this talk we'll take a deep dive
     and follow the story of our three adventurers, ELF, MachO, and
     COFF as they make their way out of Objectville carrying C++
     translation units on their backs as they venture to become
     executables. We'll see as they make their way through the tangled
     forests of name mangling, climb the cliffs of thread local
     storage, and wade through the bogs of debug info. We'll see how
     they mostly follow the same path, but each approach the journey
     in their own way.  We'll also see that becoming an executable is
     not quite the end of their journey, as the dynamic linker awaits
     to bring them to yet a higher plane of existence as complete C++
     programs running on a machine."
*** C++NOW 2018: Michael Caisse - Modern C++ in Embedded Systems 

 + [[https://www.youtube.com/watch?v=1l2g2dAobXA][Modern C++ in Embedded Systems - YouTube]]
   + "For nearly 35 years I have been working with small processors
     and there has always been deep divides between practitioners of
     languages. When writing assembly we ridiculed those using C and
     when I spent years microcoding we scoffed at everyone. However,
     nearly all groups continue to wag their heads at the shameful C++
     programmers attempting to twist their tools toward the
     small. Recent language developments have made C++ the obvious
     choice for many embedded projects; nevertheless, the toxic
     environment extends past reddit roasts into poor vendor support
     of tools and nearly obstructionist chip manufacturers. This
     session will use a bare-metal project started in 2018 for a Ciere
     client as a case study while we work through the decision process
     for using C++, the acrobatics required to support the language,
     recent language features that enable goals of size, speed, and
     expressiveness, and useful libraries. While the examples will be
     based on a concrete project, the extracted lessons-learned should
     be applicable to many embedded projects (bare-metal and
     small-OS). Attendees will walk away with motivations to use C++
     in embedded projects, hints and tips to making tools work, and a
     sampling of language features and idioms that improve the quality
     of a final product."


See: https://arobenko.gitbooks.io/bare_metal_cpp/content/


What is shown:

   + Case presented: An ARM-based embedded processor is used for
     controlling motors and a hydraulic machine. 

   + Processor used: ARM Cortex RC4 connected to a FPGA (Filed
     Programmable Gate Array).

   + Peripherals mentioned: I2C, SPI

   + Tooling:
     + GCC toolchain for ARM
     + CMAKE for build automation.
     + Linker script

   + State Machine => Boost.SML (https://youtu.be/1l2g2dAobXA?t=4335)
     + Typical state machines used: _Mealy's state_ machine.
     + https://github.com/boost-experimental/sml

   + LADON - Real time object oriented modelling from 90's (prodecessor for
     UML Real time extensions) => Distributed State Machines.
     + Allows to connect multiple state machines.

   + Metaprogramming techniques used:
     + tag dispatching
     + CRTP => Curious Recurring Template Pattern for emulating
       dynamic polymorphism (runtime poly.) with static polymorphism
       at compile time.
     + Mixins
     + Variant Polymorphism
     + Type traits (metafunctions) => struct which takes list of types
       as arguments peforming computations on types.
     + Type synonyms with 'using' keyword

   + Common compiler options disabled on code for embedded systems:
     + Disable RTTI (-fno-rtti)
     + Disable exceptions (-fno-exceptions)

   + How can C++ simplify the project?
     + More declarative.
     + More correctness and bugs caught at compile-time.
     + Template metaprogramming is crucial for developing lightweight
       abstraction and reducing run-time overhead.

** Type Erasure and Polymorphism
*** NDC Conference 2017 - Sean Parent -  Better Code: Runtime Polymorphism

 + [[https://www.youtube.com/watch?v=QGcVXgEVMJg][Better Code: Runtime Polymorphism - Sean Parent - YouTube]]

   + Description: "This talk explains why (and how) to implement
     polymorphism without inheritance in C++. The talk contains many
     C++ tips and techniques, including many new features from
     C++11. During the course of that talk a key feature from
     Photoshop will be demonstrated and implemented."

   + Notes: This talk is about how to preserve value semantics and
     polymorphism without using inheritance in the client code. It is
     done by using the *type erasure* design pattern. Actually, the
     solution presented do use inheritance, but inside the ~object_t~
     class.

   + Benefits of the presented *type erasure* implementation:

     + Greater interoperability between software components as classes
       doesn't need to inherit froms same base class, the only
       requirement is to satisfy the constructor template constraints.

     + Alows value semantics to cohexist with polymorphism with
       minimal performance penalty. It combines the benefits of
       dynamic and static polymorphism.

     + A factory function can return a value rather than a pointer or
       smart pointer and still preserve the value semantics.

     + Non-intrusive for client code. A client code doesn't need to be
       aware of polymorphism. For instance, a client code _double describeArea(const Shape& sh)_ 
       cannot be used directly with objects returned by a factory
       function, for instance   std::unique_ptr<Shape>. By using 
       type erasure, this code  doesn't need to modified as the
       factory function can returns a value instead of a pointer and 
       still preserve the polymorphism.
       + Less error prone
       + Client code doesn't need heap allocation. (Actually, the heap
         allocation is hidden in the type erasure wrapper)
       + The client code doesn't need to worry about object ownership
         or lifetime.
       + Exception safe
       + Thread safe

     + _Referenced Book_: Stepanov, Alexander and Paul McJones -
       *Elements of Programming* - Addison Wesley - Professional 2009. 

   + Key Moments 

     + https://youtu.be/QGcVXgEVMJg?t=2032
       + The class structure is composed by concept class (interface),
         model classes inheriting the concept and the outter class
         that hides the inheritance and wraps any argument which
         statifies the template constraints.

     + https://youtu.be/QGcVXgEVMJg?t=2072
       + A virtual copy constructor is used in the concept class for
         allowing the wrapper class (outer class) object_t to preserve
         copy semantics by performing deep copying, instead of shallow
         copying.

     + https://youtu.be/QGcVXgEVMJg?t=2136 and https://youtu.be/QGcVXgEVMJg?t=2156
       + Templates used at constructor and the model. 
         
*** C++Now 2018: Louis Dionne "Runtime Polymorphism: Back to the Basics"

- [[https://www.youtube.com/watch?v=OtU51Ytfe04][C++Now 2018: Louis Dionne “Runtime Polymorphism: Back to the Basics” - YouTube]]
  + Description: "C++ solves the problem of runtime polymorphism in a very
    specific way. It does so through inheritance, by having all
    classes that will be used polymorphically inherit from the same
    base class, and then using a table of function pointers (the
    virtual table) to perform dynamic dispatch when a method is
    called. Polymorphic objects are then accessed through pointers to
    their base class, which encourages storing objects on the heap
    and accessing them via pointers. This is both inconvenient and
    inefficient when compared to traditional value semantics. As Sean
    Parent said: Inheritance is the base class of evil. It turns out
    that this is only one of many possible designs, each of which has
    different tradeoffs and characteristics. This talk will explore
    the design space for runtime polymorphism in C++, and in
    particular will introduce a policy-based approach to solving the
    problem. We will see how this approach enables runtime
    polymorphism with stack-allocated storage, heap-allocated
    storage, shared storage, no storage at all (reference semantics),
    and more. We will also see how we can get fine-grained control
    over the dispatch mechanism to beat the performance of classic
    virtual tables in some cases. The examples will be based on a
    real implementation in the Dyno library [1], but the principles
    are independent from the library."

    + Problem: C++ sub-typing polymorphism inevitably requires
      pointers to objects allocated on the heap. However by using
      pointers, the advantages of value semantics, which C++ is built
      on top, are lost. For instance, pointers doesn't play well with
      C++ algorithms and functions expecting value or reference
      parameters. Another issue is that pointers to objects allocated
      on the heap raises questions about memory ownership such as who
      should delete the pointer.

      + Ideas => some possible approaches:
        + Use static polymorphism: _template functions._
        + Use a _proxy object allocated on the stack._ The object
          inherits the base class and takes a pointer to base class
          as argument. Then the proxy object can forward any method
          call or message to the wrapped heap object.
        + Deal with it and accept as it is for performance reasons.

*** ECOOP 2015 - Bjarne Stroustrup - Object Oriented Programming without Inheritance 
 
 + [[https://www.youtube.com/watch?v=xcpSLRpOMJM][Bjarne Stroustrup - Object Oriented Programming without Inheritance - ECOOP 2015 - YouTube]]
   + Explanative talk about generic programming (templates) paradigm
     as an alternative to object oriented programming inheritance.
   + Selected Moments:
     + [[https://youtu.be/xcpSLRpOMJM?t=619][Deep Roots in earliste C++]]
     + [[https://youtu.be/xcpSLRpOMJM?t=794][Resources and resources management]]
     + [[https://youtu.be/xcpSLRpOMJM?t=1044][Move Semantics]]
     + [[https://youtu.be/xcpSLRpOMJM?t=1249][Generic Programming in C++]]
     + [[https://youtu.be/xcpSLRpOMJM?t=1566][An Example of generic interface]]
     + [[https://youtu.be/xcpSLRpOMJM?t=2088][C++ 'concepts']] (Generic programming.)

*** C++Now 2018: Odin Holmes C++ Mixins: Customization Through Compile Time Composition

 + [[https://www.youtube.com/watch?v=wWZi_wPyVvs][C++Now 2018: Odin Holmes “C++ Mixins: Customization Through Compile Time Composition” - YouTube]]
   + " Working in the embedded domain where 'special cases' are the
     norm I often find myself fighting with customization capabilities
     and 'canned' (non-customizable) abstractions. std::string often
     has a small buffer for small string optimization, std::function
     has something similar, why can't I set the size of that buffer,
     or more radically why can't I just stick that same buffer in a
     std::vector for a 'small vector optimization'. While we're at it
     why can't I take .at() out of std::vectors public interface and
     call some user-defined function on out of memory, maybe I turned
     off exceptions but still want to handle errors properly. Maybe I
     want a std::deque interface but have a fixed sized ring buffer
     under the hood. Those following the SG14 will notice I am ticking
     off proposals, the problem with these proposals is that the
     mostly follow a common pattern: "I need X without Y" or "I need X
     to have Y" and there are many many combinations of X and Y. Why
     do I have to pay for atomic ref counting in a shared_pointer in a
     single threaded use case? We could go on all day. In this talk we
     will explore the feasibility of building classes from composable
     pieces, some concrete proof of concepts as well as the library
     infrastructure needed for this task." 

** Functional Programming 
*** CppCon 2015: Stephan T. Lavavej "functional: What's New, And Proper Usage"

 + [[https://www.youtube.com/watch?v=zt7ThwVfap0][CppCon 2015: Stephan T. Lavavej “functional: What's New, And Proper Usage" - YouTube]]
   + "functional gained lots of machinery in C++11, with further
     changes in C++14 and C++17. This talk will cover what's new in
     11/14/17, focusing on how to use it properly. For example, you've
     probably used std::function, but do you know the criteria for
     activating the Small Functor Optimization? (It's not just being
     small!) We'll also look at bind(), mem_fn(), C++17's invoke(),
     and more." 

 *C++11 Lambdas Expressions*

 + Lambda expressions are core language features. They aren't ordinary
   functions or functions. Actually, lambdas are a special type of
   function-object, Functor generated by the compiler. The compiler
   converts lambda expressions into unnamed classes.

   + A lambda is just a class with member function:
     UnammedClass::operator()(Arguments ...)

 + Lambdas are not std::function. This type is polymorphic type which
   works with function-objects (aka callable objects or "functors")
   and ordinary function pointers.

 *Terminology of C++ ISO Standard*

 _Function-Object_: Anything that can be used or called like a function: 

  + Function pointers
  + Classes with operator()(Args),
  + C++11 Lambdas
  + Reference to functions (also called like a function, but the
    stdandard does not regard it as an object type)

 *C++17 std::invoke()* 

 + => Allows to call anything callable, namely:
   + function pointers
   + function objects 
   + pointers to member functions (PMFs): (obj.* pmf)(arg)
   + pointers to data member (PMDs): obj.*pmd

 _std::invoke_ provides an uniform syntax for invoking all callable
'objects' in C++.

Invoke is particurlarly useful for implementing "higher order
functions" with templates: 

#+BEGIN_SRC cpp
  #include <iostream>
  #include <functional>

  template<typename Range, typename Callable> 
  void transform_print(const Range& range, Callable fobj)
  {
     for(const auto& x : range)
        std::cout << std::invoke(fobj, x) << std::endl;
  }

  [cling]$ auto xs = std::vector<std::string>{"hello", "world", "c++17"};

  [cling]$ xs
  { "hello", "world", "c++17" }

  // Pass a member fucntion 
  [cling]$ transform_print(xs, &std::string::size);
  5
  5
  5

#+END_SRC

 *C++11 std::bind()*  

#+BEGIN_SRC cpp 
  #include <vector>
  #include <algorithm>
  #include <functional> 
  using namespace std::placeholders;

  std::vector<int> vs{1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144};

  // Count the number of elements less than 25 
  >> std::cout << "cout = " << std::count_if(vs.begin(), vs.end(), 
                                             std::bind(std::less<int>(), _1, 25)) 
                            << std::endl;
  cout = 4
  >> 

 >> auto fn = std::bind(std::less<int>(), _1, 25)

 >> fn(10)
 (bool) true
 >> fn(100)
 (bool) false
 >> fn(5)
 (bool) true
 >> fn(24)
 (bool) true
 >> fn(25)
 (bool) false
 >> 
#+END_SRC

 *Reference wrapper class definition* 

#+BEGIN_SRC cpp 
  template<typename T> class reference_wrapper
  { 
  public: 
    typedef T type;
    reference_wrapper(T&)  noexcept;
    reference_wrapper(T&&) = delete;
    reference_wrapper T&() const noexcept;
    T& get() const noexcept;

    template<typename... Args>
     std::result_of_t<T& (Args&&...)>
     operator()(Args&&...) const;
  };
#+END_SRC

 *Recommendations* 

 + Never use the old <functiona> stuff such as mem_fn
 + Remove any existing usage
 + C++98/03 algorithms/containers never needed unary_function /
   binary_function, ptr_fun() [DEPRECATED, DISCONTINUED]
 + Also remove: auto_ptr

 *std::function* 

 + function<Ret (Args) is a wrapper
   + stores a callable ob ject of abitrary type
   + tempalted on call signature, not callable object type
   + type erasure, powered by virtual functions (or equivalent)
   + Useful when code cannot be templated
     + Separately compiled code
     + Virtual function
     + Container elements
   + Requires copy-constructible function objects  

#+BEGIN_SRC cpp 
  using Function = std::function<double (double)>;
  using namespace std::placeholders;
 
  using std::bind;
  using std::plus;
  using std::multiplies;

  auto funlist = std::deque<Function>{};

  funlist.emplace_back(std::bind(plus<double>(), _1, 10))
  funlist.emplace_back(std::bind(multiplies<double>(), _1, 3))
  funlist.emplace_back((double (*) (double)) std::sin )
  funlist.emplace_back((double (*) (double)) std::cos )
  funlist.emplace_back((double (*) (double)) std::exp )
  funlist.emplace_back([](double x){ return 4 * x + 5;} )

  >> funlist
  { @0x2f27b50, @0x2f27b70, @0x2f27b90, @0x2f27bb0, @0x2f27bd0 }
  >> 

  >> for(const auto& fn: funlist){ std::cout << " => " << fn(4.0) << std::endl; }
   => 14
   => 12
   => -0.756802
   => -0.653644
   => 54.5982
   => 21

 #+END_SRC













 
  
*** CPPCON-2017: Klaus Iglberger - Free Your Functions

+ [[https://www.youtube.com/watch?v=WLDT1lDOsb4][CppCon 2017: Klaus Iglberger "Free Your Functions!"]]
  * Description: "You are devoted to minimize coupling and
    duplication? You are taking care to maximize cohesion,
    flexibility, extensibility, encapsulation, testability, and even
    performance in order to achieve the high goals of
    (object-oriented) programming? Awesome!  But wait: You still
    favor member functions? Seriously? You have been deceived! You
    have been praying at the altar of false promises! Shed the
    shackles of Java philosophy! Free your functions!. In this talk I
    will demonstrate why in C++ free functions should generally be
    preferred to member functions, and why free functions — not
    member functions! — provide you with all the aforementioned
    advantages you expect from object-oriented programming. Note,
    though, that this talk might fundamentally change your perception
    of C++ and object-oriented programming in general!"

  * _Summary and notes_:
    * _Free functions_ (ordinary functions or non-virtual functions)
      abides to object oriented principles such as OCP (Open-Close
      Principle) as they can extend a class without requiring
      modification or recompilation of the class source code.
    * _Static polymorphism_ which is a combination of free functions
      and _template metaprogramming_ can make the code more loosely
      coupled and more perfomant.
      * Becomes more loosely coupled because it doesn't require that
        arguments have any common base class or class hierarchy.
      * Becomes more performant as template generates overloaded code
        for each different type parameters combination what
        eliminates virtual function calls and dynamic
        polymorphism. The disadvantage of templates are the higher
        complexity and larger code size.
    * Benefits of Free Functions:
      - Encapsulation
      - Cohesion (SRP - Single Responsibility Principle)
      - Reuse (DRY - DO NOT REPEAT YOURSELF)
      - Overloading (Polymorphism )
      - Generic Programming (Aka template metaprogramming)
      - Abstraction
      - Testability
      - _Performance_ (Raison d'être of C++).

    * Free Functions on standard library:
      - std::begin, std::cbegin ...

    * Use free functions in order to:
      * ... wrap virtual function calls
      * ... get an homogeneous interface.
      * ... get more performant code.
      * ... more flexible and loosely-coupled code.

    * Free functions aren't are multi-paradigm, they can work with
      any paradigm. It is not necessarly functional programming. 

    * Potential Problems
      * C++ doens't have a convenient syntax for function application
        as ML-based languages like Haskell and OCaml. So, multiple
        function applications would be written as f1(f2(f3(f5 ... fn(x))))

      * _Discoverability_: according to the presentation, IDE's may not
        help to find them easily as they help to find methods (aka
        member functions). However it can mitigated with careful
        selection of namespaces which would improve code complexion
        and discoverability.
*** C++Now 2018: Ben Deane "Easy to Use, Hard to Misuse: Declarative Style in C++"

 + [[https://www.youtube.com/watch?v=2ouxETt75R4][C++Now 2018: Ben Deane “Easy to Use, Hard to Misuse: Declarative Style in C++” - YouTube]]
   + We say that interfaces should be easy to use and hard to
     misuse. But how do we get there? In this talk I will demonstrate
     how using declarative techniques in APIs, functions, and plain
     old "regular" code can help. We'll look at what is meant by
     "declarative style" in C++; explore why declarative interfaces
     are desirable and how to construct them; and take an in-depth
     look at which features of C++ help us write in a declarative
     style. I want to deconstruct C++ a bit, examine what we're doing
     and what makes the good parts good, and from that reconstruct
     some best practices. Many of us are already writing code
     following piecemeal modern advice such as "no raw loops", or
     "almost always auto", or C++ core guideline recommendations. In
     many cases, this advice translates to writing more declarative
     code; being deliberate about exploring and using declarative
     techniques gives us insight we can apply more widely.     

** Tooling 
*** LVM Euro Conference 2013 - The Clang AST - a Tutorial

+ [[https://www.youtube.com/watch?v=VqCkCDFLSsc][The Clang AST - a Tutorial - YouTube]]
  + "If you always wanted to know more about about Clang's AST [1],
    for example because you want to implement an awesome tool [2, 3]
    based on Clang, or simply because you want to start contributing,
    this talk is for you."
  + Note: Clang + LLVM suite provides many services that can be used
    to build code automation tools for C++ such as code generators
    and reflection metadata code generator.
*** CppCon 2018: "Latest and Greatest in the Visual Studio Family for C++ Developers 2018" :tooling:

  + [[https://www.youtube.com/watch?v=6NAAuxWNhk4&feature=youtu.be][CppCon 2018: “Latest and Greatest in the Visual Studio Family for C++ Developers 2018” - YouTube]]
    + "This talk will be modeled on our previously successful talks at
      CppCon. We'll give the community an update on how we are doing
      in terms of conformance where we'll be announcing the final
      conformance state for MSVC for the final 2017 update. We'll be
      showing many many demos of new features (not in previous
      versions of this talk) that target cross platform developers in
      C++. This will include making it easier to bring your code to
      Visual Studio, significant improvements to ease of use for
      developers using CMake, improvements to unit testing
      experiences, a lot of new Linux targeting improvements, an
      update on our performance work, and new debugger features for
      C++ developers. Developers will learn new tricks they can apply
      immediately on leaving the session as well as get a sense of
      what is coming in future updates. The main message is that
      Visual Studio and Visual Studio Code will make every C++
      developer (not just Windows developers) more productive." 

  + Features:

    + Fredom to target any platform from a single ID:
      + ARM/mBed, Android, Cyngwin, iOS, Linux, UWP, Windows

    + CMake compatibility

    + The VC++ Compiler has full support for C++11/14/15 language features.

      + Process Snapshot - allows to introspect process memory.

      + Macro expansion - The editor, now can expand macros when the
        mouse is hoovered over some macro.

      + Completion for templates.

      + Live Sharing => Collaboration session. 

      + Multiple cursor editing, aka multi caret editing: hold CTRL +
        ALT and click at the points where the cursor will be placed
        and then type.

      + Peek definition.

      + Compiler flags:
        + /std:c++14 (default)
        + /std:c++17
        + /std:c++latest
        + /experimental:external  - Switch to isolate code from
          external headers.

      + C++ Core Check - https:/aka.ms/CppCoreCheck

    + Integratio with other building systems: Make, Ninja, NMake, ... 

    + Code editing experience:
      + IntelliSense => Smart Code Completion 
      + Refactoring
      + Debugging
      + Reverse Debugging
      + Debug Visualization

    + Integration with other compilers and tools:
      + Clang/LLVM, GCC, Clang-format, Google-test, Boost.Test

    + Recommended Package Manger: *Vcpakge* - cross platform package
      manager which works on Linux, MacOSX and Windows. There are over
      900 libraries available in that.

      + $ vcpackage install boost sdl zlib gtest
      + https://aka.ms/vcpkg 

    + Can compile and run code in remote machines and also perform
      remote debugging. 

    + One of the most valued and loved of feature of Visual Studio is
      the *debugger*.
      + The debugger can attach to process in current or remote
        machine through SSH.

    + *CMake target view* provides a CMake-centric experience showing
      all targets, files and configuration.

    + *Open folder experience:*
      + Optmized for non-MSBuild projects => any project using CMake,
        make or other C++ building system. Target Windows, MinGW,
        Cyngwin, Linux or mBed.
      + Easy to get started
        + devenv.exe <folder>
        + File => Open => Folder ... (Ctrl + Alt +Shift + O)

    + Linux Targeting:
      + Visual Studio can connect to any linux distribution with
        GDB or GdbServer. Remove VMs, Containers, IoT (RasberryPI, Beaglebone),
        Local Windows Subsystem for Linux distros and Cross-Compile.
*** Rapid Prototyping in C++ - Dmitri Nesteruk - Meeting C++ 2015

 - [[https://www.youtube.com/watch?v=Ncy4Y-k-vLA][Rapid Prototyping in C++ - Dmitri Nesteruk - Meeting C++ 2015 - YouTube]]
   * Description: Show several techniques for fast prototyping in C++.
   * Summary:
     + CERN's ROOT Framework or CLING C++ interpreter. Allows to play
       and evaluate C++ code in the same fashion Python interpreter does.
     + Wrap the C++ library with SWIG wrapper generator to generate a Python binding and
       then prototype in the Python REPL.
     + Use a more suitable tool with fast feedback for prototyping
       such as spreadsheet, R language, Python, Matlab, Octave and so
       on.
     + Runtime compiled C++.
*** CppCon 2018: Steven Simpson "Source Instrumentation for Monitoring C++ in Production" :tooling:instrumentation:

 + [[https://www.youtube.com/watch?v=0WgC5jnrRx8&feature=youtu.be][CppCon 2018: Steven Simpson “Source Instrumentation for Monitoring C++ in Production” - YouTube]]
   + "It is essential to discuss how modern C++ code can be
     effectively instrumented, in order to effectively monitor it
     after deployment. *This talk will focus on portable source*
     *instrumentation techniques such as logging, tracing and*
     *metrics*. Straightforward, but well designed code additions can
     drastically ease the troubleshooting of functional issues, and
     identification of performance bottlenecks, in production.  Of
     course when dealing with C++ performance is often critical, and
     so minimizing the cost of any instrumentation is also
     critical. Key to this is understanding the trade-off between the
     detail of information collected, and the overheads of exposing
     that information. It is also important to understand how best to
     benefit from advances in contemporary monitoring infrastructure,
     popularised by "cloud" environments.  This talk will open with a
     brief summary of monitoring goals, infrastructure, benefits, and
     existing practise. It will then detail practicalities of building
     a set of C++ source instrumentation primitives, based on proven
     principles employed in demanding production software."

 
   + Summary + Notes + Brainstorm:
     * Use a logging library with the following features.
       + Format string (or ostream)
       + Serverity levels, [INFO], [WARNING], [FAILURE], [CRITICAL], [TRACE] ...
       + Enable/disable at runtime
       + Logs files + rotation
       + Timestamp 
       + Remote Logging
       + OS Integration => Syslog on U*nix, or OutputDebugString on Windows.

     * Error messages and exception should have context about the
       problem such as the file where it happened, code line, what
       caused the exception and so on. 

     * Log Service infrastructure:
       + Should support search, indexing, sorting and filtering.
       + Structured Logging Format: json, csv, to avoid parsing and
         writing complicated regular expressions.
       + Logging Alert
       + Logging can be stored in cloud services. 

     * Logging X Tracing

       + A more detailed logging, showing the internals of some
         operation for debugging purposes. 

       + Example about tracing: Unix utility strace which log system
         calls perfomed by a program. $ strace -ttT cat hello.txt    

     * Downsides of logging:
       * Logging may, specially writing to IO, may cause performance
         overhead on performance critical code. This is why tracing
         logging in this type of code is often disabled on deployment
         builds.
       * Tracing can be implemented with C-preprocessor macros in
         order to allow disabling it on debug builds. Using
         preprocessor has also the advatange that, when the tracing is
         disabled, it will not inccur on any rutime overhead or
         performance cost, as string concatenation will not happen and
         the code will be discarded. 
  
     * Domains where logging is essential:
       * _Network Servers and Web Servers_. => Servers are long running
         programs which runs in background as daemons without any
         graphical user interface. So logging, is the only available
         information about what is going on with the sefver.
       * _Databases_ 
       * _Embedded Systems_ => Usually doesn't have keyboard, monitor
         and etc.
       * _Industrial Instrumentation_ => Temperature, pressure, speed, ... 

     * Closing:
       * By building observable software, the software can become its
         own debugger. 

     * *Techniques for Program Instrumentation* => My Ideas.
       * Logging with some logging library
       * Debug Build 
         * Debugging Symbols 
         * Assertions => Allows to check assumptions during the
           development. 
         * Tracing
       * Use a proper debugger such as GDB, WindBG, LLDB for
         instrospecting the process. 
       * Proper error messages with enough context information. 
       * Unit Tests or some automated testing.
       * System call logger such as strace.
       * Memory Leak Detector such as Valgrind.
       * Profiler => Mesure performance.
       * Compiler with non cryptic error messages like Clang++.
       * Enforce as much correctness as possible at compile-time in
         order to catch bugs earlier before runtime and deployment.
** High Performance Computing for Math 
*** CPPCON 2016: Klaus Iglberger "The Blaze High Performance Math Library"

 - [[https://www.youtube.com/watch?v=w-Y22KrMgFE][CppCon 2016: Klaus Iglberger “The Blaze High Performance Math Library" - YouTube]]
   - "In this presentation we introduce the Blaze C++ math library, a
     hot contender for the linear algebra performance throne. Blaze
     is an open-source, high-performance library for dense and sparse
     arithmetic. It combines elegance and ease of use with HPC-grade
     performance, making it one of the most intuitive and at the same
     time fastest C++ math libraries available. We demonstrate its
     basic linear algebra functionality by means of several BLAS
     level 1 to 3 operations and explain why Blaze outperforms even
     well established linear algebra libraries. Additionally, we
     present some advanced features that enable users to adapt Blaze
     to special circumstances: custom data structures, custom
     operations, and the customizable error reporting mechanism."

     - Note: Blaze library uses _Express Template_ technique for
       compile-time generation of high-performance linear algebra
       code. 
*** Statistical scientific programming OO patterns: accumulators - Olivia Quinet - Lightning Talks :math:science:
 
 + [[https://www.youtube.com/watch?v=IwvA7oExmSo][Statistical scientific programming OO patterns: accumulators - Olivia Quinet - Lightning Talks - YouTube]]
   + "Statistical scientific programming OO patterns: accumulators -
     Olivia Quinet - Lightning Talks Meeting C++ 2017"
     + Summary: Accumulators like Boost.Accumulators allows to compute
       several statistical properties of a set of values such as a
       time series avoiding errors such as _float pointing_
       _castastrophic cancellation_ and loss of precision. _The Welford_
       _statistical formula is shown as a way to implement accumulators_
       and how it can be used to compute standard deviation and other
       statistical properties. 

See: Welford statiscal formulas & Accumulators => Incremental statical
computations. 

*** Algorithms and Iterators for Multidimensional Arrays - Cem Bassoy - Lightning Talks Meeting C++ 2017 :math:science:

  + [[https://www.youtube.com/watch?v=8P-sDH9XJAc][Algorithms and Iterators for Multidimensional Arrays - Cem Bassoy - Lightning Talks Meeting C++ 2017 - YouTube]]

Paper at:  [[https://arxiv.org/abs/1711.10912][1711.10912 - TLib: A Flexible C++ Tensor Framework for Numerical Tensor Calculus]]

Abstract:

#+BEGIN_QUOTE
Numerical tensor calculus comprise basic tensor operations such as the
entrywise addition and contraction of higher-order tensors. We
present, TLib, flexible tensor framework with generic tensor functions
and tensor classes that assists users to implement generic and
flexible tensor algorithms in C++. The number of dimensions, the
extents of the dimensions of the tensors and the contraction modes of
the tensor operations can be runtime variable. Our framework provides
tensor classes that simplify the management of multidimensional data
and utilization of tensor operations using object-oriented and generic
programming techniques. Additional stream classes help the user to
verify and compare of numerical results with MATLAB. Tensor operations
are implemented with generic tensor functions and in terms of
multidimensional iterator types only, decoupling data storage
representation and computation. The user can combine tensor functions
with different tensor types and extend the framework without further
modification of the classes or functions. We discuss the design and
implementation of the framework and demonstrate its usage with
examples that have been discussed in the literature.

#+END_QUOTE    
** C++ Binary Components + ABI + Reflection 
*** CPPCON 2016 - C++14 Reflections Without Macros, Markup nor External Tooling :reflection:metaprogramming:templates:

 + [[https://www.youtube.com/watch?v=abdeAew3gmQ][CppCon 2016: "C++14 Reflections Without Macros, Markup nor External Tooling.." - YouTube]]
   + "C++ was lacking the reflections feature for a long time. But a
     new metaprogramming trick was discovered recently: we can get
     some information about POD structure by probing it's braced
     initializes. Combining that trick with variadic templates,
     constexpr functions, implicit conversion operators, SFINAE,
     decltype and integral constants we can count structure's fields
     and even deduce type of each field.  Now the best part:
     everything works without any additional markup nor macros
     typically needed to implement reflections in C++.  In this talk
     I'll explain most of the tricks in detail, starting from a very
     basic implementation that is only capable of detecting fields
     count and ending up with a fully functional prototype capable of
     dealing with nested PODs, const/volatile qualified pointers,
     pointers-to-pointers and enum members. Highly useful use-cases
     will be shown a the end of the talk. You may start experimenting
     right now using the implementation at".
*** NDC Conference - Introduction to C++ Template Metaprogramming - Sasha Goldshtein :tmp:templates:

 + [[https://www.youtube.com/watch?v=lrziylOWBT4][Introduction to C++ Template Metaprogramming - Sasha Goldshtein]]
   + "technique in modern C++. First, TMP can be used as a precursor
     to C++17 Concepts, in order to check constraints and produce
     clear error messages when a template parameter doesn't adhere to
     its specified constraints. Second, TMP can be used to pick an
     algorithm implementation based on the template type provided --
     thus enabling optimizations for specific types. Finally, TMP can
     be used to introspect C++ types at compile-time and generate
     compile-time constructs that save time or enable
     fully-compile-time computation. In this talk, we will review a
     collection of techniques and examples for using TMP in your
     libraries and application code. You are expected to understand
     basic template syntax and template specialisation, and we will
     build the rest as we go along." 
*** CppCon 2018: Victor Ciura "These Aren't the COM Objects You're Looking For"

 + [[https://www.youtube.com/watch?v=T_1zutIBHs0][CppCon 2018: Victor Ciura “These Aren't the COM Objects You're Looking For” - YouTube]]
   + Description: "Windows COM is 25 years old. Yet it is relevant
     today more than ever, because Microsoft has bet its entire
     modern WinRT API on it (starting with Windows 8/10). But, if
     you’re familiar with the “old” COM with its idioms and SDK
     helper classes, you’re in for a treat. With the advent of modern
     C++ 17, using COM objects and new Windows APIs in your
     applications feels like a completely new experience. In this
     session, we’ll explore how using modern C++ features can
     radically transform the shape of your COM code. By eliminating a
     lot of boilerplate, your code will be much more readable and
     maintainable. Classic COM idioms around activation and
     QueryInterface() can feel totally different with modern C++
     helpers. A beautiful example of modern COM usage is C++/WinRT
     (now part of Windows SDK). This is a standard C++ language
     projection for the new Windows Runtime API.  COM memory
     management, data marshalling, string handling can all feel quite
     mechanical in nature and very error prone, so a little help from
     modern C++ facilities would be more than welcomed. Error
     handling and debugging can be cumbersome for COM like APIs;
     we’ll explore some tricks to improve this experience, as well."
*** BoostCon: John Bandela - Easy Binary Compatible C++ Interfaces Across Compilers
 
 + [[https://www.youtube.com/watch?v=BbbqBJ94-_E][John Bandela: Easy Binary Compatible C++ Interfaces Across Compilers - YouTube]]
   + Description: C++ is often perceived as hard to use and not as
     productive as other languages. One of the reasons for this is
     the lack of interoperability of binary components. When using a
     library, the user then either has to build from source (further
     complicated by the fact that there are multiple build systems)
     or the creator has to distribute multiple binaries. For example
     on Windows, one may have to distribute binaries for GCC Mingw,
     Visual C++ 2010 (release and debug, static and dynamic CRT),
     Visual C++ 2012, etc. There have been attempts to get around
     this problem. Options range from "extern C" functions, COM or
     XPCOM, or language extensions such as C++/CX. The above options
     either require compiler extensions or feel foreign and low-level
     to someone who is used to Modern C++. With C++11 being more
     consistently implemented across more compilers, one can take
     advantage of features such as lambdas and variadic templates to
     create easy to define, use, and implement binary interfaces that
     will work across compilers.
     + This presentation will discuss the design and implementation of
       a library that has the following benefits:
     + No external tools to run
       * Define an interface once and use the definition for both implementation and usage
       * Interfaces are easy to implement and use once defined
       * Use std::string, std::vector, and std::pair in the interface
       * Use real return types (not error codes)
       * Use exceptions both in implementation and usage
       * Binary compatible with COM
       * Supports interface inheritance
       * Supports implementation inheritance
       * Implementation tested on Windows with Visual C++ executable and GCC .dll
       * Implementation tested on Linux with GCC executable and Clang .so
*** BoostCon: John Bandela - CppComponents- A Modern Portable C++11 Component System

 + [[https://www.youtube.com/watch?v=a4iFJuNBx7U][CppComponents- A Modern Portable C++11 Component System - YouTube]]

*** CppCon 2017: Mathieu Ropert "API & ABI Versioning"

- [[https://www.youtube.com/watch?v=Ia3IDPjA-d0][CppCon 2017: Mathieu Ropert “API & ABI Versioning...” - YouTube]]
  - "Software keeps changing, but not always as fast as its
    clients. A key to maintaining a library in the long run is to
    ensure a proper versioning of the API and ABI. Not only does this
    gives a clear picture of both source and binary compatibility
    between the versions, but it also helps design by making breaking
    changes explicit to the developer.  In this talk I will define
    API and ABI in terms of impacts on compatibility, explain the
    difference between breaking and non-breaking changes and present
    a few techniques to handle them.  We will quickly explain what
    APIs are, with an emphasis on the notion of contracts. Then the
    usually lesser known notion of ABI will be explained, going over
    the concepts of call syntax, mangling and most importantly sizes,
    alignment and offsets in data structures. We will see how to use
    semantic versioning (semver) in C++ by considering not only
    changes to the API but also to the ABI and offer some advice on
    how to change API and ABI over time and how to minimize the
    impacts."
